################################################################
#                         Centipedes                           #
################################################################
# Description:                                                 #
# The title pretty much explains it. This program will run a   #
# random centipede at a slow speed, a random centipede  at a   #
# medium/slow speed, a random centipede at a medium speed, a   #
# a random centipede at a fast speed, then a random centipede  #
# at a random speed. 
# Requirements: PyGlow.py                                      #
#                                                              #
# Author: Paul Ryan                                            #
#                                                              #
################################################################

from PyGlow import PyGlow
from time import sleep
import random

pyglow = PyGlow()

# Initialize
pyglow.all(0)

# Variables
sleep_speed = 0.10

# Lists
centipede_ripple_speeds = [0.1, 0.075, 0.05, 0.025]

# Functions
def centipede_12(ripple_speed):
    # Variables
    ripple_speed = ripple_speed
    ''' Uncomment the following print statements for feedback '''
    #print "Centipede 12"
    #print "Centipede speed is: ", ripple_speed
    # centipede 12 Head
    pyglow.led(1, 120)
    sleep(sleep_speed)
    # Ripple Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # centipede 12 Body 1
    pyglow.led(2, 120)
    sleep(sleep_speed)
    # Ripple Body 1 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    # centipede 12 Body 2
    pyglow.led(3, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 2 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    # centipede 12 Body 3
    pyglow.led(4, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 3 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    # centipede 12 Body 4
    pyglow.led(5, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 4 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    # centipede 12 Body 5
    pyglow.led(6, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 5 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    # centipede 12 Body 6
    pyglow.led(18, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 6 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    # centipede 12 Body 7
    pyglow.led(11, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 7 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    # centipede 12 Body 8
    pyglow.led(10, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 8 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    # centipede 12 Body 9
    pyglow.led(9, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 9 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    # centipede 12 Body 10
    pyglow.led(8, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 10 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    # centipede 12 Body 11
    pyglow.led(7, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 11 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off centipede 12
    # Turn off Head 
    pyglow.led(1, 0)
    sleep(sleep_speed)
    # Ripple Body 1 - 11
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 1
    pyglow.led(2, 0)
    sleep(sleep_speed)
    # Ripple Body 2 - 11
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 2
    pyglow.led(3, 0)
    sleep(sleep_speed)
    # Ripple Body 3 - 11
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 3   
    pyglow.led(4, 0)
    sleep(sleep_speed)
    # Ripple Body 4 - 11
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 4
    pyglow.led(5, 0)
    sleep(sleep_speed)
    # Ripple Body 5 - 11
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 5
    pyglow.led(6, 0)
    sleep(sleep_speed)
    # Ripple Body 6 - 11
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 6
    pyglow.led(18, 0)
    sleep(sleep_speed)
    # Ripple Body 7 - 11
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)  
    # Turn off Body 7
    pyglow.led(11, 0)
    sleep(sleep_speed)
    # Ripple Body 8 - 11
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 8
    pyglow.led(10, 0)
    sleep(sleep_speed)
    # Ripple Body 9 - 11
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 9    
    pyglow.led(9, 0)
    sleep(sleep_speed)
    # Ripple Body 10 - 11
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 10
    pyglow.led(8, 0)
    sleep(sleep_speed)
    # Ripple Body 11
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    # Turn off Body 11
    pyglow.led(7, 0)
    sleep(sleep_speed)

    sleep(1)

def centipede_13(ripple_speed):
    # Variables
    ripple_speed = ripple_speed
    ''' Uncomment the following print statements for feedback '''
    #print "Centipede 13"
    #print "Centipede speed is: ", ripple_speed
    # Turn on centipede 13
    # Turn on Head
    pyglow.led(1, 120)
    sleep(sleep_speed)
    # Ripple Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn on Body 1
    pyglow.led(2, 120)
    sleep(sleep_speed)
    # Ripple Body 1 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    # Turn on Body 2
    pyglow.led(3, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 2 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    # Turn on Body 3
    pyglow.led(4, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 3 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    # Turn on Body 4  
    pyglow.led(5, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 4 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    # Turn on Body 5
    pyglow.led(12, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 5 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    # Turn on Body 6
    pyglow.led(18, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 6 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    # Turn on Body 7
    pyglow.led(17, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 7 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    # Turn on Body 8
    pyglow.led(16, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 8 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    # Turn on Body 9
    pyglow.led(15, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 9 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    # Turn on Body 10
    pyglow.led(14, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 10 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    # Turn on Body 11
    pyglow.led(13, 120)
    sleep(sleep_speed)
    # Ripple Body 1 - 11 and Head
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn off Head 
    pyglow.led(1, 0)
    sleep(sleep_speed)
    # Ripple Body 1 - 11
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    # Turn off Body 1
    pyglow.led(2, 0)
    sleep(sleep_speed)
    # Ripple Body 2 - 11
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    # Turn off Body 2
    pyglow.led(3, 0)
    sleep(sleep_speed)
    # Ripple Body 3 - 11
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    # Turn off Body 3
    pyglow.led(4, 0)
    sleep(sleep_speed)
    # Ripple Body 4 - 11
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    # Turn off Body 4
    pyglow.led(5, 0)
    sleep(sleep_speed)
    # Ripple Body 5 - 11
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    # Turn off Body 5
    pyglow.led(12, 0)
    sleep(sleep_speed)
    # Ripple Body 6 - 11
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    # Turn off Body 6
    pyglow.led(18, 0)
    sleep(sleep_speed)
    # Ripple Body 7 - 11
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    # Turn off Body 7
    pyglow.led(17, 0)
    sleep(sleep_speed)
    # Ripple Body 8 - 11
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    # Turn off Body 8
    pyglow.led(16, 0)
    sleep(sleep_speed)
    # Ripple Body 9 - 11
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    # Turn off Body 9
    pyglow.led(15, 0)
    sleep(sleep_speed)
    # Ripple Body 10 - 11
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    # Turn off Body 10
    pyglow.led(14, 0)
    sleep(sleep_speed)
    # Ripple Body 11
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    # Turn off Body 11
    pyglow.led(13, 0)
    sleep(sleep_speed)

    sleep(1)

def centipede_21(ripple_speed):
    # Variables
    ripple_speed = ripple_speed
    ''' Uncomment the following print statements for feedback '''
    #print "Centipede 21"
    #print "Centipede speed is: ", ripple_speed
    # Turn on centipede 21
    # Turn on Head
    pyglow.led(7, 120)
    sleep(sleep_speed)
    # Ripple head
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn on Body 1
    pyglow.led(8, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    # Turn on Body 2
    pyglow.led(9, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 2
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    # Turn on Body 3
    pyglow.led(10, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 3
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    # Turn on Body 4
    pyglow.led(11, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 4
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    # Turn on Body 5
    pyglow.led(18, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 5
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    # Turn on Body 6
    pyglow.led(6, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 6
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    # Turn on Body 7
    pyglow.led(5, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 7
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    # Turn on Body 8
    pyglow.led(4, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 8
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    # Turn on Body 9
    pyglow.led(3, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 9
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    # Turn on Body 10
    pyglow.led(2, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 10
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    # Turn on Body 11
    pyglow.led(1, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 11
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off centipede 21
    # Turn off head
    pyglow.led(7, 0)
    sleep(sleep_speed)
    # Ripple Body 1 - 11
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 1
    pyglow.led(8, 0)
    sleep(sleep_speed)
    # Ripple Body 2 - 11
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 2
    pyglow.led(9, 0)
    sleep(sleep_speed)
    # Ripple Body 3 - 11
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn offf Body 3
    pyglow.led(10, 0)
    sleep(sleep_speed)
    # Ripple Body 4 - 11
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 4
    pyglow.led(11, 0)
    sleep(sleep_speed)
    # Ripple Body 5 - 11
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 5
    pyglow.led(18, 0)
    sleep(sleep_speed)
    # Ripple Body 6 - 11
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 6
    pyglow.led(6, 0)
    sleep(sleep_speed)
    # Ripple Body 7 - 11
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 7
    pyglow.led(5, 0)
    sleep(sleep_speed)
    # Ripple Body 8 - 11
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 8
    pyglow.led(4, 0)
    sleep(sleep_speed)
    # Ripple Body 9 - 11
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 9
    pyglow.led(3, 0)
    sleep(sleep_speed)
    # Ripple Body 10 - 11
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 10
    pyglow.led(2, 0)
    sleep(sleep_speed)
    # Ripple Body 11
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 11
    pyglow.led(1, 0)
    sleep(sleep_speed)

    sleep(1)

def centipede_23(ripple_speed):
    # Variables
    ripple_speed = ripple_speed
    ''' Uncomment the following print statements for feedback '''
    #print "Centipede 23"
    #print "Centipede speed is: ", ripple_speed
    # Light up centipede 23
    # Turn on Head
    pyglow.led(7, 120)
    sleep(sleep_speed)
    # Ripple Head
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn on Body 1
    pyglow.led(8, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    # Turn on Body 2
    pyglow.led(9, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 2 
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    # Turn on Body 3
    pyglow.led(10, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 3
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    # Turn on Body 4
    pyglow.led(11, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 4
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    # Turn on Body 5
    pyglow.led(12, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 5
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    # Turn on Body 6
    pyglow.led(6, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 6
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    # Turn on Body 7
    pyglow.led(17, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 7
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    # Turn on Body 8
    pyglow.led(16, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 8
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed) 
    # Turn on Body 9
    pyglow.led(15, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 9
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed) 
    # Turn on Body 10
    pyglow.led(14, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 10
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    # Turn on Body 11
    pyglow.led(13, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 11
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn off centipede 23 
    # Turn off Head
    pyglow.led(7, 0)
    sleep(sleep_speed)
    # Ripple Body 1 - 11
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn off Body 1
    pyglow.led(8, 0)
    sleep(sleep_speed)
    # Ripple Body 2 - 11
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn off Body 2
    pyglow.led(9, 0)
    sleep(sleep_speed)
    # Ripple Body 3 - 11
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn off Body 3
    pyglow.led(10, 0)
    sleep(sleep_speed)
    # Ripple Body 4 - 11
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn off Body 4
    pyglow.led(11, 0)
    sleep(sleep_speed)
    # Ripple Body 5 - 11
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn off Body 5
    pyglow.led(12, 0)
    sleep(sleep_speed)
    # Ripple Body 6 - 11
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn off Body 6
    pyglow.led(6, 0)
    sleep(sleep_speed)
    # Ripple Body 7 - 11
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn off Body 7
    pyglow.led(17, 0)
    sleep(sleep_speed)
    # Ripple Body 8 - 11
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn off Body 8
    pyglow.led(16, 0)
    sleep(sleep_speed)
    # Ripple Body 9 - 11
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn off Body 9
    pyglow.led(15, 0)
    sleep(sleep_speed)
    # Ripple Body 10 - 11
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn off Body 10
    pyglow.led(14, 0)
    sleep(sleep_speed)
    # Ripple Body  11
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn off Body 11
    pyglow.led(13, 0)
    sleep(sleep_speed)

    sleep(1)

def centipede_31(ripple_speed):
    # Variables
    ripple_speed = ripple_speed
    ''' Uncomment the following print statements for feedback '''
    #print "Centipede 31"
    #print "Centipede speed is: ", ripple_speed
    # Light up centipede 31
    # Turn on Head
    pyglow.led(13, 120)
    sleep(sleep_speed)
    # Ripple Head
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn on Body 1 
    pyglow.led(14, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    # Turn on Body 2
    pyglow.led(15, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 2
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    # Turn on Body 3
    pyglow.led(16, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 3
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    # Turn on Body 4
    pyglow.led(17, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 4
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    # Turn on Body 5
    pyglow.led(18, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 5
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    # Turn on Body 6
    pyglow.led(12, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 6
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    # Turn on Body 7
    pyglow.led(5, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 7
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    # Turn on Body 8
    pyglow.led(4, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 8
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    # Turn on Body 9
    pyglow.led(3, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 9
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    # Turn on Body 10
    pyglow.led(2, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 10
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    # Turn on Body 11
    pyglow.led(1, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 11
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off centipede 31
    # Turn off Head
    pyglow.led(13, 0)
    sleep(sleep_speed)
    # Ripple Body 1 - 11
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 1
    pyglow.led(14, 0)
    sleep(sleep_speed)
    # Ripple Body 2 - 11
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 2
    pyglow.led(15, 0)
    sleep(sleep_speed)
    # Ripple Body 3 - 11
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 3
    pyglow.led(16, 0)
    sleep(sleep_speed)
    # Ripple Body 4 - 11
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 4
    pyglow.led(17, 0)
    sleep(sleep_speed)
    # Ripple Body 5 - 11
    pyglow.led(18, 60)
    sleep(ripple_speed)
    pyglow.led(18, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 5
    pyglow.led(18, 0)
    sleep(sleep_speed)
    # Ripple Body 6 - 11
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 6
    pyglow.led(12, 0)
    sleep(sleep_speed)
    # Ripple Body 7 - 11
    pyglow.led(5, 60)
    sleep(ripple_speed)
    pyglow.led(5, 120)
    sleep(ripple_speed)
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 7
    pyglow.led(5, 0)
    sleep(sleep_speed)
    # Ripple Body 8 - 11
    pyglow.led(4, 60)
    sleep(ripple_speed)
    pyglow.led(4, 120)
    sleep(ripple_speed)
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 8
    pyglow.led(4, 0)
    sleep(sleep_speed)
    # Ripple Body 9 - 11
    pyglow.led(3, 60)
    sleep(ripple_speed)
    pyglow.led(3, 120)
    sleep(ripple_speed)
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 9
    pyglow.led(3, 0)
    sleep(sleep_speed)
    # Ripple Body 10 - 11
    pyglow.led(2, 60)
    sleep(ripple_speed)
    pyglow.led(2, 120)
    sleep(ripple_speed)
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 10
    pyglow.led(2, 0)
    sleep(sleep_speed)
    # Ripple Body 11
    pyglow.led(1, 60)
    sleep(ripple_speed)
    pyglow.led(1, 120)
    sleep(ripple_speed)
    # Turn off Body 11
    pyglow.led(1, 0)
    sleep(sleep_speed)

    sleep(1)

def centipede_32(ripple_speed):
    # Variables
    ripple_speed = ripple_speed
    ''' Uncomment the following print statements for feedback '''
    #print "Centipede 32"
    #print "Centipede speed is: ", ripple_speed
    # Light up Centipede 32
    # Turn on Head
    pyglow.led(13, 120)
    sleep(sleep_speed)
    # Ripple Head
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    # Turn on Body 1
    pyglow.led(14, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    # Turn on Body 2
    pyglow.led(15, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 2
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    # Turn on Body 3
    pyglow.led(16, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 3
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    # Turn on Body 4
    pyglow.led(17, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 4
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    # Turn on Body 5
    pyglow.led(6, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 5
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    # Turn on Body 6
    pyglow.led(12, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 6
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    # Turn on Body 7
    pyglow.led(11, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 7
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    # Turn on Body 8
    pyglow.led(10, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 8
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed) 
    # Turn on Body 9
    pyglow.led(9, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 9
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    # Turn on Body 10
    pyglow.led(8, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 10
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    # Turn on Body 11
    pyglow.led(7, 120)
    sleep(sleep_speed)
    # Ripple Head and Body 1 - 11
    pyglow.led(13, 60)
    sleep(ripple_speed)
    pyglow.led(13, 120)
    sleep(ripple_speed)
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Centipede 32 
    # Turn off Head
    pyglow.led(13, 0)
    sleep(sleep_speed)
    # Ripple Body 1 - 11
    pyglow.led(14, 60)
    sleep(ripple_speed)
    pyglow.led(14, 120)
    sleep(ripple_speed)
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 1
    pyglow.led(14, 0)
    sleep(sleep_speed)
    # Ripple Body 2 - 11
    pyglow.led(15, 60)
    sleep(ripple_speed)
    pyglow.led(15, 120)
    sleep(ripple_speed)
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 2
    pyglow.led(15, 0)
    sleep(sleep_speed)
    # Ripple Body 3 - 11
    pyglow.led(16, 60)
    sleep(ripple_speed)
    pyglow.led(16, 120)
    sleep(ripple_speed)
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 3
    pyglow.led(16, 0)
    sleep(sleep_speed)
    # Ripple Body 4 - 11
    pyglow.led(17, 60)
    sleep(ripple_speed)
    pyglow.led(17, 120)
    sleep(ripple_speed)
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 4
    pyglow.led(17, 0)
    sleep(sleep_speed)
    # Ripple Body 5 - 11
    pyglow.led(6, 60)
    sleep(ripple_speed)
    pyglow.led(6, 120)
    sleep(ripple_speed)
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 5
    pyglow.led(6, 0)
    sleep(sleep_speed)
    # Ripple Body 6 - 11
    pyglow.led(12, 60)
    sleep(ripple_speed)
    pyglow.led(12, 120)
    sleep(ripple_speed)
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 6
    pyglow.led(12, 0)
    sleep(sleep_speed)
    # Ripple Body 7 - 11
    pyglow.led(11, 60)
    sleep(ripple_speed)
    pyglow.led(11, 120)
    sleep(ripple_speed)
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 7
    pyglow.led(11, 0)
    sleep(sleep_speed)
    # Ripple Body 8 - 11
    pyglow.led(10, 60)
    sleep(ripple_speed)
    pyglow.led(10, 120)
    sleep(ripple_speed)
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 8
    pyglow.led(10, 0)
    sleep(sleep_speed)
    # Ripple Body 9 - 11
    pyglow.led(9, 60)
    sleep(ripple_speed)
    pyglow.led(9, 120)
    sleep(ripple_speed)
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 9
    pyglow.led(9, 0)
    sleep(sleep_speed)
    # Ripple Body 10 - 11
    pyglow.led(8, 60)
    sleep(ripple_speed)
    pyglow.led(8, 120)
    sleep(ripple_speed)
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 10
    pyglow.led(8, 0)
    sleep(sleep_speed)
    # Ripple Body 11
    pyglow.led(7, 60)
    sleep(ripple_speed)
    pyglow.led(7, 120)
    sleep(ripple_speed)
    # Turn off Body 11
    pyglow.led(7, 0)
    sleep(sleep_speed)

    sleep(1)

# List of centipede functions
centipedes = [centipede_12, centipede_13, centipede_21, centipede_23,
              centipede_31, centipede_32]

# Start the program
try:
    while True:
        # Random Slow Centipede
        random.choice(centipedes)(0.1)
        # Random Slow/Medium Centipede
        random.choice(centipedes)(0.075)
        # Random Medium Centipede
        random.choice(centipedes)(0.05)
        # Random Fast Centipede
        random.choice(centipedes)(0.025)
        # Random Centipede, Random Speed
        random.choice(centipedes)(random.choice(centipede_ripple_speeds))
# Stop the program and turn off LEDs with Ctrl-C
except KeyboardInterrupt:
    pyglow.all()
