################################################################
#                     Fading Spiral Arms                       #
################################################################
# Description:                                                 #
# This program lights up the LEDs on arm 1 one at at time,     #
# then arm 2, then arm 3. Instead the lights being turned off  #
# at a time like in the Spiral Arms program, the lights        #
# gradually fade.                                              #
#                                                              #
# Requirements: PyGlow.py                                      #
#                                                              #
# Author: Paul Ryan                                            #
#                                                              #
################################################################

from PyGlow import PyGlow
from time import sleep

pyglow = PyGlow()

# Initialize
pyglow.all(0)

# Functions
def fading_spiral_arms():
    sleep_speed = 0.01
    # Turn LED 1 
    pyglow.led(1,180)
    sleep(sleep_speed)
    # Turn on LED 2 
    pyglow.led(2, 180)
    sleep(sleep_speed)
    # Fade LED 1 
    pyglow.led(1, 170)
    sleep(sleep_speed)
    # Turn on LED 3
    pyglow.led(3, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 2
    pyglow.led(1, 160)
    sleep(sleep_speed)
    pyglow.led(2, 170)
    sleep(sleep_speed)
    # Turn on LED 4
    pyglow.led(4, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 3
    pyglow.led(1, 150)
    sleep(sleep_speed)
    pyglow.led(2, 160)
    sleep(sleep_speed)
    pyglow.led(3, 170)
    sleep(sleep_speed)
    # Turn on LED 5
    pyglow.led(5, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 4
    pyglow.led(1, 140)
    sleep(sleep_speed)
    pyglow.led(2, 150)
    sleep(sleep_speed)
    pyglow.led(3, 160)
    sleep(sleep_speed)
    pyglow.led(4, 170)
    sleep(sleep_speed)
    # Turn on LED 6 
    pyglow.led(6, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 5
    pyglow.led(1, 130)
    sleep(sleep_speed)
    pyglow.led(2, 140)
    sleep(sleep_speed)
    pyglow.led(3, 150)
    sleep(sleep_speed)
    pyglow.led(4, 160)
    sleep(sleep_speed)
    pyglow.led(5, 170)
    sleep(sleep_speed)
    # Turn on LED 7 
    pyglow.led(7, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 5
    pyglow.led(1, 120)
    sleep(sleep_speed)
    pyglow.led(2, 130)
    sleep(sleep_speed)
    pyglow.led(3, 140)
    sleep(sleep_speed)
    pyglow.led(4, 150)
    sleep(sleep_speed)
    pyglow.led(5, 160)
    sleep(sleep_speed)
    pyglow.led(6, 170)
    sleep(sleep_speed)
    # Turn on LED 8
    pyglow.led(8, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 7
    pyglow.led(1, 110)
    sleep(sleep_speed)
    pyglow.led(2, 120)
    sleep(sleep_speed)
    pyglow.led(3, 130)
    sleep(sleep_speed)
    pyglow.led(4, 140)
    sleep(sleep_speed)
    pyglow.led(5, 150)
    sleep(sleep_speed)
    pyglow.led(6, 160)
    sleep(sleep_speed)
    pyglow.led(7, 170)
    sleep(sleep_speed)
    # Turn on LED 9 
    pyglow.led(9, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 8
    pyglow.led(1, 100)
    sleep(sleep_speed)
    pyglow.led(2, 110)
    sleep(sleep_speed)
    pyglow.led(3, 120)
    sleep(sleep_speed)
    pyglow.led(4, 130)
    sleep(sleep_speed)
    pyglow.led(5, 140)
    sleep(sleep_speed)
    pyglow.led(6, 150)
    sleep(sleep_speed)
    pyglow.led(7, 160)
    sleep(sleep_speed)
    pyglow.led(8, 170)
    sleep(sleep_speed)
    # Turn on LED 10 
    pyglow.led(10, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 9
    pyglow.led(1, 90)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(3, 110)
    sleep(sleep_speed)
    pyglow.led(4, 120)
    sleep(sleep_speed)
    pyglow.led(5, 130)
    sleep(sleep_speed)
    pyglow.led(6, 140)
    sleep(sleep_speed)
    pyglow.led(7, 150)
    sleep(sleep_speed)
    pyglow.led(8, 160)
    sleep(sleep_speed)
    pyglow.led(9, 170)
    sleep(sleep_speed)
    # Turn on LED 11 
    pyglow.led(11, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 10
    pyglow.led(1, 80)
    sleep(sleep_speed)
    pyglow.led(2, 90)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(4, 110)
    sleep(sleep_speed)
    pyglow.led(5, 120)
    sleep(sleep_speed)
    pyglow.led(6, 130)
    sleep(sleep_speed)
    pyglow.led(7, 140)
    sleep(sleep_speed)
    pyglow.led(8, 150)
    sleep(sleep_speed)
    pyglow.led(9, 160)
    sleep(sleep_speed)
    pyglow.led(10, 170)
    sleep(sleep_speed)
    # Turn on LED 12 
    pyglow.led(12, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 11
    pyglow.led(1, 70)
    sleep(sleep_speed)
    pyglow.led(2, 80)
    sleep(sleep_speed)
    pyglow.led(3, 90)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(5, 110)
    sleep(sleep_speed)
    pyglow.led(6, 120)
    sleep(sleep_speed)
    pyglow.led(7, 130)
    sleep(sleep_speed)
    pyglow.led(8, 140)
    sleep(sleep_speed)
    pyglow.led(9, 150)
    sleep(sleep_speed)
    pyglow.led(10, 160)
    sleep(sleep_speed)
    pyglow.led(11, 170)
    sleep(sleep_speed)
    # Turn on LED 13
    pyglow.led(13, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 12
    pyglow.led(1, 60)
    sleep(sleep_speed)
    pyglow.led(2, 70)
    sleep(sleep_speed)
    pyglow.led(3, 80)
    sleep(sleep_speed)
    pyglow.led(4, 90)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(6, 110)
    sleep(sleep_speed)
    pyglow.led(7, 120)
    sleep(sleep_speed)
    pyglow.led(8, 130)
    sleep(sleep_speed)
    pyglow.led(9, 140)
    sleep(sleep_speed)
    pyglow.led(10, 150)
    sleep(sleep_speed)
    pyglow.led(11, 160)
    sleep(sleep_speed)
    pyglow.led(12, 170)
    sleep(sleep_speed)
    # Turn on LED 14 
    pyglow.led(14, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 13
    pyglow.led(1, 50)
    sleep(sleep_speed)
    pyglow.led(2, 60)
    sleep(sleep_speed)
    pyglow.led(3, 70)
    sleep(sleep_speed)
    pyglow.led(4, 80)
    sleep(sleep_speed)
    pyglow.led(5, 90)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(7, 110)
    sleep(sleep_speed)
    pyglow.led(8, 120)
    sleep(sleep_speed)
    pyglow.led(9, 130)
    sleep(sleep_speed)
    pyglow.led(10, 140)
    sleep(sleep_speed)
    pyglow.led(11, 150)
    sleep(sleep_speed)
    pyglow.led(12, 160)
    sleep(sleep_speed)
    pyglow.led(13, 170)
    sleep(sleep_speed)
    # Turn on LED 15 
    pyglow.led(15, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 14
    pyglow.led(1, 40)
    sleep(sleep_speed)
    pyglow.led(2, 50)
    sleep(sleep_speed)
    pyglow.led(3, 60)
    sleep(sleep_speed)
    pyglow.led(4, 70)
    sleep(sleep_speed)
    pyglow.led(5, 80)
    sleep(sleep_speed)
    pyglow.led(6, 90)
    sleep(sleep_speed)
    pyglow.led(7, 100)
    sleep(sleep_speed)
    pyglow.led(8, 110)
    sleep(sleep_speed)
    pyglow.led(9, 120)
    sleep(sleep_speed)
    pyglow.led(10, 130)
    sleep(sleep_speed)
    pyglow.led(11, 140)
    sleep(sleep_speed)
    pyglow.led(12, 150)
    sleep(sleep_speed)
    pyglow.led(13, 160)
    sleep(sleep_speed)
    pyglow.led(14, 170)
    sleep(sleep_speed)
    # Turn on LED 16 
    pyglow.led(16, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 15
    pyglow.led(1, 30)
    sleep(sleep_speed)
    pyglow.led(2, 40)
    sleep(sleep_speed)
    pyglow.led(3, 50)
    sleep(sleep_speed)
    pyglow.led(4, 60)
    sleep(sleep_speed)
    pyglow.led(5, 70)
    sleep(sleep_speed)
    pyglow.led(6, 80)
    sleep(sleep_speed)
    pyglow.led(7, 90)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(9, 110)
    sleep(sleep_speed)
    pyglow.led(10, 120)
    sleep(sleep_speed)
    pyglow.led(11, 130)
    sleep(sleep_speed)
    pyglow.led(12, 140)
    sleep(sleep_speed)
    pyglow.led(13, 150)
    sleep(sleep_speed)
    pyglow.led(14, 160)
    sleep(sleep_speed)
    pyglow.led(15, 170)
    sleep(sleep_speed)
    # Turn on LED 17
    pyglow.led(17, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 16
    pyglow.led(1, 20)
    sleep(sleep_speed)
    pyglow.led(2, 30)
    sleep(sleep_speed)
    pyglow.led(3, 40)
    sleep(sleep_speed)
    pyglow.led(4, 50)
    sleep(sleep_speed)
    pyglow.led(5, 60)
    sleep(sleep_speed)
    pyglow.led(6, 70)
    sleep(sleep_speed)
    pyglow.led(7, 80)
    sleep(sleep_speed)
    pyglow.led(8, 90)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(10, 110)
    sleep(sleep_speed)
    pyglow.led(11, 120)
    sleep(sleep_speed)
    pyglow.led(12, 130)
    sleep(sleep_speed)
    pyglow.led(13, 140)
    sleep(sleep_speed)
    pyglow.led(14, 150)
    sleep(sleep_speed)
    pyglow.led(15, 160)
    sleep(sleep_speed)
    pyglow.led(16, 170)
    sleep(sleep_speed)
    # Turn on LED 18 
    pyglow.led(18, 180)
    sleep(sleep_speed)
    # Fade LED 1 - 17
    pyglow.led(1, 10)
    sleep(sleep_speed)
    pyglow.led(2, 20)
    sleep(sleep_speed)
    pyglow.led(3, 30)
    sleep(sleep_speed)
    pyglow.led(4, 40)
    sleep(sleep_speed)
    pyglow.led(5, 50)
    sleep(sleep_speed)
    pyglow.led(6, 60)
    sleep(sleep_speed)
    pyglow.led(7, 70)
    sleep(sleep_speed)
    pyglow.led(8, 80)
    sleep(sleep_speed)
    pyglow.led(9, 90)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(11, 110)
    sleep(sleep_speed)
    pyglow.led(12, 120)
    sleep(sleep_speed)
    pyglow.led(13, 130)
    sleep(sleep_speed)
    pyglow.led(14, 140)
    sleep(sleep_speed)
    pyglow.led(15, 150)
    sleep(sleep_speed)
    pyglow.led(16, 160)
    sleep(sleep_speed)
    pyglow.led(17, 170)
    sleep(sleep_speed)
    # Fade LED 1 - 18
    pyglow.led(1, 0)
    sleep(sleep_speed)
    pyglow.led(2, 10)
    sleep(sleep_speed)
    pyglow.led(3, 20)
    sleep(sleep_speed)
    pyglow.led(4, 30)
    sleep(sleep_speed)
    pyglow.led(5, 40)
    sleep(sleep_speed)
    pyglow.led(6, 50)
    sleep(sleep_speed)
    pyglow.led(7, 60)
    sleep(sleep_speed)
    pyglow.led(8, 70)
    sleep(sleep_speed)
    pyglow.led(9, 80)
    sleep(sleep_speed)
    pyglow.led(10, 90)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(12, 110)
    sleep(sleep_speed)
    pyglow.led(13, 120)
    sleep(sleep_speed)
    pyglow.led(14, 130)
    sleep(sleep_speed)
    pyglow.led(15, 140)
    sleep(sleep_speed)
    pyglow.led(16, 150)
    sleep(sleep_speed)
    pyglow.led(17, 160)
    sleep(sleep_speed)
    pyglow.led(18, 170)
    sleep(sleep_speed)
    # Fade LED 2 - 18
    pyglow.led(2, 0)
    sleep(sleep_speed)
    pyglow.led(3, 10)
    sleep(sleep_speed)
    pyglow.led(4, 20)
    sleep(sleep_speed)
    pyglow.led(5, 30)
    sleep(sleep_speed)
    pyglow.led(6, 40)
    sleep(sleep_speed)
    pyglow.led(7, 50)
    sleep(sleep_speed)
    pyglow.led(8, 60)
    sleep(sleep_speed)
    pyglow.led(9, 70)
    sleep(sleep_speed)
    pyglow.led(10, 80)
    sleep(sleep_speed)
    pyglow.led(11, 90)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(13, 110)
    sleep(sleep_speed)
    pyglow.led(14, 120)
    sleep(sleep_speed)
    pyglow.led(15, 130)
    sleep(sleep_speed)
    pyglow.led(16, 140)
    sleep(sleep_speed)
    pyglow.led(17, 150)
    sleep(sleep_speed)
    pyglow.led(18, 160)
    sleep(sleep_speed)
    # Fade LED 3 - 18
    pyglow.led(3, 0)
    sleep(sleep_speed)
    pyglow.led(4, 10)
    sleep(sleep_speed)
    pyglow.led(5, 20)
    sleep(sleep_speed)
    pyglow.led(6, 30)
    sleep(sleep_speed)
    pyglow.led(7, 40)
    sleep(sleep_speed)
    pyglow.led(8, 50)
    sleep(sleep_speed)
    pyglow.led(9, 60)
    sleep(sleep_speed)
    pyglow.led(10, 70)
    sleep(sleep_speed)
    pyglow.led(11, 80)
    sleep(sleep_speed)
    pyglow.led(12, 90)
    sleep(sleep_speed)
    pyglow.led(13, 100)
    sleep(sleep_speed)
    pyglow.led(14, 110)
    sleep(sleep_speed)
    pyglow.led(15, 120)
    sleep(sleep_speed)
    pyglow.led(16, 130)
    sleep(sleep_speed)
    pyglow.led(17, 140)
    sleep(sleep_speed)
    pyglow.led(18, 150)
    sleep(sleep_speed)
    # Fade LED 4 - 18
    pyglow.led(4, 0)
    sleep(sleep_speed)
    pyglow.led(5, 10)
    sleep(sleep_speed)
    pyglow.led(6, 20)
    sleep(sleep_speed)
    pyglow.led(7, 30)
    sleep(sleep_speed)
    pyglow.led(8, 40)
    sleep(sleep_speed)
    pyglow.led(9, 50)
    sleep(sleep_speed)
    pyglow.led(10, 60)
    sleep(sleep_speed)
    pyglow.led(11, 70)
    sleep(sleep_speed)
    pyglow.led(12, 80)
    sleep(sleep_speed)
    pyglow.led(13, 90)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(15, 110)
    sleep(sleep_speed)
    pyglow.led(16, 120)
    sleep(sleep_speed)
    pyglow.led(17, 130)
    sleep(sleep_speed)
    pyglow.led(18, 140)
    sleep(sleep_speed)
    # Fade LED 5 - 18
    pyglow.led(5, 0)
    sleep(sleep_speed)
    pyglow.led(6, 10)
    sleep(sleep_speed)
    pyglow.led(7, 20)
    sleep(sleep_speed)
    pyglow.led(8, 30)
    sleep(sleep_speed)
    pyglow.led(9, 40)
    sleep(sleep_speed)
    pyglow.led(10, 50)
    sleep(sleep_speed)
    pyglow.led(11, 60)
    sleep(sleep_speed)
    pyglow.led(12, 70)
    sleep(sleep_speed)
    pyglow.led(13, 80)
    sleep(sleep_speed)
    pyglow.led(14, 90)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(16, 110)
    sleep(sleep_speed)
    pyglow.led(17, 120)
    sleep(sleep_speed)
    pyglow.led(18, 130)
    sleep(sleep_speed)
    # Fade LED 6 - 18
    pyglow.led(6, 0)
    sleep(sleep_speed)
    pyglow.led(7, 10)
    sleep(sleep_speed)
    pyglow.led(8, 20)
    sleep(sleep_speed)
    pyglow.led(9, 30)
    sleep(sleep_speed)
    pyglow.led(10, 40)
    sleep(sleep_speed)
    pyglow.led(11, 50)
    sleep(sleep_speed)
    pyglow.led(12, 60)
    sleep(sleep_speed)
    pyglow.led(13, 70)
    sleep(sleep_speed)
    pyglow.led(14, 80)
    sleep(sleep_speed)
    pyglow.led(15, 90)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(17, 110)
    sleep(sleep_speed)
    pyglow.led(18, 120)
    sleep(sleep_speed)
    # Fade LED 7 - 18
    pyglow.led(7, 0)
    sleep(sleep_speed)
    pyglow.led(8, 10)
    sleep(sleep_speed)
    pyglow.led(9, 20)
    sleep(sleep_speed)
    pyglow.led(10, 30)
    sleep(sleep_speed)
    pyglow.led(11, 40)
    sleep(sleep_speed)
    pyglow.led(12, 50)
    sleep(sleep_speed)
    pyglow.led(13, 60)
    sleep(sleep_speed)
    pyglow.led(14, 70)
    sleep(sleep_speed)
    pyglow.led(15, 80)
    sleep(sleep_speed)
    pyglow.led(16, 90)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(18, 110)
    sleep(sleep_speed)
    # Fade LED 8 - 18
    pyglow.led(8, 0)
    sleep(sleep_speed)
    pyglow.led(9, 10)
    sleep(sleep_speed)
    pyglow.led(10, 20)
    sleep(sleep_speed)
    pyglow.led(11, 30)
    sleep(sleep_speed)
    pyglow.led(12, 40)
    sleep(sleep_speed)
    pyglow.led(13, 50)
    sleep(sleep_speed)
    pyglow.led(14, 60)
    sleep(sleep_speed)
    pyglow.led(15, 70)
    sleep(sleep_speed)
    pyglow.led(16, 80)
    sleep(sleep_speed)
    pyglow.led(17, 90)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    # Fade LED 9 - 18
    pyglow.led(9, 0)
    sleep(sleep_speed)
    pyglow.led(10, 10)
    sleep(sleep_speed)
    pyglow.led(11, 20)
    sleep(sleep_speed)
    pyglow.led(12, 30)
    sleep(sleep_speed)
    pyglow.led(13, 40)
    sleep(sleep_speed)
    pyglow.led(14, 50)
    sleep(sleep_speed)
    pyglow.led(15, 60)
    sleep(sleep_speed)
    pyglow.led(16, 70)
    sleep(sleep_speed)
    pyglow.led(17, 80)
    sleep(sleep_speed)
    pyglow.led(18, 90)
    sleep(sleep_speed)
    # Fade LED 10 - 18
    pyglow.led(10, 0)
    sleep(sleep_speed)
    pyglow.led(11, 10)
    sleep(sleep_speed)
    pyglow.led(12, 20)
    sleep(sleep_speed)
    pyglow.led(13, 30)
    sleep(sleep_speed)
    pyglow.led(14, 40)
    sleep(sleep_speed)
    pyglow.led(15, 50)
    sleep(sleep_speed)
    pyglow.led(16, 60)
    sleep(sleep_speed)
    pyglow.led(17, 70)
    sleep(sleep_speed)
    pyglow.led(18, 80)
    sleep(sleep_speed)
    # Fade LED 11 - 18
    pyglow.led(11, 0)
    sleep(sleep_speed)
    pyglow.led(12, 10)
    sleep(sleep_speed)
    pyglow.led(13, 20)
    sleep(sleep_speed)
    pyglow.led(14, 30)
    sleep(sleep_speed)
    pyglow.led(15, 40)
    sleep(sleep_speed)
    pyglow.led(16, 50)
    sleep(sleep_speed)
    pyglow.led(17, 60)
    sleep(sleep_speed)
    pyglow.led(18, 70)
    sleep(sleep_speed)
    # Fade LED 12 - 18
    pyglow.led(12, 0)
    sleep(sleep_speed)
    pyglow.led(13, 10)
    sleep(sleep_speed)
    pyglow.led(14, 20)
    sleep(sleep_speed)
    pyglow.led(15, 30)
    sleep(sleep_speed)
    pyglow.led(16, 40)
    sleep(sleep_speed)
    pyglow.led(17, 50)
    sleep(sleep_speed)
    pyglow.led(18, 60)
    sleep(sleep_speed)
    # Fade LED 13 - 18
    pyglow.led(13, 0)
    sleep(sleep_speed)
    pyglow.led(14, 10)
    sleep(sleep_speed)
    pyglow.led(15, 20)
    sleep(sleep_speed)
    pyglow.led(16, 30)
    sleep(sleep_speed)
    pyglow.led(17, 40)
    sleep(sleep_speed)
    pyglow.led(18, 50)
    sleep(sleep_speed)
    # Fade LED 14 - 18
    pyglow.led(14, 0)
    sleep(sleep_speed)
    pyglow.led(15, 10)
    sleep(sleep_speed)
    pyglow.led(16, 20)
    sleep(sleep_speed)
    pyglow.led(17, 30)
    sleep(sleep_speed)
    pyglow.led(18, 40)
    sleep(sleep_speed)
    # Fade LED 15 - 18
    pyglow.led(15, 0)
    sleep(sleep_speed)
    pyglow.led(16, 10)
    sleep(sleep_speed)
    pyglow.led(17, 20)
    sleep(sleep_speed)
    pyglow.led(18, 30)
    sleep(sleep_speed)
    # Fade LED 16 - 18
    pyglow.led(16, 0)
    sleep(sleep_speed)
    pyglow.led(17, 10)
    sleep(sleep_speed)
    pyglow.led(18, 20)
    sleep(sleep_speed)
    # Fade LED 17 and 18
    pyglow.led(17, 0)
    sleep(sleep_speed)
    pyglow.led(18, 10)
    sleep(sleep_speed)
    # Fade LED 118
    pyglow.led(18, 0)
    sleep(sleep_speed)

# Start the program   
try:
    while True:
        fading_spiral_arms()
        sleep(0.5)
# Stop the program and turn off LEDs with Ctrl-C
except KeyboardInterrupt:
    pyglow.all()
