################################################################
#                          Random Snakes                       #
################################################################
# Description:                                                 #
# This programs contains all the functions from my snake       #
# programs and runs them randomly.                             #
#                                                              #
# Requirements: PyGlow.py                                      #
#                                                              #
# Author: Paul Ryan                                            #
#                                                              #
################################################################

from PyGlow import PyGlow
from time import sleep
import random

pyglow = PyGlow()

# Initialize
pyglow.all(0)

# Lists
# Snake 12 LEDs 
snake_12_leds = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 18]
# Snake 13 LEDs 
snake_13_leds = [1, 2, 3, 4, 5, 12, 13, 14, 15, 16, 17, 18]
# Snake 23 LEDs 
snake_23_leds = [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

# Functions
def snake_12():
    pyglow.set_leds(snake_12_leds, 100)
    pyglow.update_leds()
    sleep(2)
    pyglow.set_leds(snake_12_leds, 0)
    pyglow.update_leds()
    sleep(1)

def snake_13():
    pyglow.set_leds(snake_13_leds, 100)
    pyglow.update_leds()
    sleep(2)
    pyglow.set_leds(snake_13_leds, 0)
    pyglow.update_leds()
    sleep(1)
    
def snake_23():
    pyglow.set_leds(snake_23_leds, 100)
    pyglow.update_leds()
    sleep(2)
    pyglow.set_leds(snake_23_leds, 0)
    pyglow.update_leds()
    sleep(1)

def fading_snake_12():
    pyglow.set_leds(snake_12_leds, 100)
    pyglow.update_leds()
    sleep(2)
    pyglow.set_leds(snake_12_leds, 90)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_12_leds, 80)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_12_leds, 70)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_12_leds, 60)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_12_leds, 50)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_12_leds, 40)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_12_leds, 30)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_12_leds, 20)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_12_leds, 10)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_12_leds, 0)
    pyglow.update_leds()
    sleep(1)

def fading_snake_13():
    pyglow.set_leds(snake_13_leds, 100)
    pyglow.update_leds()
    sleep(2)
    pyglow.set_leds(snake_13_leds, 90)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_13_leds, 80)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_13_leds, 70)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_13_leds, 60)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_13_leds, 50)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_13_leds, 40)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_13_leds, 30)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_13_leds, 20)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_13_leds, 10)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_13_leds, 0)
    pyglow.update_leds()
    sleep(1)
    
def fading_snake_23():
    pyglow.set_leds(snake_23_leds, 100)
    pyglow.update_leds()
    sleep(2)
    pyglow.set_leds(snake_23_leds, 90)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_23_leds, 80)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_23_leds, 70)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_23_leds, 60)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_23_leds, 50)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_23_leds, 40)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_23_leds, 30)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_23_leds, 20)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_23_leds, 10)
    pyglow.update_leds()
    sleep(0.1)
    pyglow.set_leds(snake_23_leds, 0)
    pyglow.update_leds()
    sleep(1)

def slithering_snake_12():
    # Set sleep speed
    sleep_speed = 0.10
    # Light up Snake 12 
    pyglow.led(1, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(7, 100)
    sleep(sleep_speed)
    # Turn off Snake 12 
    pyglow.led(1, 0)
    sleep(sleep_speed)
    pyglow.led(2, 0)
    sleep(sleep_speed)
    pyglow.led(3, 0)
    sleep(sleep_speed)
    pyglow.led(4, 0)
    sleep(sleep_speed)
    pyglow.led(5, 0)
    sleep(sleep_speed)
    pyglow.led(6, 0)
    sleep(sleep_speed)
    pyglow.led(18, 0)
    sleep(sleep_speed)
    pyglow.led(11, 0)
    sleep(sleep_speed)
    pyglow.led(10, 0)
    sleep(sleep_speed)
    pyglow.led(9, 0)
    sleep(sleep_speed)
    pyglow.led(8, 0)
    sleep(sleep_speed)
    pyglow.led(7, 0)
    sleep(1)

def slithering_snake_13():
    # Set sleep speed
    sleep_speed = 0.10
    # Light up Snake 13
    pyglow.led(1, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(13, 100)
    sleep(sleep_speed)
    # Turn off Snake 13 
    pyglow.led(1, 0)
    sleep(sleep_speed)
    pyglow.led(2, 0)
    sleep(sleep_speed)
    pyglow.led(3, 0)
    sleep(sleep_speed)
    pyglow.led(4, 0)
    sleep(sleep_speed)
    pyglow.led(5, 0)
    sleep(sleep_speed)
    pyglow.led(18, 0)
    sleep(sleep_speed)
    pyglow.led(12, 0)
    sleep(sleep_speed)
    pyglow.led(17, 0)
    sleep(sleep_speed)
    pyglow.led(16, 0)
    sleep(sleep_speed)
    pyglow.led(15, 0)
    sleep(sleep_speed)
    pyglow.led(14, 0)
    sleep(sleep_speed)
    pyglow.led(13, 0)
    sleep(1)

def slithering_snake_21():
    # Set sleep speed
    sleep_speed = 0.10
    # Light up Snake 21
    pyglow.led(7, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(1, 100)
    sleep(sleep_speed)
    # Turn off Snake 21
    pyglow.led(7, 0)
    sleep(sleep_speed)
    pyglow.led(8, 0)
    sleep(sleep_speed)
    pyglow.led(9, 0)
    sleep(sleep_speed)
    pyglow.led(10, 0)
    sleep(sleep_speed)
    pyglow.led(11, 0)
    sleep(sleep_speed)
    pyglow.led(18, 0)
    sleep(sleep_speed)
    pyglow.led(6, 0)
    sleep(sleep_speed)
    pyglow.led(5, 0)
    sleep(sleep_speed)
    pyglow.led(4, 0)
    sleep(sleep_speed)
    pyglow.led(3, 0)
    sleep(sleep_speed)
    pyglow.led(2, 0)
    sleep(sleep_speed)
    pyglow.led(1, 0)
    sleep(1)

def slithering_snake_23():
    # Set sleep speed
    sleep_speed = 0.10
    # Light up Snake 23
    pyglow.led(7, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(13, 100)
    sleep(sleep_speed)
    # Turn off Snake 23 
    pyglow.led(7, 0)
    sleep(sleep_speed)
    pyglow.led(8, 0)
    sleep(sleep_speed)
    pyglow.led(9, 0)
    sleep(sleep_speed)
    pyglow.led(10, 0)
    sleep(sleep_speed)
    pyglow.led(11, 0)
    sleep(sleep_speed)
    pyglow.led(12, 0)
    sleep(sleep_speed)
    pyglow.led(6, 0)
    sleep(sleep_speed)
    pyglow.led(17, 0)
    sleep(sleep_speed)
    pyglow.led(16, 0)
    sleep(sleep_speed)
    pyglow.led(15, 0)
    sleep(sleep_speed)
    pyglow.led(14, 0)
    sleep(sleep_speed)
    pyglow.led(13, 0)
    sleep(1)

def slithering_snake_31():
    # Set sleep speed
    sleep_speed = 0.10
    # Light up Snake 31
    pyglow.led(13, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(1, 100)
    sleep(sleep_speed)
    # Turn off Snake 31
    pyglow.led(13, 0)
    sleep(sleep_speed)
    pyglow.led(14, 0)
    sleep(sleep_speed)
    pyglow.led(15, 0)
    sleep(sleep_speed)
    pyglow.led(16, 0)
    sleep(sleep_speed)
    pyglow.led(17, 0)
    sleep(sleep_speed)
    pyglow.led(18, 0)
    sleep(sleep_speed)
    pyglow.led(12, 0)
    sleep(sleep_speed)
    pyglow.led(5, 0)
    sleep(sleep_speed)
    pyglow.led(4, 0)
    sleep(sleep_speed)
    pyglow.led(3, 0)
    sleep(sleep_speed)
    pyglow.led(2, 0)
    sleep(sleep_speed)
    pyglow.led(1, 0)
    sleep(1)

def slithering_snake_32():
    # Set sleep speed
    sleep_speed = 0.10
    # Light up Snake 32 
    pyglow.led(13, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(7, 100)
    sleep(sleep_speed)
    # Turn off Snake 32 
    pyglow.led(13, 0)
    sleep(sleep_speed)
    pyglow.led(14, 0)
    sleep(sleep_speed)
    pyglow.led(15, 0)
    sleep(sleep_speed)
    pyglow.led(16, 0)
    sleep(sleep_speed)
    pyglow.led(17, 0)
    sleep(sleep_speed)
    pyglow.led(6, 0)
    sleep(sleep_speed)
    pyglow.led(12, 0)
    sleep(sleep_speed)
    pyglow.led(11, 0)
    sleep(sleep_speed)
    pyglow.led(10, 0)
    sleep(sleep_speed)
    pyglow.led(9, 0)
    sleep(sleep_speed)
    pyglow.led(8, 0)
    sleep(sleep_speed)
    pyglow.led(7, 0)
    sleep(1)

def slithering_fading_snake_12():
    # Set sleep speed
    sleep_speed = 0.01
    # Turn on Snake Head 
    pyglow.led(1, 120)
    sleep(sleep_speed)
    # Turn on Snake Body 1
    pyglow.led(2, 120)
    sleep(sleep_speed)
    # Fade Head
    pyglow.led(1, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 2
    pyglow.led(3, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1
    pyglow.led(1, 100)
    sleep(sleep_speed)
    pyglow.led(2, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 3
    pyglow.led(4, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 2
    pyglow.led(1, 90)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(3, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 4
    pyglow.led(5, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 3
    pyglow.led(1, 80)
    sleep(sleep_speed)
    pyglow.led(2, 90)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(4, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 5
    pyglow.led(6, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 4
    pyglow.led(1, 70)
    sleep(sleep_speed)
    pyglow.led(2, 80)
    sleep(sleep_speed)
    pyglow.led(3, 90)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(5, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 6
    pyglow.led(18, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 5
    pyglow.led(1, 60)
    sleep(sleep_speed)
    pyglow.led(2, 70)
    sleep(sleep_speed)
    pyglow.led(3, 80)
    sleep(sleep_speed)
    pyglow.led(4, 90)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(6, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 7
    pyglow.led(11, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 6
    pyglow.led(1, 50)
    sleep(sleep_speed)
    pyglow.led(2, 60)
    sleep(sleep_speed)
    pyglow.led(3, 70)
    sleep(sleep_speed)
    pyglow.led(4, 80)
    sleep(sleep_speed)
    pyglow.led(5, 90)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(18, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 8
    pyglow.led(10, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 7
    pyglow.led(1, 40)
    sleep(sleep_speed)
    pyglow.led(2, 50)
    sleep(sleep_speed)
    pyglow.led(3, 60)
    sleep(sleep_speed)
    pyglow.led(4, 70)
    sleep(sleep_speed)
    pyglow.led(5, 80)
    sleep(sleep_speed)
    pyglow.led(6, 90)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(11, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 9
    pyglow.led(9, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 8
    pyglow.led(1, 30)
    sleep(sleep_speed)
    pyglow.led(2, 40)
    sleep(sleep_speed)
    pyglow.led(3, 50)
    sleep(sleep_speed)
    pyglow.led(4, 60)
    sleep(sleep_speed)
    pyglow.led(5, 70)
    sleep(sleep_speed)
    pyglow.led(6, 80)
    sleep(sleep_speed)
    pyglow.led(18, 90)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(10, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 10
    pyglow.led(8, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 9
    pyglow.led(1, 20)
    sleep(sleep_speed)
    pyglow.led(2, 30)
    sleep(sleep_speed)
    pyglow.led(3, 40)
    sleep(sleep_speed)
    pyglow.led(4, 50)
    sleep(sleep_speed)
    pyglow.led(5, 60)
    sleep(sleep_speed)
    pyglow.led(6, 70)
    sleep(sleep_speed)
    pyglow.led(18, 80)
    sleep(sleep_speed)
    pyglow.led(11, 90)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(9, 110)
    sleep(sleep_speed)
    # Turn on Snake Tail
    pyglow.led(7, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 10
    pyglow.led(1, 10)
    sleep(sleep_speed)
    pyglow.led(2, 20)
    sleep(sleep_speed)
    pyglow.led(3, 30)
    sleep(sleep_speed)
    pyglow.led(4, 40)
    sleep(sleep_speed)
    pyglow.led(5, 50)
    sleep(sleep_speed)
    pyglow.led(6, 60)
    sleep(sleep_speed)
    pyglow.led(18, 70)
    sleep(sleep_speed)
    pyglow.led(11, 80)
    sleep(sleep_speed)
    pyglow.led(10, 90)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(8, 110)
    sleep(sleep_speed)
    # Fade Head, Body 1 - 10, and Tail
    pyglow.led(1, 0)
    sleep(sleep_speed)
    pyglow.led(2, 10)
    sleep(sleep_speed)
    pyglow.led(3, 20)
    sleep(sleep_speed)
    pyglow.led(4, 30)
    sleep(sleep_speed)
    pyglow.led(5, 40)
    sleep(sleep_speed)
    pyglow.led(6, 50)
    sleep(sleep_speed)
    pyglow.led(18, 60)
    sleep(sleep_speed)
    pyglow.led(11, 70)
    sleep(sleep_speed)
    pyglow.led(10, 80)
    sleep(sleep_speed)
    pyglow.led(9, 90)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(7, 110)
    sleep(sleep_speed)
    # Fade Body 1 - 10 and Tail
    pyglow.led(2, 0)
    sleep(sleep_speed)
    pyglow.led(3, 10)
    sleep(sleep_speed)
    pyglow.led(4, 20)
    sleep(sleep_speed)
    pyglow.led(5, 30)
    sleep(sleep_speed)
    pyglow.led(6, 40)
    sleep(sleep_speed)
    pyglow.led(18, 50)
    sleep(sleep_speed)
    pyglow.led(11, 60)
    sleep(sleep_speed)
    pyglow.led(10, 70)
    sleep(sleep_speed)
    pyglow.led(9, 80)
    sleep(sleep_speed)
    pyglow.led(8, 90)
    sleep(sleep_speed)
    pyglow.led(7, 100)
    sleep(sleep_speed)
    # Fade Body 2 - 10 and Tail
    pyglow.led(3, 0)
    sleep(sleep_speed)
    pyglow.led(4, 10)
    sleep(sleep_speed)
    pyglow.led(5, 20)
    sleep(sleep_speed)
    pyglow.led(6, 30)
    sleep(sleep_speed)
    pyglow.led(18, 40)
    sleep(sleep_speed)
    pyglow.led(11, 50)
    sleep(sleep_speed)
    pyglow.led(10, 60)
    sleep(sleep_speed)
    pyglow.led(9, 70)
    sleep(sleep_speed)
    pyglow.led(8, 80)
    sleep(sleep_speed)
    pyglow.led(7, 90)
    sleep(sleep_speed)
    # Fade Body 3 - 10 and Tail
    pyglow.led(4, 0)
    sleep(sleep_speed)
    pyglow.led(5, 10)
    sleep(sleep_speed)
    pyglow.led(6, 20)
    sleep(sleep_speed)
    pyglow.led(18, 30)
    sleep(sleep_speed)
    pyglow.led(11, 40)
    sleep(sleep_speed)
    pyglow.led(10, 50)
    sleep(sleep_speed)
    pyglow.led(9, 60)
    sleep(sleep_speed)
    pyglow.led(8, 70)
    sleep(sleep_speed)
    pyglow.led(7, 80)
    sleep(sleep_speed)
    # Fade Body 4 - 10 and Tail
    pyglow.led(5, 0)
    sleep(sleep_speed)
    pyglow.led(6, 10)
    sleep(sleep_speed)
    pyglow.led(18, 20)
    sleep(sleep_speed)
    pyglow.led(11, 30)
    sleep(sleep_speed)
    pyglow.led(10, 40)
    sleep(sleep_speed)
    pyglow.led(9, 50)
    sleep(sleep_speed)
    pyglow.led(8, 60)
    sleep(sleep_speed)
    pyglow.led(7, 70)
    sleep(sleep_speed)
    # Fade Body 5 - 10 and Tail
    pyglow.led(6, 0)
    sleep(sleep_speed)
    pyglow.led(18, 10)
    sleep(sleep_speed)
    pyglow.led(11, 20)
    sleep(sleep_speed)
    pyglow.led(10, 30)
    sleep(sleep_speed)
    pyglow.led(9, 40)
    sleep(sleep_speed)
    pyglow.led(8, 50)
    sleep(sleep_speed)
    pyglow.led(7, 60)
    sleep(sleep_speed)
    # Fade Body 6 - 10 and Tail
    pyglow.led(18, 0)
    sleep(sleep_speed)
    pyglow.led(11, 10)
    sleep(sleep_speed)
    pyglow.led(10, 20)
    sleep(sleep_speed)
    pyglow.led(9, 30)
    sleep(sleep_speed)
    pyglow.led(8, 40)
    sleep(sleep_speed)
    pyglow.led(7, 50)
    sleep(sleep_speed)
    # Fade Body 7 - 10 and Tail
    pyglow.led(11, 0)
    sleep(sleep_speed)
    pyglow.led(10, 10)
    sleep(sleep_speed)
    pyglow.led(9, 20)
    sleep(sleep_speed)
    pyglow.led(8, 30)
    sleep(sleep_speed)
    pyglow.led(7, 40)
    sleep(sleep_speed)
    # Fade Body 8 - 10 and Tail
    pyglow.led(10, 0)
    sleep(sleep_speed)
    pyglow.led(9, 10)
    sleep(sleep_speed)
    pyglow.led(8, 20)
    sleep(sleep_speed)
    pyglow.led(7, 30)
    sleep(sleep_speed)
    # Fade Body 9 - 10 and Tail
    pyglow.led(9, 0)
    sleep(sleep_speed)
    pyglow.led(8, 10)
    sleep(sleep_speed)
    pyglow.led(7, 20)
    sleep(sleep_speed)
    # Fade Body 10 and Tail
    pyglow.led(8, 0)
    sleep(sleep_speed)
    pyglow.led(7, 10)
    sleep(sleep_speed)
    # Fade Tail
    pyglow.led(7, 0)
    sleep(sleep_speed)
    # Pause before next snake function
    sleep(1)

def slithering_fading_snake_13():
    # Set sleep speed
    sleep_speed = 0.01
    # Turn on Snake Head
    pyglow.led(1, 120)
    sleep(sleep_speed)
    # Turn on Snake Body 1
    pyglow.led(2, 120)
    sleep(sleep_speed)
    # Fade Head
    pyglow.led(1, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 2
    pyglow.led(3, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1
    pyglow.led(1, 100)
    sleep(sleep_speed)
    pyglow.led(2, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 3
    pyglow.led(4, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 2
    pyglow.led(1, 90)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(3, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 4
    pyglow.led(5, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 3
    pyglow.led(1, 80)
    sleep(sleep_speed)
    pyglow.led(2, 90)
    sleep(sleep_speed)
    pyglow.led(3, 80)
    sleep(sleep_speed)
    pyglow.led(4, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 5
    pyglow.led(18, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 4
    pyglow.led(1, 70)
    sleep(sleep_speed)
    pyglow.led(2, 80)
    sleep(sleep_speed)
    pyglow.led(3, 90)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(5, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 6
    pyglow.led(12, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 5
    pyglow.led(1, 60)
    sleep(sleep_speed)
    pyglow.led(2, 70)
    sleep(sleep_speed)
    pyglow.led(3, 80)
    sleep(sleep_speed)
    pyglow.led(4, 90)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(18, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 7
    pyglow.led(17, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 6
    pyglow.led(1, 50)
    sleep(sleep_speed)
    pyglow.led(2, 60)
    sleep(sleep_speed)
    pyglow.led(3, 70)
    sleep(sleep_speed)
    pyglow.led(4, 80)
    sleep(sleep_speed)
    pyglow.led(5, 90)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(12, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 8
    pyglow.led(16, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 7
    pyglow.led(1, 40)
    sleep(sleep_speed)
    pyglow.led(2, 50)
    sleep(sleep_speed)
    pyglow.led(3, 60)
    sleep(sleep_speed)
    pyglow.led(4, 70)
    sleep(sleep_speed)
    pyglow.led(5, 80)
    sleep(sleep_speed)
    pyglow.led(18, 90)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(17, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 9
    pyglow.led(15, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 8
    pyglow.led(1, 30)
    sleep(sleep_speed)
    pyglow.led(2, 40)
    sleep(sleep_speed)
    pyglow.led(3, 50)
    sleep(sleep_speed)
    pyglow.led(4, 60)
    sleep(sleep_speed)
    pyglow.led(5, 70)
    sleep(sleep_speed)
    pyglow.led(18, 80)
    sleep(sleep_speed)
    pyglow.led(12, 90)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(16, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 10
    pyglow.led(14, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 9
    pyglow.led(1, 20)
    sleep(sleep_speed)
    pyglow.led(2, 30)
    sleep(sleep_speed)
    pyglow.led(3, 40)
    sleep(sleep_speed)
    pyglow.led(4, 50)
    sleep(sleep_speed)
    pyglow.led(5, 60)
    sleep(sleep_speed)
    pyglow.led(18, 70)
    sleep(sleep_speed)
    pyglow.led(12, 80)
    sleep(sleep_speed)
    pyglow.led(17, 90)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(15, 110)
    sleep(sleep_speed)
    # Turn on Snake Tail
    pyglow.led(13, 120)
    sleep(sleep_speed)
    # Fade Head, Body 1 - 10
    pyglow.led(1, 10)
    sleep(sleep_speed)
    pyglow.led(2, 20)
    sleep(sleep_speed)
    pyglow.led(3, 30)
    sleep(sleep_speed)
    pyglow.led(4, 40)
    sleep(sleep_speed)
    pyglow.led(5, 50)
    sleep(sleep_speed)
    pyglow.led(18, 60)
    sleep(sleep_speed)
    pyglow.led(12, 70)
    sleep(sleep_speed)
    pyglow.led(17, 80)
    sleep(sleep_speed)
    pyglow.led(16, 90)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(14, 110)
    sleep(sleep_speed)
    # Fade Head, Body 1 - 10, Tail
    pyglow.led(1, 0)
    sleep(sleep_speed)
    pyglow.led(2, 10)
    sleep(sleep_speed)
    pyglow.led(3, 20)
    sleep(sleep_speed)
    pyglow.led(4, 30)
    sleep(sleep_speed)
    pyglow.led(5, 40)
    sleep(sleep_speed)
    pyglow.led(18, 50)
    sleep(sleep_speed)
    pyglow.led(12, 60)
    sleep(sleep_speed)
    pyglow.led(17, 70)
    sleep(sleep_speed)
    pyglow.led(16, 80)
    sleep(sleep_speed)
    pyglow.led(15, 90)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(13, 110)
    sleep(sleep_speed)
    # Fade Body 1 - 10, Tail
    pyglow.led(2, 0)
    sleep(sleep_speed)
    pyglow.led(3, 10)
    sleep(sleep_speed)
    pyglow.led(4, 20)
    sleep(sleep_speed)
    pyglow.led(5, 30)
    sleep(sleep_speed)
    pyglow.led(18, 40)
    sleep(sleep_speed)
    pyglow.led(12, 50)
    sleep(sleep_speed)
    pyglow.led(17, 60)
    sleep(sleep_speed)
    pyglow.led(16, 70)
    sleep(sleep_speed)
    pyglow.led(15, 80)
    sleep(sleep_speed)
    pyglow.led(14, 90)
    sleep(sleep_speed)
    pyglow.led(13, 100)
    sleep(sleep_speed)
    # Fade Body 2 - 10, Tail
    pyglow.led(3, 0)
    sleep(sleep_speed)
    pyglow.led(4, 10)
    sleep(sleep_speed)
    pyglow.led(5, 20)
    sleep(sleep_speed)
    pyglow.led(18, 30)
    sleep(sleep_speed)
    pyglow.led(12, 40)
    sleep(sleep_speed)
    pyglow.led(17, 50)
    sleep(sleep_speed)
    pyglow.led(16, 60)
    sleep(sleep_speed)
    pyglow.led(15, 70)
    sleep(sleep_speed)
    pyglow.led(14, 80)
    sleep(sleep_speed)
    pyglow.led(13, 90)
    sleep(sleep_speed)
    # Fade Body 3 - 10, Tail
    pyglow.led(4, 0)
    sleep(sleep_speed)
    pyglow.led(5, 10)
    sleep(sleep_speed)
    pyglow.led(18, 20)
    sleep(sleep_speed)
    pyglow.led(12, 30)
    sleep(sleep_speed)
    pyglow.led(17, 40)
    sleep(sleep_speed)
    pyglow.led(16, 50)
    sleep(sleep_speed)
    pyglow.led(15, 60)
    sleep(sleep_speed)
    pyglow.led(14, 70)
    sleep(sleep_speed)
    pyglow.led(13, 80)
    sleep(sleep_speed)
    # Fade Body 4 - 10, Tail
    pyglow.led(5, 0)
    sleep(sleep_speed)
    pyglow.led(18, 10)
    sleep(sleep_speed)
    pyglow.led(12, 20)
    sleep(sleep_speed)
    pyglow.led(17, 30)
    sleep(sleep_speed)
    pyglow.led(16, 40)
    sleep(sleep_speed)
    pyglow.led(15, 50)
    sleep(sleep_speed)
    pyglow.led(14, 60)
    sleep(sleep_speed)
    pyglow.led(13, 70)
    sleep(sleep_speed)
    # Fade Body 5 - 10, Tail
    pyglow.led(18, 0)
    sleep(sleep_speed)
    pyglow.led(12, 10)
    sleep(sleep_speed)
    pyglow.led(17, 20)
    sleep(sleep_speed)
    pyglow.led(16, 30)
    sleep(sleep_speed)
    pyglow.led(15, 40)
    sleep(sleep_speed)
    pyglow.led(14, 50)
    sleep(sleep_speed)
    pyglow.led(13, 60)
    sleep(sleep_speed)
    # Fade Body 6 - 10, Tail
    pyglow.led(12, 0)
    sleep(sleep_speed)
    pyglow.led(17, 10)
    sleep(sleep_speed)
    pyglow.led(16, 20)
    sleep(sleep_speed)
    pyglow.led(15, 30)
    sleep(sleep_speed)
    pyglow.led(14, 40)
    sleep(sleep_speed)
    pyglow.led(13, 50)
    sleep(sleep_speed)
    # Fade Body 7 - 10, Tail
    pyglow.led(17, 0)
    sleep(sleep_speed)
    pyglow.led(16, 10)
    sleep(sleep_speed)
    pyglow.led(15, 20)
    sleep(sleep_speed)
    pyglow.led(14, 30)
    sleep(sleep_speed)
    pyglow.led(13, 40)
    sleep(sleep_speed)
    # Fade Body 8 - 10, Tail
    pyglow.led(16, 0)
    sleep(sleep_speed)
    pyglow.led(15, 10)
    sleep(sleep_speed)
    pyglow.led(14, 20)
    sleep(sleep_speed)
    pyglow.led(13, 30)
    sleep(sleep_speed)
    # Fade Body 9 - 10, Tail
    pyglow.led(15, 0)
    sleep(sleep_speed)
    pyglow.led(14, 10)
    sleep(sleep_speed)
    pyglow.led(13, 20)
    sleep(sleep_speed)
    # Fade Body 10 and  Tail
    pyglow.led(14, 0)
    sleep(sleep_speed)
    pyglow.led(13, 10)
    sleep(sleep_speed)
    # Fade Tail
    pyglow.led(13, 0)
    sleep(sleep_speed)
    # Pause before next snake function
    sleep(1)
    
def slithering_fading_snake_21():
    # Set sleep speed
    sleep_speed = 0.01
    # Turn on Snake Head
    pyglow.led(7, 120)
    sleep(sleep_speed)
    # Turn on Snake Body 1
    pyglow.led(8, 120)
    sleep(sleep_speed)
    # Fade Head
    pyglow.led(7, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 2
    pyglow.led(9, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1
    pyglow.led(7, 100)
    sleep(sleep_speed)
    pyglow.led(8, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 3
    pyglow.led(10, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 2
    pyglow.led(7, 90)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(9, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 4
    pyglow.led(11, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 3
    pyglow.led(7, 80)
    sleep(sleep_speed)
    pyglow.led(8, 90)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(10, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 5
    pyglow.led(18, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 4
    pyglow.led(7, 70)
    sleep(sleep_speed)
    pyglow.led(8, 80)
    sleep(sleep_speed)
    pyglow.led(9, 90)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(11, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 6
    pyglow.led(6, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 5
    pyglow.led(7, 60)
    sleep(sleep_speed)
    pyglow.led(8, 70)
    sleep(sleep_speed)
    pyglow.led(9, 80)
    sleep(sleep_speed)
    pyglow.led(10, 90)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(18, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 7
    pyglow.led(5, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 6
    pyglow.led(7, 50)
    sleep(sleep_speed)
    pyglow.led(8, 60)
    sleep(sleep_speed)
    pyglow.led(9, 70)
    sleep(sleep_speed)
    pyglow.led(10, 80)
    sleep(sleep_speed)
    pyglow.led(11, 90)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(6, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 8
    pyglow.led(4, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 7
    pyglow.led(7, 40)
    sleep(sleep_speed)
    pyglow.led(8, 50)
    sleep(sleep_speed)
    pyglow.led(9, 60)
    sleep(sleep_speed)
    pyglow.led(10, 70)
    sleep(sleep_speed)
    pyglow.led(11, 80)
    sleep(sleep_speed)
    pyglow.led(18, 90)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(5, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 9
    pyglow.led(3, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 8
    pyglow.led(7, 30)
    sleep(sleep_speed)
    pyglow.led(8, 40)
    sleep(sleep_speed)
    pyglow.led(9, 50)
    sleep(sleep_speed)
    pyglow.led(10, 60)
    sleep(sleep_speed)
    pyglow.led(11, 70)
    sleep(sleep_speed)
    pyglow.led(18, 80)
    sleep(sleep_speed)
    pyglow.led(6, 90)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(4, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 10
    pyglow.led(2, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 9
    pyglow.led(7, 20)
    sleep(sleep_speed)
    pyglow.led(8, 30)
    sleep(sleep_speed)
    pyglow.led(9, 40)
    sleep(sleep_speed)
    pyglow.led(10, 50)
    sleep(sleep_speed)
    pyglow.led(11, 60)
    sleep(sleep_speed)
    pyglow.led(18, 70)
    sleep(sleep_speed)
    pyglow.led(6, 80)
    sleep(sleep_speed)
    pyglow.led(5, 90)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(3, 110)
    sleep(sleep_speed)
    # Turn on Snake Tail
    pyglow.led(1, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 10
    pyglow.led(7, 10)
    sleep(sleep_speed)
    pyglow.led(8, 20)
    sleep(sleep_speed)
    pyglow.led(9, 30)
    sleep(sleep_speed)
    pyglow.led(10, 40)
    sleep(sleep_speed)
    pyglow.led(11, 50)
    sleep(sleep_speed)
    pyglow.led(18, 60)
    sleep(sleep_speed)
    pyglow.led(6, 70)
    sleep(sleep_speed)
    pyglow.led(5, 80)
    sleep(sleep_speed)
    pyglow.led(4, 90)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(2, 110)
    sleep(sleep_speed)
    # Fade Head, Body 1 - 10, and Tail
    pyglow.led(7, 0)
    sleep(sleep_speed)
    pyglow.led(8, 10)
    sleep(sleep_speed)
    pyglow.led(9, 20)
    sleep(sleep_speed)
    pyglow.led(10, 30)
    sleep(sleep_speed)
    pyglow.led(11, 40)
    sleep(sleep_speed)
    pyglow.led(18, 50)
    sleep(sleep_speed)
    pyglow.led(6, 60)
    sleep(sleep_speed)
    pyglow.led(5, 70)
    sleep(sleep_speed)
    pyglow.led(4, 80)
    sleep(sleep_speed)
    pyglow.led(3, 90)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(1, 110)
    sleep(sleep_speed)
    # Fade Body 1 - 10 and Tail
    pyglow.led(8, 0)
    sleep(sleep_speed)
    pyglow.led(9, 10)
    sleep(sleep_speed)
    pyglow.led(10, 20)
    sleep(sleep_speed)
    pyglow.led(11, 30)
    sleep(sleep_speed)
    pyglow.led(18, 40)
    sleep(sleep_speed)
    pyglow.led(6, 50)
    sleep(sleep_speed)
    pyglow.led(5, 60)
    sleep(sleep_speed)
    pyglow.led(4, 70)
    sleep(sleep_speed)
    pyglow.led(3, 80)
    sleep(sleep_speed)
    pyglow.led(2, 90)
    sleep(sleep_speed)
    pyglow.led(1, 100)
    sleep(sleep_speed)
    # Fade Body 2 - 10 and Tail
    pyglow.led(9, 0)
    sleep(sleep_speed)
    pyglow.led(10, 10)
    sleep(sleep_speed)
    pyglow.led(11, 20)
    sleep(sleep_speed)
    pyglow.led(18, 30)
    sleep(sleep_speed)
    pyglow.led(6, 40)
    sleep(sleep_speed)
    pyglow.led(5, 50)
    sleep(sleep_speed)
    pyglow.led(4, 60)
    sleep(sleep_speed)
    pyglow.led(3, 70)
    sleep(sleep_speed)
    pyglow.led(2, 80)
    sleep(sleep_speed)
    pyglow.led(1, 90)
    sleep(sleep_speed)
    # Fade Body 3 - 10 and Tail
    pyglow.led(10, 0)
    sleep(sleep_speed)
    pyglow.led(11, 10)
    sleep(sleep_speed)
    pyglow.led(18, 20)
    sleep(sleep_speed)
    pyglow.led(6, 30)
    sleep(sleep_speed)
    pyglow.led(5, 40)
    sleep(sleep_speed)
    pyglow.led(4, 50)
    sleep(sleep_speed)
    pyglow.led(3, 60)
    sleep(sleep_speed)
    pyglow.led(2, 70)
    sleep(sleep_speed)
    pyglow.led(1, 80)
    sleep(sleep_speed)
    # Fade Body 4 - 10 and Tail
    pyglow.led(11, 0)
    sleep(sleep_speed)
    pyglow.led(18, 10)
    sleep(sleep_speed)
    pyglow.led(6, 20)
    sleep(sleep_speed)
    pyglow.led(5, 30)
    sleep(sleep_speed)
    pyglow.led(4, 40)
    sleep(sleep_speed)
    pyglow.led(3, 50)
    sleep(sleep_speed)
    pyglow.led(2, 60)
    sleep(sleep_speed)
    pyglow.led(1, 70)
    sleep(sleep_speed)
    # Fade Body 5 - 10 and Tail
    pyglow.led(18, 0)
    sleep(sleep_speed)
    pyglow.led(6, 10)
    sleep(sleep_speed)
    pyglow.led(5, 20)
    sleep(sleep_speed)
    pyglow.led(4, 30)
    sleep(sleep_speed)
    pyglow.led(3, 40)
    sleep(sleep_speed)
    pyglow.led(2, 50)
    sleep(sleep_speed)
    pyglow.led(1, 60)
    sleep(sleep_speed)
    # Fade Body 6 - 10 and Tail
    pyglow.led(6, 0)
    sleep(sleep_speed)
    pyglow.led(5, 10)
    sleep(sleep_speed)
    pyglow.led(4, 20)
    sleep(sleep_speed)
    pyglow.led(3, 30)
    sleep(sleep_speed)
    pyglow.led(2, 40)
    sleep(sleep_speed)
    pyglow.led(1, 50)
    sleep(sleep_speed)
    # Fade Body 7 - 10 and Tail
    pyglow.led(5, 0)
    sleep(sleep_speed)
    pyglow.led(4, 10)
    sleep(sleep_speed)
    pyglow.led(3, 20)
    sleep(sleep_speed)
    pyglow.led(2, 30)
    sleep(sleep_speed)
    pyglow.led(1, 40)
    sleep(sleep_speed)
    # Fade Body 8 - 10 and Tail
    pyglow.led(4, 0)
    sleep(sleep_speed)
    pyglow.led(3, 10)
    sleep(sleep_speed)
    pyglow.led(2, 20)
    sleep(sleep_speed)
    pyglow.led(1, 30)
    sleep(sleep_speed)
    # Fade Body 9 - 10 and Tail
    pyglow.led(3, 0)
    sleep(sleep_speed)
    pyglow.led(2, 10)
    sleep(sleep_speed)
    pyglow.led(1, 20)
    sleep(sleep_speed)
    # Fade Body 10 and Tail
    pyglow.led(2, 0)
    sleep(sleep_speed)
    pyglow.led(1, 10)
    sleep(sleep_speed)
    # Fade Tail
    pyglow.led(1, 0)
    sleep(sleep_speed)
    # Pause before next snake function
    sleep(1)

def slithering_fading_snake_23():
    # Set sleep speed
    sleep_speed = 0.01
    # Turn on Snake Head
    pyglow.led(7, 120)
    sleep(sleep_speed)
    # Turn on Snake Body 1
    pyglow.led(8, 120)
    sleep(sleep_speed)
    # Fade Head
    pyglow.led(7, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 2
    pyglow.led(9, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1
    pyglow.led(7, 100)
    sleep(sleep_speed)
    pyglow.led(8, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 3
    pyglow.led(10, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 2
    pyglow.led(7, 90)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(9, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 4
    pyglow.led(11, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 3
    pyglow.led(7, 80)
    sleep(sleep_speed)
    pyglow.led(8, 90)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(10, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 5
    pyglow.led(12, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 4
    pyglow.led(7, 70)
    sleep(sleep_speed)
    pyglow.led(8, 80)
    sleep(sleep_speed)
    pyglow.led(9, 90)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(11, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 6
    pyglow.led(6, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 5
    pyglow.led(7, 60)
    sleep(sleep_speed)
    pyglow.led(8, 70)
    sleep(sleep_speed)
    pyglow.led(9, 80)
    sleep(sleep_speed)
    pyglow.led(10, 90)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(12, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 7
    pyglow.led(17, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 6
    pyglow.led(7, 50)
    sleep(sleep_speed)
    pyglow.led(8, 60)
    sleep(sleep_speed)
    pyglow.led(9, 70)
    sleep(sleep_speed)
    pyglow.led(10, 80)
    sleep(sleep_speed)
    pyglow.led(11, 90)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(6, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 8
    pyglow.led(16, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 7
    pyglow.led(7, 40)
    sleep(sleep_speed)
    pyglow.led(8, 50)
    sleep(sleep_speed)
    pyglow.led(9, 60)
    sleep(sleep_speed)
    pyglow.led(10, 70)
    sleep(sleep_speed)
    pyglow.led(11, 80)
    sleep(sleep_speed)
    pyglow.led(12, 90)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(17, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 9
    pyglow.led(15, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 8
    pyglow.led(7, 30)
    sleep(sleep_speed)
    pyglow.led(8, 40)
    sleep(sleep_speed)
    pyglow.led(9, 50)
    sleep(sleep_speed)
    pyglow.led(10, 60)
    sleep(sleep_speed)
    pyglow.led(11, 70)
    sleep(sleep_speed)
    pyglow.led(12, 80)
    sleep(sleep_speed)
    pyglow.led(6, 90)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(16, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 10
    pyglow.led(14, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 9
    pyglow.led(7, 20)
    sleep(sleep_speed)
    pyglow.led(8, 30)
    sleep(sleep_speed)
    pyglow.led(9, 40)
    sleep(sleep_speed)
    pyglow.led(10, 50)
    sleep(sleep_speed)
    pyglow.led(11, 60)
    sleep(sleep_speed)
    pyglow.led(12, 70)
    sleep(sleep_speed)
    pyglow.led(6, 80)
    sleep(sleep_speed)
    pyglow.led(17, 90)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(15, 110)
    sleep(sleep_speed)
    # Turn on Snake Tail
    pyglow.led(13, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 10
    pyglow.led(7, 10)
    sleep(sleep_speed)
    pyglow.led(8, 20)
    sleep(sleep_speed)
    pyglow.led(9, 30)
    sleep(sleep_speed)
    pyglow.led(10, 40)
    sleep(sleep_speed)
    pyglow.led(11, 50)
    sleep(sleep_speed)
    pyglow.led(12, 60)
    sleep(sleep_speed)
    pyglow.led(6, 70)
    sleep(sleep_speed)
    pyglow.led(17, 80)
    sleep(sleep_speed)
    pyglow.led(16, 90)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(14, 110)
    sleep(sleep_speed)
    # Fade Head, Body 1 - 10, and Tail
    pyglow.led(7, 0)
    sleep(sleep_speed)
    pyglow.led(8, 10)
    sleep(sleep_speed)
    pyglow.led(9, 20)
    sleep(sleep_speed)
    pyglow.led(10, 30)
    sleep(sleep_speed)
    pyglow.led(11, 40)
    sleep(sleep_speed)
    pyglow.led(12, 50)
    sleep(sleep_speed)
    pyglow.led(6, 60)
    sleep(sleep_speed)
    pyglow.led(17, 70)
    sleep(sleep_speed)
    pyglow.led(16, 80)
    sleep(sleep_speed)
    pyglow.led(15, 90)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(13, 110)
    sleep(sleep_speed)
    # Fade Body 1 - 10 and Tail
    pyglow.led(8, 0)
    sleep(sleep_speed)
    pyglow.led(9, 10)
    sleep(sleep_speed)
    pyglow.led(10, 20)
    sleep(sleep_speed)
    pyglow.led(11, 30)
    sleep(sleep_speed)
    pyglow.led(12, 40)
    sleep(sleep_speed)
    pyglow.led(6, 50)
    sleep(sleep_speed)
    pyglow.led(17, 60)
    sleep(sleep_speed)
    pyglow.led(16, 70)
    sleep(sleep_speed)
    pyglow.led(15, 80)
    sleep(sleep_speed)
    pyglow.led(14, 90)
    sleep(sleep_speed)
    pyglow.led(13, 100)
    sleep(sleep_speed)
    # Fade Body 2 - 10 and Tail
    pyglow.led(9, 0)
    sleep(sleep_speed)
    pyglow.led(10, 10)
    sleep(sleep_speed)
    pyglow.led(11, 20)
    sleep(sleep_speed)
    pyglow.led(12, 30)
    sleep(sleep_speed)
    pyglow.led(6, 40)
    sleep(sleep_speed)
    pyglow.led(17, 50)
    sleep(sleep_speed)
    pyglow.led(16, 60)
    sleep(sleep_speed)
    pyglow.led(15, 70)
    sleep(sleep_speed)
    pyglow.led(14, 80)
    sleep(sleep_speed)
    pyglow.led(13, 90)
    sleep(sleep_speed)
    # Fade Body 3 - 10 and Tail
    pyglow.led(10, 0)
    sleep(sleep_speed)
    pyglow.led(11, 10)
    sleep(sleep_speed)
    pyglow.led(12, 20)
    sleep(sleep_speed)
    pyglow.led(6, 30)
    sleep(sleep_speed)
    pyglow.led(17, 40)
    sleep(sleep_speed)
    pyglow.led(16, 50)
    sleep(sleep_speed)
    pyglow.led(15, 60)
    sleep(sleep_speed)
    pyglow.led(14, 70)
    sleep(sleep_speed)
    pyglow.led(13, 80)
    sleep(sleep_speed)
    # Fade Body 4 - 10 and Tail
    pyglow.led(11, 0)
    sleep(sleep_speed)
    pyglow.led(12, 10)
    sleep(sleep_speed)
    pyglow.led(6, 20)
    sleep(sleep_speed)
    pyglow.led(17, 30)
    sleep(sleep_speed)
    pyglow.led(16, 40)
    sleep(sleep_speed)
    pyglow.led(15, 50)
    sleep(sleep_speed)
    pyglow.led(14, 60)
    sleep(sleep_speed)
    pyglow.led(13, 70)
    sleep(sleep_speed)
    # Fade Body 5 - 10 and Tail
    pyglow.led(12, 0)
    sleep(sleep_speed)
    pyglow.led(6, 10)
    sleep(sleep_speed)
    pyglow.led(17, 20)
    sleep(sleep_speed)
    pyglow.led(16, 30)
    sleep(sleep_speed)
    pyglow.led(15, 40)
    sleep(sleep_speed)
    pyglow.led(14, 50)
    sleep(sleep_speed)
    pyglow.led(13, 60)
    sleep(sleep_speed)
    # Fade Body 6 - 10 and Tail
    pyglow.led(6, 0)
    sleep(sleep_speed)
    pyglow.led(17, 10)
    sleep(sleep_speed)
    pyglow.led(16, 20)
    sleep(sleep_speed)
    pyglow.led(15, 30)
    sleep(sleep_speed)
    pyglow.led(14, 40)
    sleep(sleep_speed)
    pyglow.led(13, 50)
    sleep(sleep_speed)
    # Fade Body 7 - 10 and Tail
    pyglow.led(17, 0)
    sleep(sleep_speed)
    pyglow.led(16, 10)
    sleep(sleep_speed)
    pyglow.led(15, 20)
    sleep(sleep_speed)
    pyglow.led(14, 30)
    sleep(sleep_speed)
    pyglow.led(13, 40)
    sleep(sleep_speed)
    # Fade Body 8 - 10 and Tail
    pyglow.led(16, 0)
    sleep(sleep_speed)
    pyglow.led(15, 10)
    sleep(sleep_speed)
    pyglow.led(14, 20)
    sleep(sleep_speed)
    pyglow.led(13, 30)
    sleep(sleep_speed)
    # Fade Body 9 - 10 and Tail
    pyglow.led(15, 0)
    sleep(sleep_speed)
    pyglow.led(14, 10)
    sleep(sleep_speed)
    pyglow.led(13, 20)
    sleep(sleep_speed)
    # Fade Body 10 and Tail
    pyglow.led(14, 0)
    sleep(sleep_speed)
    pyglow.led(13, 10)
    sleep(sleep_speed)
    # Fade Tail
    pyglow.led(13, 0)
    sleep(sleep_speed)
    # Pause before next snake function
    sleep(1)

def slithering_fading_snake_31():
    # Set sleep speed
    sleep_speed = 0.01
    # Turn on Snake Head
    pyglow.led(13, 120)
    sleep(sleep_speed)
    # Turn on Snake Body 1
    pyglow.led(14, 120)
    sleep(sleep_speed)
    # Fade Head
    pyglow.led(13, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 2
    pyglow.led(15, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1
    pyglow.led(13, 100)
    sleep(sleep_speed)
    pyglow.led(14, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 3
    pyglow.led(16, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 2
    pyglow.led(13, 90)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(15, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 4
    pyglow.led(17, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 3
    pyglow.led(13, 80)
    sleep(sleep_speed)
    pyglow.led(14, 90)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(16, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 5
    pyglow.led(18, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 4
    pyglow.led(13, 70)
    sleep(sleep_speed)
    pyglow.led(14, 80)
    sleep(sleep_speed)
    pyglow.led(15, 90)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(17, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 6
    pyglow.led(12, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 5
    pyglow.led(13, 60)
    sleep(sleep_speed)
    pyglow.led(14, 70)
    sleep(sleep_speed)
    pyglow.led(15, 80)
    sleep(sleep_speed)
    pyglow.led(16, 90)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(18, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 7
    pyglow.led(5, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 6
    pyglow.led(13, 50)
    sleep(sleep_speed)
    pyglow.led(14, 60)
    sleep(sleep_speed)
    pyglow.led(15, 70)
    sleep(sleep_speed)
    pyglow.led(16, 80)
    sleep(sleep_speed)
    pyglow.led(17, 90)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(12, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 8
    pyglow.led(4, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 7
    pyglow.led(13, 40)
    sleep(sleep_speed)
    pyglow.led(14, 50)
    sleep(sleep_speed)
    pyglow.led(15, 60)
    sleep(sleep_speed)
    pyglow.led(16, 70)
    sleep(sleep_speed)
    pyglow.led(17, 80)
    sleep(sleep_speed)
    pyglow.led(18, 90)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(5, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 9
    pyglow.led(3, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 8
    pyglow.led(13, 30)
    sleep(sleep_speed)
    pyglow.led(14, 40)
    sleep(sleep_speed)
    pyglow.led(15, 50)
    sleep(sleep_speed)
    pyglow.led(16, 60)
    sleep(sleep_speed)
    pyglow.led(17, 70)
    sleep(sleep_speed)
    pyglow.led(18, 80)
    sleep(sleep_speed)
    pyglow.led(12, 90)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(4, 110)
    sleep(sleep_speed)
    # Turn on Snake Body 10
    pyglow.led(2, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 9
    pyglow.led(13, 20)
    sleep(sleep_speed)
    pyglow.led(14, 30)
    sleep(sleep_speed)
    pyglow.led(15, 40)
    sleep(sleep_speed)
    pyglow.led(16, 50)
    sleep(sleep_speed)
    pyglow.led(17, 60)
    sleep(sleep_speed)
    pyglow.led(18, 70)
    sleep(sleep_speed)
    pyglow.led(12, 80)
    sleep(sleep_speed)
    pyglow.led(5, 90)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(3, 110)
    sleep(sleep_speed)
    # Turn on Snake Tail
    pyglow.led(1, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 10
    pyglow.led(13, 10)
    sleep(sleep_speed)
    pyglow.led(14, 20)
    sleep(sleep_speed)
    pyglow.led(15, 30)
    sleep(sleep_speed)
    pyglow.led(16, 40)
    sleep(sleep_speed)
    pyglow.led(17, 50)
    sleep(sleep_speed)
    pyglow.led(18, 60)
    sleep(sleep_speed)
    pyglow.led(12, 70)
    sleep(sleep_speed)
    pyglow.led(5, 80)
    sleep(sleep_speed)
    pyglow.led(4, 90)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(2, 110)
    sleep(sleep_speed)
    # Fade Head, Body 1 - 10, and Tail
    pyglow.led(13, 0)
    sleep(sleep_speed)
    pyglow.led(14, 10)
    sleep(sleep_speed)
    pyglow.led(15, 20)
    sleep(sleep_speed)
    pyglow.led(16, 30)
    sleep(sleep_speed)
    pyglow.led(17, 40)
    sleep(sleep_speed)
    pyglow.led(18, 50)
    sleep(sleep_speed)
    pyglow.led(12, 60)
    sleep(sleep_speed)
    pyglow.led(5, 70)
    sleep(sleep_speed)
    pyglow.led(4, 80)
    sleep(sleep_speed)
    pyglow.led(3, 90)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(1, 110)
    sleep(sleep_speed)
    # Fade Body 1 - 10 and Tail
    pyglow.led(14, 0)
    sleep(sleep_speed)
    pyglow.led(15, 10)
    sleep(sleep_speed)
    pyglow.led(16, 20)
    sleep(sleep_speed)
    pyglow.led(17, 30)
    sleep(sleep_speed)
    pyglow.led(18, 40)
    sleep(sleep_speed)
    pyglow.led(12, 50)
    sleep(sleep_speed)
    pyglow.led(5, 60)
    sleep(sleep_speed)
    pyglow.led(4, 70)
    sleep(sleep_speed)
    pyglow.led(3, 80)
    sleep(sleep_speed)
    pyglow.led(2, 90)
    sleep(sleep_speed)
    pyglow.led(1, 100)
    sleep(sleep_speed)
    # Fade Body 2 - 10 and Tail
    pyglow.led(15, 0)
    sleep(sleep_speed)
    pyglow.led(16, 10)
    sleep(sleep_speed)
    pyglow.led(17, 20)
    sleep(sleep_speed)
    pyglow.led(18, 30)
    sleep(sleep_speed)
    pyglow.led(12, 40)
    sleep(sleep_speed)
    pyglow.led(5, 50)
    sleep(sleep_speed)
    pyglow.led(4, 60)
    sleep(sleep_speed)
    pyglow.led(3, 70)
    sleep(sleep_speed)
    pyglow.led(2, 80)
    sleep(sleep_speed)
    pyglow.led(1, 90)
    sleep(sleep_speed)
    # Fade Body 3 - 10 and Tail
    pyglow.led(16, 0)
    sleep(sleep_speed)
    pyglow.led(17, 10)
    sleep(sleep_speed)
    pyglow.led(18, 20)
    sleep(sleep_speed)
    pyglow.led(12, 30)
    sleep(sleep_speed)
    pyglow.led(5, 40)
    sleep(sleep_speed)
    pyglow.led(4, 50)
    sleep(sleep_speed)
    pyglow.led(3, 60)
    sleep(sleep_speed)
    pyglow.led(2, 70)
    sleep(sleep_speed)
    pyglow.led(1, 80)
    sleep(sleep_speed)
    # Fade Body 4 - 10 and Tail
    pyglow.led(17, 0)
    sleep(sleep_speed)
    pyglow.led(18, 10)
    sleep(sleep_speed)
    pyglow.led(12, 20)
    sleep(sleep_speed)
    pyglow.led(5, 30)
    sleep(sleep_speed)
    pyglow.led(4, 40)
    sleep(sleep_speed)
    pyglow.led(3, 50)
    sleep(sleep_speed)
    pyglow.led(2, 60)
    sleep(sleep_speed)
    pyglow.led(1, 70)
    sleep(sleep_speed)
    # Fade Body 5 - 10 and Tail
    pyglow.led(18, 0)
    sleep(sleep_speed)
    pyglow.led(12, 10)
    sleep(sleep_speed)
    pyglow.led(5, 20)
    sleep(sleep_speed)
    pyglow.led(4, 30)
    sleep(sleep_speed)
    pyglow.led(3, 40)
    sleep(sleep_speed)
    pyglow.led(2, 50)
    sleep(sleep_speed)
    pyglow.led(1, 60)
    sleep(sleep_speed)
    # Fade Body 6 - 10 and Tail
    pyglow.led(12, 0)
    sleep(sleep_speed)
    pyglow.led(5, 10)
    sleep(sleep_speed)
    pyglow.led(4, 20)
    sleep(sleep_speed)
    pyglow.led(3, 30)
    sleep(sleep_speed)
    pyglow.led(2, 40)
    sleep(sleep_speed)
    pyglow.led(1, 50)
    sleep(sleep_speed)
    # Fade Body 7 - 10 and Tail
    pyglow.led(5, 0)
    sleep(sleep_speed)
    pyglow.led(4, 10)
    sleep(sleep_speed)
    pyglow.led(3, 20)
    sleep(sleep_speed)
    pyglow.led(2, 30)
    sleep(sleep_speed)
    pyglow.led(1, 40)
    sleep(sleep_speed)
    # Fade Body 8 - 10 and Tail
    pyglow.led(4, 0)
    sleep(sleep_speed)
    pyglow.led(3, 10)
    sleep(sleep_speed)
    pyglow.led(2, 20)
    sleep(sleep_speed)
    pyglow.led(1, 30)
    sleep(sleep_speed)
    # Fade Body 9 - 10 and Tail
    pyglow.led(3, 0)
    sleep(sleep_speed)
    pyglow.led(2, 10)
    sleep(sleep_speed)
    pyglow.led(1, 20)
    sleep(sleep_speed)
    # Fade Body 10 and Tail
    pyglow.led(2, 0)
    sleep(sleep_speed)
    pyglow.led(1, 10)
    sleep(sleep_speed)
    # Fade Tail
    pyglow.led(1, 0)
    sleep(sleep_speed)
    # Pause before next snake function
    sleep(1)

def slithering_fading_snake_32():
    # Set sleep speed
    sleep_speed = 0.01
    # Turn on Snake Head
    pyglow.led(13, 120)
    sleep(sleep_speed)
    # Turn on Body 1
    pyglow.led(14, 120)
    sleep(sleep_speed)
    # Fade Head
    pyglow.led(13, 110)
    sleep(sleep_speed)
    # Turn on Body 2
    pyglow.led(15, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1
    pyglow.led(13, 100)
    sleep(sleep_speed)
    pyglow.led(14, 110)
    sleep(sleep_speed)
    # Turn on Body 3
    pyglow.led(16, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 2
    pyglow.led(13, 90)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(15, 110)
    sleep(sleep_speed)
    # Turn on Body 4
    pyglow.led(17, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 3
    pyglow.led(13, 80)
    sleep(sleep_speed)
    pyglow.led(14, 90)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(16, 110)
    sleep(sleep_speed)
    # Turn on Body 5
    pyglow.led(6, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 4
    pyglow.led(13, 70)
    sleep(sleep_speed)
    pyglow.led(14, 80)
    sleep(sleep_speed)
    pyglow.led(15, 90)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(17, 110)
    sleep(sleep_speed)
    # Turn on Body 6
    pyglow.led(12, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 5
    pyglow.led(13, 60)
    sleep(sleep_speed)
    pyglow.led(14, 70)
    sleep(sleep_speed)
    pyglow.led(15, 80)
    sleep(sleep_speed)
    pyglow.led(16, 90)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(6, 110)
    sleep(sleep_speed)
    # Turn on Body 7
    pyglow.led(11, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 6
    pyglow.led(13, 50)
    sleep(sleep_speed)
    pyglow.led(14, 60)
    sleep(sleep_speed)
    pyglow.led(15, 70)
    sleep(sleep_speed)
    pyglow.led(16, 80)
    sleep(sleep_speed)
    pyglow.led(17, 90)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(12, 110)
    sleep(sleep_speed)
    # Turn on Body 8
    pyglow.led(10, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 7
    pyglow.led(13, 40)
    sleep(sleep_speed)
    pyglow.led(14, 50)
    sleep(sleep_speed)
    pyglow.led(15, 60)
    sleep(sleep_speed)
    pyglow.led(16, 70)
    sleep(sleep_speed)
    pyglow.led(17, 80)
    sleep(sleep_speed)
    pyglow.led(6, 90)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(11, 110)
    sleep(sleep_speed)
    # Turn on Body 9
    pyglow.led(9, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 8
    pyglow.led(13, 30)
    sleep(sleep_speed)
    pyglow.led(14, 40)
    sleep(sleep_speed)
    pyglow.led(15, 50)
    sleep(sleep_speed)
    pyglow.led(16, 60)
    sleep(sleep_speed)
    pyglow.led(17, 70)
    sleep(sleep_speed)
    pyglow.led(6, 80)
    sleep(sleep_speed)
    pyglow.led(12, 90)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(10, 110)
    sleep(sleep_speed)
    # Turn on Body 10
    pyglow.led(8, 120)
    sleep(sleep_speed)
    # Fade Head and Body 1 - 9
    pyglow.led(13, 20)
    sleep(sleep_speed)
    pyglow.led(14, 30)
    sleep(sleep_speed)
    pyglow.led(15, 40)
    sleep(sleep_speed)
    pyglow.led(16, 50)
    sleep(sleep_speed)
    pyglow.led(17, 60)
    sleep(sleep_speed)
    pyglow.led(6, 70)
    sleep(sleep_speed)
    pyglow.led(12, 80)
    sleep(sleep_speed)
    pyglow.led(11, 90)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(9, 110)
    sleep(sleep_speed)
    # Turn on Tail
    pyglow.led(7, 120)
    sleep(sleep_speed)
    # Fade Head  and Body 1 - 10
    pyglow.led(13, 10)
    sleep(sleep_speed)
    pyglow.led(14, 20)
    sleep(sleep_speed)
    pyglow.led(15, 30)
    sleep(sleep_speed)
    pyglow.led(16, 40)
    sleep(sleep_speed)
    pyglow.led(17, 50)
    sleep(sleep_speed)
    pyglow.led(6, 60)
    sleep(sleep_speed)
    pyglow.led(12, 70)
    sleep(sleep_speed)
    pyglow.led(11, 80)
    sleep(sleep_speed)
    pyglow.led(10, 90)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(8, 110)
    sleep(sleep_speed)
    # Fade Head, Body 1 - 10, and Tail
    pyglow.led(13, 0)
    sleep(sleep_speed)
    pyglow.led(14, 10)
    sleep(sleep_speed)
    pyglow.led(15, 20)
    sleep(sleep_speed)
    pyglow.led(16, 30)
    sleep(sleep_speed)
    pyglow.led(17, 40)
    sleep(sleep_speed)
    pyglow.led(6, 50)
    sleep(sleep_speed)
    pyglow.led(12, 60)
    sleep(sleep_speed)
    pyglow.led(11, 70)
    sleep(sleep_speed)
    pyglow.led(10, 80)
    sleep(sleep_speed)
    pyglow.led(9, 90)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(7, 110)
    sleep(sleep_speed)
    # Fade Body 1 - 10 and Tail
    pyglow.led(14, 0)
    sleep(sleep_speed)
    pyglow.led(15, 10)
    sleep(sleep_speed)
    pyglow.led(16, 20)
    sleep(sleep_speed)
    pyglow.led(17, 30)
    sleep(sleep_speed)
    pyglow.led(6, 40)
    sleep(sleep_speed)
    pyglow.led(12, 50)
    sleep(sleep_speed)
    pyglow.led(11, 60)
    sleep(sleep_speed)
    pyglow.led(10, 70)
    sleep(sleep_speed)
    pyglow.led(9, 80)
    sleep(sleep_speed)
    pyglow.led(8, 90)
    sleep(sleep_speed)
    pyglow.led(7, 100)
    sleep(sleep_speed)
    # Fade Body 2 - 10 and Tail
    pyglow.led(15, 0)
    sleep(sleep_speed)
    pyglow.led(16, 10)
    sleep(sleep_speed)
    pyglow.led(17, 20)
    sleep(sleep_speed)
    pyglow.led(6, 30)
    sleep(sleep_speed)
    pyglow.led(12, 40)
    sleep(sleep_speed)
    pyglow.led(11, 50)
    sleep(sleep_speed)
    pyglow.led(10, 60)
    sleep(sleep_speed)
    pyglow.led(9, 70)
    sleep(sleep_speed)
    pyglow.led(8, 80)
    sleep(sleep_speed)
    pyglow.led(7, 90)
    sleep(sleep_speed)
    # Fade Body 3 - 10 and Tail)
    pyglow.led(16, 0)
    sleep(sleep_speed)
    pyglow.led(17, 10)
    sleep(sleep_speed)
    pyglow.led(6, 20)
    sleep(sleep_speed)
    pyglow.led(12, 30)
    sleep(sleep_speed)
    pyglow.led(11, 40)
    sleep(sleep_speed)
    pyglow.led(10, 50)
    sleep(sleep_speed)
    pyglow.led(9, 60)
    sleep(sleep_speed)
    pyglow.led(8, 70)
    sleep(sleep_speed)
    pyglow.led(7, 80)
    sleep(sleep_speed)
    # Fade Body 4 - 10 and Tail)
    pyglow.led(17, 0)
    sleep(sleep_speed)
    pyglow.led(6, 10)
    sleep(sleep_speed)
    pyglow.led(12, 20)
    sleep(sleep_speed)
    pyglow.led(11, 30)
    sleep(sleep_speed)
    pyglow.led(10, 40)
    sleep(sleep_speed)
    pyglow.led(9, 50)
    sleep(sleep_speed)
    pyglow.led(8, 60)
    sleep(sleep_speed)
    pyglow.led(7, 70)
    sleep(sleep_speed)
    # Fade Body 5 - 10 and Tail)
    pyglow.led(6, 0)
    sleep(sleep_speed)
    pyglow.led(12, 10)
    sleep(sleep_speed)
    pyglow.led(11, 20)
    sleep(sleep_speed)
    pyglow.led(10, 30)
    sleep(sleep_speed)
    pyglow.led(9, 40)
    sleep(sleep_speed)
    pyglow.led(8, 50)
    sleep(sleep_speed)
    pyglow.led(7, 60)
    sleep(sleep_speed)
    # Fade Body 6 - 10 and Tail
    pyglow.led(12, 0)
    sleep(sleep_speed)
    pyglow.led(11, 10)
    sleep(sleep_speed)
    pyglow.led(10, 20)
    sleep(sleep_speed)
    pyglow.led(9, 30)
    sleep(sleep_speed)
    pyglow.led(8, 40)
    sleep(sleep_speed)
    pyglow.led(7, 50)
    sleep(sleep_speed)
    # Fade Body 7 - 10 and Tail
    pyglow.led(11, 0)
    sleep(sleep_speed)
    pyglow.led(10, 10)
    sleep(sleep_speed)
    pyglow.led(9, 20)
    sleep(sleep_speed)
    pyglow.led(8, 30)
    sleep(sleep_speed)
    pyglow.led(7, 40)
    sleep(sleep_speed)
    # Fade Body 8 - 10 and Tail
    pyglow.led(10, 0)
    sleep(sleep_speed)
    pyglow.led(9, 10)
    sleep(sleep_speed)
    pyglow.led(8, 20)
    sleep(sleep_speed)
    pyglow.led(7, 30)
    sleep(sleep_speed)
    # Fade Body 9 - 10 and Tail
    pyglow.led(9, 0)
    sleep(sleep_speed)
    pyglow.led(8, 10)
    sleep(sleep_speed)
    pyglow.led(7, 20)
    sleep(sleep_speed)
    # Fade Body 10 and Tail
    pyglow.led(8, 0)
    sleep(sleep_speed)
    pyglow.led(7, 10)
    sleep(sleep_speed)
    # Fade Tail
    pyglow.led(7, 0)
    sleep(sleep_speed)
    # Pause before next snake function
    sleep(1)


def pulsing_snake_12():
    pulse_speed = 125
    while pulse_speed > 100:
        ''' Uncomment the following print statement for feedback '''
        #print "Pulse speed is: ", pulse_speed
    	pyglow.set_leds(snake_12_leds, 100, speed = pulse_speed, pulse = True)
    	sleep(0)
    	pyglow.update_leds()
        pulse_speed -= 1
    pyglow.set_leds(snake_12_leds, 0)
    pyglow.update_leds()
    sleep(1)

def pulsing_snake_13():
    pulse_speed = 125
    while pulse_speed > 100:
        ''' Uncomment the following print statement for feedback '''
        #print "Pulse speed is: ", pulse_speed
    	pyglow.set_leds(snake_13_leds, 100, speed = pulse_speed, pulse = True)
    	sleep(0)
    	pyglow.update_leds()
        pulse_speed -= 1
    pyglow.set_leds(snake_13_leds, 0)
    pyglow.update_leds()
    sleep(1)
    
def pulsing_snake_23():
    pulse_speed = 125
    while pulse_speed > 100:
        ''' Uncomment the following print statement for feedback '''
        #print "Pulse speed is: ", pulse_speed
    	pyglow.set_leds(snake_23_leds, 100, speed = pulse_speed, pulse = True)
    	sleep(0)
    	pyglow.update_leds()
        pulse_speed -= 1
    pyglow.set_leds(snake_23_leds, 0)
    pyglow.update_leds()
    sleep(1)

def exploding_snake_12():
    # Variables
    explode_speed = 0.020
    # Pulse
    pulse_snake_12_or_21()
    # Explode Snake 12 
    ''' Uncomment the following print statement for feedback '''
    #print "Exploding Snake 12..."
    pyglow.led(6, 0)
    sleep(explode_speed)
    pyglow.led(18, 0)
    sleep(explode_speed)
    pyglow.led(11, 0)
    sleep(explode_speed)
    pyglow.led(5, 0)
    sleep(explode_speed)
    pyglow.led(10, 0)
    sleep(explode_speed)
    pyglow.led(4, 0)
    sleep(explode_speed)
    pyglow.led(9, 0)
    sleep(explode_speed)
    pyglow.led(3, 0)
    sleep(explode_speed)
    pyglow.led(8, 0)
    sleep(explode_speed)
    pyglow.led(2, 0)
    sleep(explode_speed)
    pyglow.led(7, 0)
    sleep(explode_speed)
    pyglow.led(1, 0)
    sleep(explode_speed)
    pyglow.update_leds()

    sleep(1)

def exploding_snake_13():
    # Variables
    explode_speed = 0.020
    # Pulse
    pulse_snake_13_or_31()
    # Explode Snake 13 
    ''' Uncomment the following print statement for feedback '''
    #print "Exploding Snake 13..."
    pyglow.led(18, 0)
    sleep(explode_speed)
    pyglow.led(12, 0)
    sleep(explode_speed)
    pyglow.led(17, 0)
    sleep(explode_speed)
    pyglow.led(5, 0)
    sleep(explode_speed)
    pyglow.led(16, 0)
    sleep(explode_speed)
    pyglow.led(4, 0)
    sleep(explode_speed)
    pyglow.led(15, 0)
    sleep(explode_speed)
    pyglow.led(3, 0)
    sleep(explode_speed)
    pyglow.led(14, 0)
    sleep(explode_speed)
    pyglow.led(2, 0)
    sleep(explode_speed)
    pyglow.led(13, 0)
    sleep(explode_speed)
    pyglow.led(1, 0)
    sleep(explode_speed)
    pyglow.update_leds()

    sleep(1)
    
def exploding_snake_23():
    # Variables
    explode_speed = 0.020
    # Pulse
    pulse_snake_23_or_32()
    ''' Uncomment the following print statement for feedback '''
    #print "Exploding Snake 23..."
    # Explode Snake 13 
    pyglow.led(6, 0)
    sleep(explode_speed)
    pyglow.led(12, 0)
    sleep(explode_speed)
    pyglow.led(11, 0)
    sleep(explode_speed)
    pyglow.led(17, 0)
    sleep(explode_speed)
    pyglow.led(10, 0)
    sleep(explode_speed)
    pyglow.led(16, 0)
    sleep(explode_speed)
    pyglow.led(9, 0)
    sleep(explode_speed)
    pyglow.led(15, 0)
    sleep(explode_speed)
    pyglow.led(8, 0)
    sleep(explode_speed)
    pyglow.led(14, 0)
    sleep(explode_speed)
    pyglow.led(7, 0)
    sleep(explode_speed)
    pyglow.led(13, 0)
    sleep(explode_speed)
    pyglow.update_leds()

    sleep(1)

def slithering_exploding_snake_12():
    # Set sleep speed
    sleep_speed = 0.10
    # Light up Snake 12
    '''' Uncomment the following line for feedback '''
    #print "Snake 12 is slithering..."
    pyglow.led(1, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(7, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_12_or_21()
    # Explode Snake 12
    '''' Uncomment the following line for feedback '''
    #print "Snake 12 is exploding..."
    explode_snake_12_or_21()

def slithering_exploding_snake_13():
    # Set sleep speed
    sleep_speed = 0.10
    # Light up Snake 13
    '''' Uncomment the following line for feedback '''
    #print "Snake 13 is slithering..."
    pyglow.led(1, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(13, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_13_or_31()
    # Explode Snake 13
    '''' Uncomment the following line for feedback '''
    #print "Snake 13 is exploding..."
    explode_snake_13_or_31()

def slithering_exploding_snake_21():
    # Set sleep speed
    sleep_speed = 0.10
    # Light up Snake 21
    '''' Uncomment the following line for feedback '''
    #print "Snake 21 is slithering..."
    pyglow.led(7, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(1, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_12_or_21()
    # Explode Snake 21
    '''' Uncomment the following line for feedback '''
    #print "Snake 21 is exploding..."
    explode_snake_12_or_21()

def slithering_exploding_snake_23():
    # Set sleep speed
    sleep_speed = 0.10
    # Light up Snake 23
    '''' Uncomment the following line for feedback '''
    #print "Snake 23 is slithering..."
    pyglow.led(7, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(13, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_23_or_32()
    # Explode Snake 23
    '''' Uncomment the following line for feedback '''
    #print "Snake 23 is exploding..."
    explode_snake_23_or_32()
    
def slithering_exploding_snake_31():
    # Set sleep speed
    sleep_speed = 0.10
    # Light up Snake 31
    '''' Uncomment the following line for feedback '''
    #print "Snake 31 is slithering..."
    pyglow.led(13, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(1, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_13_or_31()
    # Explode Snake 31
    '''' Uncomment the following line for feedback '''
    #print "Snake 31 is exploding..."
    explode_snake_13_or_31()

def slithering_exploding_snake_32():
    # Set sleep speed
    sleep_speed = 0.10
    # Light up Snake 32
    '''' Uncomment the following line for feedback '''
    #print "Snake 32 is slithering..." 
    pyglow.led(13, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(7, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_23_or_32()
    # Explode Snake 32
    '''' Uncomment the following line for feedback '''
    #print "Snake 32 is slithering..."
    explode_snake_23_or_32()
    
def pulse_snake_12_or_21():
    # Variable
    pulse_speed = 175
    ''' Uncomment the following print statement for feedback '''
    #print "Snake is pulsing."
    while pulse_speed < 225:
        ''' Uncomment the following print statement for feedback '''
        #print "Pulse speed is: ", pulse_speed
    	pyglow.led(snake_12_leds, 100, speed = pulse_speed, pulse = True)
    	sleep(0)
    	pyglow.update_leds()
        pulse_speed += 1
    pyglow.led(snake_12_leds, 100)
    sleep(1)

def pulse_snake_13_or_31():
    # Variable
    pulse_speed = 175
    ''' Uncomment the following print statement for feedback '''
    #print "Snake is pulsing."
    while pulse_speed < 225:
        ''' Uncomment the following print statement for feedback '''
        #print "Pulse speed is: ", pulse_speed
    	pyglow.led(snake_13_leds, 100, speed = pulse_speed, pulse = True)
    	sleep(0)
    	pyglow.update_leds()
        pulse_speed += 1
    pyglow.led(snake_13_leds, 100)
    sleep(1)

def pulse_snake_23_or_32():
    # Variable
    pulse_speed = 175
    ''' Uncomment the following print statement for feedback '''
    #print "Snake is pulsing."
    while pulse_speed < 225:
        ''' Uncomment the following print statement for feedback '''
        #print "Pulse speed is: ", pulse_speed
    	pyglow.led(snake_23_leds, 100, speed = pulse_speed, pulse = True)
    	sleep(0)
    	pyglow.update_leds()
        pulse_speed += 1
    pyglow.led(snake_23_leds, 100)
    sleep(1)

def explode_snake_12_or_21():
    # Variables
    explode_speed = 0.015
    # Explode snake 12 or 21
    pyglow.led(18, 0)
    sleep(explode_speed)
    pyglow.led(6, 0)
    sleep(explode_speed)
    pyglow.led(11, 0)
    sleep(explode_speed)
    pyglow.led(5, 0)
    sleep(explode_speed)
    pyglow.led(10, 0)
    sleep(explode_speed)
    pyglow.led(4, 0)
    sleep(explode_speed)
    pyglow.led(9, 0)
    sleep(explode_speed)
    pyglow.led(3, 0)
    sleep(explode_speed)
    pyglow.led(8, 0)
    sleep(explode_speed)
    pyglow.led(2, 0)
    sleep(explode_speed)
    pyglow.led(7, 0)
    sleep(explode_speed)
    pyglow.led(1, 0)
    sleep(1)

def explode_snake_13_or_31():
    # Variables
    explode_speed = 0.020
    # Explode snake 13 or 31
    pyglow.led(18, 0)
    sleep(explode_speed)
    pyglow.led(12, 0)
    sleep(explode_speed)
    pyglow.led(17, 0)
    sleep(explode_speed)
    pyglow.led(5, 0)
    sleep(explode_speed)
    pyglow.led(16, 0)
    sleep(explode_speed)
    pyglow.led(4, 0)
    sleep(explode_speed)
    pyglow.led(15, 0)
    sleep(explode_speed)
    pyglow.led(3, 0)
    sleep(explode_speed)
    pyglow.led(14, 0)
    sleep(explode_speed)
    pyglow.led(2, 0)
    sleep(explode_speed)
    pyglow.led(13, 0)
    sleep(explode_speed)
    pyglow.led(1, 0)
    sleep(1)

def explode_snake_23_or_32():
    # Variables
    explode_speed = 0.020
    # Explode snake 23 or 32
    pyglow.led(12, 0)
    sleep(explode_speed)
    pyglow.led(6, 0)
    sleep(explode_speed)
    pyglow.led(17, 0)
    sleep(explode_speed)
    pyglow.led(11, 0)
    sleep(explode_speed)
    pyglow.led(16, 0)
    sleep(explode_speed)
    pyglow.led(10, 0)
    sleep(explode_speed)
    pyglow.led(15, 0)
    sleep(explode_speed)
    pyglow.led(9, 0)
    sleep(explode_speed)
    pyglow.led(14, 0)
    sleep(explode_speed)
    pyglow.led(8, 0)
    sleep(explode_speed)
    pyglow.led(13, 0)
    sleep(explode_speed)
    pyglow.led(7, 0)
    sleep(1)

def slithering_fizzling_fading_snake_12():
    # Variables
    sleep_speed = 0.10
    # Light up Snake 12
    '''' Uncomment the following line for feedback '''
    #print "Snake 12 is slithering..."
    pyglow.led(1, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(7, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_12_or_21()
    # Explode Snake 12
    '''' Uncomment the following line for feedback '''
    #print "Snake 12 is exploding..."
    fizzling_snake_12_or_21()
    sleep(1)

def slithering_fizzling_fading_snake_13():
    # Variables
    sleep_speed = 0.10
    # Light up Snake 13
    '''' Uncomment the following line for feedback '''
    #print "Snake 13 is slithering..."
    pyglow.led(1, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(13, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_13_or_31()
    # Explode Snake 13
    '''' Uncomment the following line for feedback '''
    #print "Snake 13 is exploding..."
    fizzling_snake_13_or_31()
    sleep(1)

def slithering_fizzling_fading_snake_21():
    # Variables
    sleep_speed = 0.10
    # Light up Snake 21
    '''' Uncomment the following line for feedback '''
    #print "Snake 21 is slithering..."
    pyglow.led(7, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(1, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_12_or_21()
    # Explode Snake 21
    '''' Uncomment the following line for feedback '''
    #print "Snake 21 is exploding..."
    fizzling_snake_12_or_21()
    sleep(1)

def slithering_fizzling_fading_snake_23():
    # Variables
    sleep_speed = 0.10
    # Light up Snake 23
    '''' Uncomment the following line for feedback '''
    #print "Snake 23 is slithering..."
    pyglow.led(7, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(13, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_23_or_32()
    # Explode Snake 23
    '''' Uncomment the following line for feedback '''
    #print "Snake 23 is exploding..."
    fizzling_snake_23_or_32()
    sleep(1)
    
def slithering_fizzling_fading_snake_31():
    # Variables
    sleep_speed = 0.10
    # Light up Snake 31
    '''' Uncomment the following line for feedback '''
    #print "Snake 31 is slithering..."
    pyglow.led(13, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(1, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_13_or_31()
    # Explode Snake 31
    '''' Uncomment the following line for feedback '''
    #print "Snake 31 is exploding..."
    fizzling_snake_13_or_31()
    sleep(1)

def slithering_fizzling_fading_snake_32():
    # Variables
    sleep_speed = 0.10
    # Light up Snake 32
    '''' Uncomment the following line for feedback '''
    #print "Snake 32 is slithering..." 
    pyglow.led(13, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(7, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_23_or_32()
    # Explode Snake 32
    '''' Uncomment the following line for feedback '''
    #print "Snake 32 is slithering..."
    fizzling_snake_23_or_32()
    sleep(1)

def fizzling_snake_12_or_21():
    # Variables
    explode_speed = 0.01
    # Fade Body 5 (on both sides)
    pyglow.led(18, 90)
    sleep(explode_speed)
    pyglow.led(6, 90)
    sleep(explode_speed)
    # Fade Body 5 and 4
    pyglow.led(18, 80)
    sleep(explode_speed)
    pyglow.led(6, 80)
    sleep(explode_speed)
    pyglow.led(11, 90)
    sleep(explode_speed)
    pyglow.led(5, 90)
    # Fade Body 5 - 3
    pyglow.led(18, 70)
    sleep(explode_speed)
    pyglow.led(6, 70)
    sleep(explode_speed)
    pyglow.led(11, 80)
    sleep(explode_speed)
    pyglow.led(5, 80)
    sleep(explode_speed)
    pyglow.led(10, 90)
    sleep(explode_speed)
    pyglow.led(4, 90)
    # Fade Body 5 - 2
    pyglow.led(18, 60)
    sleep(explode_speed)
    pyglow.led(6, 60)
    sleep(explode_speed)
    pyglow.led(11, 70)
    sleep(explode_speed)
    pyglow.led(5, 70)
    sleep(explode_speed)
    pyglow.led(10, 80)
    sleep(explode_speed)
    pyglow.led(4, 80)
    sleep(explode_speed)
    pyglow.led(9, 90)
    sleep(explode_speed)
    pyglow.led(3, 90)
    # Fade Body 5 - 1
    pyglow.led(18, 50)
    sleep(explode_speed)
    pyglow.led(6, 50)
    sleep(explode_speed)
    pyglow.led(11, 60)
    sleep(explode_speed)
    pyglow.led(5, 60)
    sleep(explode_speed)
    pyglow.led(10, 70)
    sleep(explode_speed)
    pyglow.led(4, 70)
    sleep(explode_speed)
    pyglow.led(9, 80)
    sleep(explode_speed)
    pyglow.led(3, 80)
    sleep(explode_speed)
    pyglow.led(8, 90)
    sleep(explode_speed)
    pyglow.led(2, 90)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 40)
    sleep(explode_speed)
    pyglow.led(6, 40)
    sleep(explode_speed)
    pyglow.led(11, 50)
    sleep(explode_speed)
    pyglow.led(5, 50)
    sleep(explode_speed)
    pyglow.led(10, 60)
    sleep(explode_speed)
    pyglow.led(4, 60)
    sleep(explode_speed)
    pyglow.led(9, 70)
    sleep(explode_speed)
    pyglow.led(3, 70)
    sleep(explode_speed)
    pyglow.led(8, 80)
    sleep(explode_speed)
    pyglow.led(2, 80)
    sleep(explode_speed)
    pyglow.led(7, 90)
    sleep(explode_speed)
    pyglow.led(1, 90)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 30)
    sleep(explode_speed)
    pyglow.led(6, 30)
    sleep(explode_speed)
    pyglow.led(11, 40)
    sleep(explode_speed)
    pyglow.led(5, 40)
    sleep(explode_speed)
    pyglow.led(10, 50)
    sleep(explode_speed)
    pyglow.led(4, 50)
    sleep(explode_speed)
    pyglow.led(9, 60)
    sleep(explode_speed)
    pyglow.led(3, 60)
    sleep(explode_speed)
    pyglow.led(8, 70)
    sleep(explode_speed)
    pyglow.led(2, 70)
    sleep(explode_speed)
    pyglow.led(7, 80)
    sleep(explode_speed)
    pyglow.led(1, 80)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 20)
    sleep(explode_speed)
    pyglow.led(6, 20)
    sleep(explode_speed)
    pyglow.led(11, 30)
    sleep(explode_speed)
    pyglow.led(5, 30)
    sleep(explode_speed)
    pyglow.led(10, 40)
    sleep(explode_speed)
    pyglow.led(4, 40)
    sleep(explode_speed)
    pyglow.led(9, 50)
    sleep(explode_speed)
    pyglow.led(3, 50)
    sleep(explode_speed)
    pyglow.led(8, 60)
    sleep(explode_speed)
    pyglow.led(2, 60)
    sleep(explode_speed)
    pyglow.led(7, 70)
    sleep(explode_speed)
    pyglow.led(1, 70)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 10)
    sleep(explode_speed)
    pyglow.led(6, 10)
    sleep(explode_speed)
    pyglow.led(11, 20)
    sleep(explode_speed)
    pyglow.led(5, 20)
    sleep(explode_speed)
    pyglow.led(10, 30)
    sleep(explode_speed)
    pyglow.led(4, 30)
    sleep(explode_speed)
    pyglow.led(9, 40)
    sleep(explode_speed)
    pyglow.led(3, 40)
    sleep(explode_speed)
    pyglow.led(8, 50)
    sleep(explode_speed)
    pyglow.led(2, 50)
    sleep(explode_speed)
    pyglow.led(7, 60)
    sleep(explode_speed)
    pyglow.led(1, 60)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 0)
    sleep(explode_speed)
    pyglow.led(6, 0)
    sleep(explode_speed)
    pyglow.led(11, 10)
    sleep(explode_speed)
    pyglow.led(5, 10)
    sleep(explode_speed)
    pyglow.led(10, 20)
    sleep(explode_speed)
    pyglow.led(4, 20)
    sleep(explode_speed)
    pyglow.led(9, 30)
    sleep(explode_speed)
    pyglow.led(3, 30)
    sleep(explode_speed)
    pyglow.led(8, 40)
    sleep(explode_speed)
    pyglow.led(2, 40)
    sleep(explode_speed)
    pyglow.led(7, 50)
    sleep(explode_speed)
    pyglow.led(1, 50)
    sleep(explode_speed)
    # Fade Body 4 -1, Head and Tail
    pyglow.led(11, 0)
    sleep(explode_speed)
    pyglow.led(5, 0)
    sleep(explode_speed)
    pyglow.led(10, 10)
    sleep(explode_speed)
    pyglow.led(4, 10)
    sleep(explode_speed)
    pyglow.led(9, 20)
    sleep(explode_speed)
    pyglow.led(3, 20)
    sleep(explode_speed)
    pyglow.led(8, 30)
    sleep(explode_speed)
    pyglow.led(2, 30)
    sleep(explode_speed)
    pyglow.led(7, 40)
    sleep(explode_speed)
    pyglow.led(1, 40)
    sleep(explode_speed)
    # Fade Body 3 -1, Head and Tail
    pyglow.led(10, 0)
    sleep(explode_speed)
    pyglow.led(4, 0)
    sleep(explode_speed)
    pyglow.led(9, 10)
    sleep(explode_speed)
    pyglow.led(3, 10)
    sleep(explode_speed)
    pyglow.led(8, 20)
    sleep(explode_speed)
    pyglow.led(2, 20)
    sleep(explode_speed)
    pyglow.led(7, 30)
    sleep(explode_speed)
    pyglow.led(1, 30)
    sleep(explode_speed)
    # Fade Body 2 - 1, Head and Tail
    pyglow.led(9, 0)
    sleep(explode_speed)
    pyglow.led(3, 0)
    sleep(explode_speed)
    pyglow.led(8, 10)
    sleep(explode_speed)
    pyglow.led(2, 10)
    sleep(explode_speed)
    pyglow.led(7, 20)
    sleep(explode_speed)
    pyglow.led(1, 20)
    sleep(explode_speed)
    # Fade Body 1, Head and Tail
    pyglow.led(8, 0)
    sleep(explode_speed)
    pyglow.led(2, 0)
    sleep(explode_speed)
    pyglow.led(7, 10)
    sleep(explode_speed)
    pyglow.led(1, 10)
    sleep(explode_speed)
    # Fade Head and Tail
    pyglow.led(7, 0)
    sleep(explode_speed)
    pyglow.led(1, 0)
    sleep(explode_speed)

def fizzling_snake_13_or_31():
    # Variables
    explode_speed = 0.01
    # Fade Body 5 (on both sides)
    pyglow.led(18, 90)
    sleep(explode_speed)
    pyglow.led(12, 90)
    sleep(explode_speed)
    # Fade Body 5 and 4
    pyglow.led(18, 80)
    sleep(explode_speed)
    pyglow.led(12, 80)
    sleep(explode_speed)
    pyglow.led(17, 90)
    sleep(explode_speed)
    pyglow.led(5, 90)
    # Fade Body 5 - 3
    pyglow.led(18, 70)
    sleep(explode_speed)
    pyglow.led(12, 70)
    sleep(explode_speed)
    pyglow.led(17, 80)
    sleep(explode_speed)
    pyglow.led(5, 80)
    sleep(explode_speed)
    pyglow.led(16, 90)
    sleep(explode_speed)
    pyglow.led(4, 90)
    # Fade Body 5 - 2
    pyglow.led(18, 60)
    sleep(explode_speed)
    pyglow.led(12, 60)
    sleep(explode_speed)
    pyglow.led(17, 70)
    sleep(explode_speed)
    pyglow.led(5, 70)
    sleep(explode_speed)
    pyglow.led(16, 80)
    sleep(explode_speed)
    pyglow.led(4, 80)
    sleep(explode_speed)
    pyglow.led(15, 90)
    sleep(explode_speed)
    pyglow.led(3, 90)
    # Fade Body 5 - 1
    pyglow.led(18, 50)
    sleep(explode_speed)
    pyglow.led(12, 50)
    sleep(explode_speed)
    pyglow.led(17, 60)
    sleep(explode_speed)
    pyglow.led(5, 60)
    sleep(explode_speed)
    pyglow.led(16, 70)
    sleep(explode_speed)
    pyglow.led(4, 70)
    sleep(explode_speed)
    pyglow.led(15, 80)
    sleep(explode_speed)
    pyglow.led(3, 80)
    sleep(explode_speed)
    pyglow.led(14, 90)
    sleep(explode_speed)
    pyglow.led(2, 90)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 40)
    sleep(explode_speed)
    pyglow.led(12, 40)
    sleep(explode_speed)
    pyglow.led(17, 50)
    sleep(explode_speed)
    pyglow.led(5, 50)
    sleep(explode_speed)
    pyglow.led(16, 60)
    sleep(explode_speed)
    pyglow.led(4, 60)
    sleep(explode_speed)
    pyglow.led(15, 70)
    sleep(explode_speed)
    pyglow.led(3, 70)
    sleep(explode_speed)
    pyglow.led(4, 80)
    sleep(explode_speed)
    pyglow.led(2, 80)
    sleep(explode_speed)
    pyglow.led(3, 90)
    sleep(explode_speed)
    pyglow.led(1, 90)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 30)
    sleep(explode_speed)
    pyglow.led(12, 30)
    sleep(explode_speed)
    pyglow.led(17, 40)
    sleep(explode_speed)
    pyglow.led(5, 40)
    sleep(explode_speed)
    pyglow.led(16, 50)
    sleep(explode_speed)
    pyglow.led(4, 50)
    sleep(explode_speed)
    pyglow.led(15, 60)
    sleep(explode_speed)
    pyglow.led(3, 60)
    sleep(explode_speed)
    pyglow.led(14, 70)
    sleep(explode_speed)
    pyglow.led(2, 70)
    sleep(explode_speed)
    pyglow.led(13, 80)
    sleep(explode_speed)
    pyglow.led(1, 80)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 20)
    sleep(explode_speed)
    pyglow.led(2, 20)
    sleep(explode_speed)
    pyglow.led(17, 30)
    sleep(explode_speed)
    pyglow.led(5, 30)
    sleep(explode_speed)
    pyglow.led(16, 40)
    sleep(explode_speed)
    pyglow.led(4, 40)
    sleep(explode_speed)
    pyglow.led(15, 50)
    sleep(explode_speed)
    pyglow.led(3, 50)
    sleep(explode_speed)
    pyglow.led(14, 60)
    sleep(explode_speed)
    pyglow.led(2, 60)
    sleep(explode_speed)
    pyglow.led(13, 70)
    sleep(explode_speed)
    pyglow.led(1, 70)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 10)
    sleep(explode_speed)
    pyglow.led(12, 10)
    sleep(explode_speed)
    pyglow.led(17, 20)
    sleep(explode_speed)
    pyglow.led(5, 20)
    sleep(explode_speed)
    pyglow.led(16, 30)
    sleep(explode_speed)
    pyglow.led(4, 30)
    sleep(explode_speed)
    pyglow.led(15, 40)
    sleep(explode_speed)
    pyglow.led(3, 40)
    sleep(explode_speed)
    pyglow.led(14, 50)
    sleep(explode_speed)
    pyglow.led(2, 50)
    sleep(explode_speed)
    pyglow.led(3, 60)
    sleep(explode_speed)
    pyglow.led(1, 60)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 0)
    sleep(explode_speed)
    pyglow.led(12, 0)
    sleep(explode_speed)
    pyglow.led(17, 10)
    sleep(explode_speed)
    pyglow.led(5, 10)
    sleep(explode_speed)
    pyglow.led(16, 20)
    sleep(explode_speed)
    pyglow.led(4, 20)
    sleep(explode_speed)
    pyglow.led(15, 30)
    sleep(explode_speed)
    pyglow.led(3, 30)
    sleep(explode_speed)
    pyglow.led(14, 40)
    sleep(explode_speed)
    pyglow.led(2, 40)
    sleep(explode_speed)
    pyglow.led(13, 50)
    sleep(explode_speed)
    pyglow.led(1, 50)
    sleep(explode_speed)
    # Fade Body 4 -1, Head and Tail
    pyglow.led(17, 0)
    sleep(explode_speed)
    pyglow.led(5, 0)
    sleep(explode_speed)
    pyglow.led(16, 10)
    sleep(explode_speed)
    pyglow.led(4, 10)
    sleep(explode_speed)
    pyglow.led(15, 20)
    sleep(explode_speed)
    pyglow.led(3, 20)
    sleep(explode_speed)
    pyglow.led(14, 30)
    sleep(explode_speed)
    pyglow.led(2, 30)
    sleep(explode_speed)
    pyglow.led(13, 40)
    sleep(explode_speed)
    pyglow.led(1, 40)
    sleep(explode_speed)
    # Fade Body 3 -1, Head and Tail
    pyglow.led(16, 0)
    sleep(explode_speed)
    pyglow.led(4, 0)
    sleep(explode_speed)
    pyglow.led(15, 10)
    sleep(explode_speed)
    pyglow.led(3, 10)
    sleep(explode_speed)
    pyglow.led(14, 20)
    sleep(explode_speed)
    pyglow.led(2, 20)
    sleep(explode_speed)
    pyglow.led(13, 30)
    sleep(explode_speed)
    pyglow.led(1, 30)
    sleep(explode_speed)
    # Fade Body 2 - 1, Head and Tail
    pyglow.led(15, 0)
    sleep(explode_speed)
    pyglow.led(3, 0)
    sleep(explode_speed)
    pyglow.led(14, 10)
    sleep(explode_speed)
    pyglow.led(2, 10)
    sleep(explode_speed)
    pyglow.led(13, 20)
    sleep(explode_speed)
    pyglow.led(1, 20)
    sleep(explode_speed)
    # Fade Body 1, Head and Tail
    pyglow.led(14, 0)
    sleep(explode_speed)
    pyglow.led(2, 0)
    sleep(explode_speed)
    pyglow.led(13, 10)
    sleep(explode_speed)
    pyglow.led(1, 10)
    sleep(explode_speed)
    # Fade Head and Tail
    pyglow.led(13, 0)
    sleep(explode_speed)
    pyglow.led(1, 0)
    sleep(explode_speed)
    
def fizzling_snake_23_or_32():
    # Variables
    explode_speed = 0.01
    # Fade Body 5 (on both sides)
    pyglow.led(12, 90)
    sleep(explode_speed)
    pyglow.led(6, 90)
    sleep(explode_speed)
    # Fade Body 5 and 4
    pyglow.led(12, 80)
    sleep(explode_speed)
    pyglow.led(6, 80)
    sleep(explode_speed)
    pyglow.led(17, 90)
    sleep(explode_speed)
    pyglow.led(11, 90)
    # Fade Body 5 - 3
    pyglow.led(12, 70)
    sleep(explode_speed)
    pyglow.led(6, 70)
    sleep(explode_speed)
    pyglow.led(17, 80)
    sleep(explode_speed)
    pyglow.led(11, 80)
    sleep(explode_speed)
    pyglow.led(16, 90)
    sleep(explode_speed)
    pyglow.led(10, 90)
    # Fade Body 5 - 2
    pyglow.led(12, 60)
    sleep(explode_speed)
    pyglow.led(6, 60)
    sleep(explode_speed)
    pyglow.led(17, 70)
    sleep(explode_speed)
    pyglow.led(11, 70)
    sleep(explode_speed)
    pyglow.led(16, 80)
    sleep(explode_speed)
    pyglow.led(10, 80)
    sleep(explode_speed)
    pyglow.led(15, 90)
    sleep(explode_speed)
    pyglow.led(9, 90)
    # Fade Body 5 - 1
    pyglow.led(12, 50)
    sleep(explode_speed)
    pyglow.led(6, 50)
    sleep(explode_speed)
    pyglow.led(17, 60)
    sleep(explode_speed)
    pyglow.led(11, 60)
    sleep(explode_speed)
    pyglow.led(16, 70)
    sleep(explode_speed)
    pyglow.led(10, 70)
    sleep(explode_speed)
    pyglow.led(15, 80)
    sleep(explode_speed)
    pyglow.led(9, 80)
    sleep(explode_speed)
    pyglow.led(14, 90)
    sleep(explode_speed)
    pyglow.led(8, 90)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(12, 40)
    sleep(explode_speed)
    pyglow.led(6, 40)
    sleep(explode_speed)
    pyglow.led(17, 50)
    sleep(explode_speed)
    pyglow.led(11, 50)
    sleep(explode_speed)
    pyglow.led(16, 60)
    sleep(explode_speed)
    pyglow.led(10, 60)
    sleep(explode_speed)
    pyglow.led(15, 70)
    sleep(explode_speed)
    pyglow.led(9, 70)
    sleep(explode_speed)
    pyglow.led(14, 80)
    sleep(explode_speed)
    pyglow.led(8, 80)
    sleep(explode_speed)
    pyglow.led(13, 90)
    sleep(explode_speed)
    pyglow.led(7, 90)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(12, 30)
    sleep(explode_speed)
    pyglow.led(6, 30)
    sleep(explode_speed)
    pyglow.led(17, 40)
    sleep(explode_speed)
    pyglow.led(11, 40)
    sleep(explode_speed)
    pyglow.led(16, 50)
    sleep(explode_speed)
    pyglow.led(10, 50)
    sleep(explode_speed)
    pyglow.led(15, 60)
    sleep(explode_speed)
    pyglow.led(9, 60)
    sleep(explode_speed)
    pyglow.led(14, 70)
    sleep(explode_speed)
    pyglow.led(8, 70)
    sleep(explode_speed)
    pyglow.led(13, 80)
    sleep(explode_speed)
    pyglow.led(7, 80)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(12, 20)
    sleep(explode_speed)
    pyglow.led(6, 20)
    sleep(explode_speed)
    pyglow.led(17, 30)
    sleep(explode_speed)
    pyglow.led(11, 30)
    sleep(explode_speed)
    pyglow.led(16, 40)
    sleep(explode_speed)
    pyglow.led(10, 40)
    sleep(explode_speed)
    pyglow.led(15, 50)
    sleep(explode_speed)
    pyglow.led(9, 50)
    sleep(explode_speed)
    pyglow.led(14, 60)
    sleep(explode_speed)
    pyglow.led(8, 60)
    sleep(explode_speed)
    pyglow.led(13, 70)
    sleep(explode_speed)
    pyglow.led(7, 70)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(12, 10)
    sleep(explode_speed)
    pyglow.led(6, 10)
    sleep(explode_speed)
    pyglow.led(17, 20)
    sleep(explode_speed)
    pyglow.led(11, 20)
    sleep(explode_speed)
    pyglow.led(16, 30)
    sleep(explode_speed)
    pyglow.led(10, 30)
    sleep(explode_speed)
    pyglow.led(15, 40)
    sleep(explode_speed)
    pyglow.led(9, 40)
    sleep(explode_speed)
    pyglow.led(14, 50)
    sleep(explode_speed)
    pyglow.led(8, 50)
    sleep(explode_speed)
    pyglow.led(13, 60)
    sleep(explode_speed)
    pyglow.led(7, 60)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(12, 0)
    sleep(explode_speed)
    pyglow.led(6, 0)
    sleep(explode_speed)
    pyglow.led(17, 10)
    sleep(explode_speed)
    pyglow.led(11, 10)
    sleep(explode_speed)
    pyglow.led(16, 20)
    sleep(explode_speed)
    pyglow.led(10, 20)
    sleep(explode_speed)
    pyglow.led(15, 30)
    sleep(explode_speed)
    pyglow.led(9, 30)
    sleep(explode_speed)
    pyglow.led(14, 40)
    sleep(explode_speed)
    pyglow.led(8, 40)
    sleep(explode_speed)
    pyglow.led(13, 50)
    sleep(explode_speed)
    pyglow.led(7, 50)
    sleep(explode_speed)
    # Fade Body 4 -1, Head and Tail
    pyglow.led(17, 0)
    sleep(explode_speed)
    pyglow.led(11, 0)
    sleep(explode_speed)
    pyglow.led(16, 10)
    sleep(explode_speed)
    pyglow.led(10, 10)
    sleep(explode_speed)
    pyglow.led(15, 20)
    sleep(explode_speed)
    pyglow.led(9, 20)
    sleep(explode_speed)
    pyglow.led(14, 30)
    sleep(explode_speed)
    pyglow.led(8, 30)
    sleep(explode_speed)
    pyglow.led(13, 40)
    sleep(explode_speed)
    pyglow.led(7, 40)
    sleep(explode_speed)
    # Fade Body 3 -1, Head and Tail
    pyglow.led(16, 0)
    sleep(explode_speed)
    pyglow.led(10, 0)
    sleep(explode_speed)
    pyglow.led(15, 10)
    sleep(explode_speed)
    pyglow.led(9, 10)
    sleep(explode_speed)
    pyglow.led(14, 20)
    sleep(explode_speed)
    pyglow.led(8, 20)
    sleep(explode_speed)
    pyglow.led(13, 30)
    sleep(explode_speed)
    pyglow.led(7, 30)
    sleep(explode_speed)
    # Fade Body 2 - 1, Head and Tail
    pyglow.led(15, 0)
    sleep(explode_speed)
    pyglow.led(9, 0)
    sleep(explode_speed)
    pyglow.led(14, 10)
    sleep(explode_speed)
    pyglow.led(8, 10)
    sleep(explode_speed)
    pyglow.led(13, 20)
    sleep(explode_speed)
    pyglow.led(7, 20)
    sleep(explode_speed)
    # Fade Body 1, Head and Tail
    pyglow.led(14, 0)
    sleep(explode_speed)
    pyglow.led(8, 0)
    sleep(explode_speed)
    pyglow.led(13, 10)
    sleep(explode_speed)
    pyglow.led(7, 10)
    sleep(explode_speed)
    # Fade Head and Tail
    pyglow.led(13, 0)
    sleep(explode_speed)
    pyglow.led(7, 0)
    sleep(explode_speed)
    
# List of all snake functions
snake_functions = [snake_12, snake_13, snake_23, fading_snake_12, fading_snake_13, fading_snake_23,
                   slithering_snake_12, slithering_snake_13, slithering_snake_21, slithering_snake_23,
                   slithering_snake_31, slithering_snake_32, slithering_fading_snake_12,
                   slithering_fading_snake_13, slithering_fading_snake_21, slithering_fading_snake_23,
                   slithering_fading_snake_31, slithering_fading_snake_32, pulsing_snake_12,
                   pulsing_snake_13, pulsing_snake_23, exploding_snake_12, exploding_snake_13,
                   exploding_snake_23, slithering_exploding_snake_12,slithering_exploding_snake_13,
                   slithering_exploding_snake_21, slithering_exploding_snake_23,
                   slithering_exploding_snake_31, slithering_exploding_snake_32,
                   slithering_fizzling_fading_snake_12, slithering_fizzling_fading_snake_13,
                   slithering_fizzling_fading_snake_21, slithering_fizzling_fading_snake_23,
                   slithering_fizzling_fading_snake_31, slithering_fizzling_fading_snake_32]

# Start the program
# Life is like a can of random snakes. You never know what your'e going to get.
try:
    while True:
        random.choice(snake_functions)()
# Stop the program and turn off LEDs with Ctrl-C
except KeyboardInterrupt:
    pyglow.all()
