################################################################
#                      Slithering Snakes                       #
################################################################
# Description:                                                 #
# The title explains it.                                       #
#                                                              #
# Requirements: PyGlow.py                                      #
#                                                              #
# Author: Paul Ryan                                            #
#                                                              #
################################################################

from PyGlow import PyGlow
from time import sleep

pyglow = PyGlow()

# Initialize
pyglow.all(0)

# Variables
sleep_speed = 0.10

# Functions
def slithering_snake_12():
    # Light up Snake 12 
    pyglow.led(1, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(7, 100)
    sleep(sleep_speed)
    # Turn off Snake 12 
    pyglow.led(1, 0)
    sleep(sleep_speed)
    pyglow.led(2, 0)
    sleep(sleep_speed)
    pyglow.led(3, 0)
    sleep(sleep_speed)
    pyglow.led(4, 0)
    sleep(sleep_speed)
    pyglow.led(5, 0)
    sleep(sleep_speed)
    pyglow.led(6, 0)
    sleep(sleep_speed)
    pyglow.led(18, 0)
    sleep(sleep_speed)
    pyglow.led(11, 0)
    sleep(sleep_speed)
    pyglow.led(10, 0)
    sleep(sleep_speed)
    pyglow.led(9, 0)
    sleep(sleep_speed)
    pyglow.led(8, 0)
    sleep(sleep_speed)
    pyglow.led(7, 0)
    sleep(sleep_speed)

def slithering_snake_13():
    # Light up Snake 13
    pyglow.led(1, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(13, 100)
    sleep(sleep_speed)
    # Turn off Snake 13 
    pyglow.led(1, 0)
    sleep(sleep_speed)
    pyglow.led(2, 0)
    sleep(sleep_speed)
    pyglow.led(3, 0)
    sleep(sleep_speed)
    pyglow.led(4, 0)
    sleep(sleep_speed)
    pyglow.led(5, 0)
    sleep(sleep_speed)
    pyglow.led(18, 0)
    sleep(sleep_speed)
    pyglow.led(12, 0)
    sleep(sleep_speed)
    pyglow.led(17, 0)
    sleep(sleep_speed)
    pyglow.led(16, 0)
    sleep(sleep_speed)
    pyglow.led(15, 0)
    sleep(sleep_speed)
    pyglow.led(14, 0)
    sleep(sleep_speed)
    pyglow.led(13, 0)
    sleep(sleep_speed)

def slithering_snake_21():
    # Light up Snake 21
    pyglow.led(7, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(1, 100)
    sleep(sleep_speed)
    # Turn off Snake 21
    pyglow.led(7, 0)
    sleep(sleep_speed)
    pyglow.led(8, 0)
    sleep(sleep_speed)
    pyglow.led(9, 0)
    sleep(sleep_speed)
    pyglow.led(10, 0)
    sleep(sleep_speed)
    pyglow.led(11, 0)
    sleep(sleep_speed)
    pyglow.led(18, 0)
    sleep(sleep_speed)
    pyglow.led(6, 0)
    sleep(sleep_speed)
    pyglow.led(5, 0)
    sleep(sleep_speed)
    pyglow.led(4, 0)
    sleep(sleep_speed)
    pyglow.led(3, 0)
    sleep(sleep_speed)
    pyglow.led(2, 0)
    sleep(sleep_speed)
    pyglow.led(1, 0)
    sleep(sleep_speed)

def slithering_snake_23():
    # Light up Snake 23
    pyglow.led(7, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(13, 100)
    sleep(sleep_speed)
    # Turn off Snake 23 
    pyglow.led(7, 0)
    sleep(sleep_speed)
    pyglow.led(8, 0)
    sleep(sleep_speed)
    pyglow.led(9, 0)
    sleep(sleep_speed)
    pyglow.led(10, 0)
    sleep(sleep_speed)
    pyglow.led(11, 0)
    sleep(sleep_speed)
    pyglow.led(12, 0)
    sleep(sleep_speed)
    pyglow.led(6, 0)
    sleep(sleep_speed)
    pyglow.led(17, 0)
    sleep(sleep_speed)
    pyglow.led(16, 0)
    sleep(sleep_speed)
    pyglow.led(15, 0)
    sleep(sleep_speed)
    pyglow.led(14, 0)
    sleep(sleep_speed)
    pyglow.led(13, 0)
    sleep(sleep_speed)

def slithering_snake_31():
    # Light up Snake 31
    pyglow.led(13, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(1, 100)
    sleep(sleep_speed)
    # Turn off Snake 31
    pyglow.led(13, 0)
    sleep(sleep_speed)
    pyglow.led(14, 0)
    sleep(sleep_speed)
    pyglow.led(15, 0)
    sleep(sleep_speed)
    pyglow.led(16, 0)
    sleep(sleep_speed)
    pyglow.led(17, 0)
    sleep(sleep_speed)
    pyglow.led(18, 0)
    sleep(sleep_speed)
    pyglow.led(12, 0)
    sleep(sleep_speed)
    pyglow.led(5, 0)
    sleep(sleep_speed)
    pyglow.led(4, 0)
    sleep(sleep_speed)
    pyglow.led(3, 0)
    sleep(sleep_speed)
    pyglow.led(2, 0)
    sleep(sleep_speed)
    pyglow.led(1, 0)
    sleep(sleep_speed)

def slithering_snake_32():
    # Light up Snake 32 
    pyglow.led(13, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(7, 100)
    sleep(sleep_speed)
    # Turn off Snake 32 
    pyglow.led(13, 0)
    sleep(sleep_speed)
    pyglow.led(14, 0)
    sleep(sleep_speed)
    pyglow.led(15, 0)
    sleep(sleep_speed)
    pyglow.led(16, 0)
    sleep(sleep_speed)
    pyglow.led(17, 0)
    sleep(sleep_speed)
    pyglow.led(6, 0)
    sleep(sleep_speed)
    pyglow.led(12, 0)
    sleep(sleep_speed)
    pyglow.led(11, 0)
    sleep(sleep_speed)
    pyglow.led(10, 0)
    sleep(sleep_speed)
    pyglow.led(9, 0)
    sleep(sleep_speed)
    pyglow.led(8, 0)
    sleep(sleep_speed)
    pyglow.led(7, 0)
    sleep(sleep_speed)

# Start the program
try:
    while True:
        # Snakes 12, 13, 21, 23, 31, 32
        slithering_snake_12()
        sleep(1)
        slithering_snake_13()
        sleep(1)
        slithering_snake_21()
        sleep(1)
        slithering_snake_23()
        sleep(1)
        slithering_snake_31()
        sleep(1)
        slithering_snake_32()
        sleep(1)
        # Snakes 12, 23, 31, 13, 32, 21
        slithering_snake_12()
        sleep(1)
        slithering_snake_23()
        sleep(1)
        slithering_snake_31()
        sleep(1)
        slithering_snake_13()
        sleep(1)
        slithering_snake_32()
        sleep(1)
        slithering_snake_21()
        sleep(1)
        # Snakes 13, 12, 23, 21, 31, 32
        slithering_snake_13()
        sleep(1)
        slithering_snake_12()
        sleep(1)
        slithering_snake_23()
        sleep(1)
        slithering_snake_21()
        sleep(1)
        slithering_snake_31()
        sleep(1)
        slithering_snake_32()
        sleep(1)
        # Snakes 13, 32, 21, 12, 23, 31
        slithering_snake_13()
        sleep(1)
        slithering_snake_32()
        sleep(1)
        slithering_snake_21()
        sleep(1)
        slithering_snake_12()
        sleep(1)
        slithering_snake_23()
        sleep(1)
        slithering_snake_31()
        sleep(1)
# Stop the program and turn off LEDs with Ctrl-C
except KeyboardInterrupt:
    pyglow.all()
