################################################################
#       Slithering Exploding (Fizzling) Fading Snakes          #
################################################################
# Description:                                                 #
# OK, so they don't really explode - more like fizzle.         #
# I was just playing off a theme in my snake series of         #
# programs, and the result wasn't quite what I was expecting.  #
#                                                              #
# Requirements: PyGlow.py                                      #
#                                                              #
# Author: Paul Ryan                                            #
#                                                              #
################################################################

from PyGlow import PyGlow
from time import sleep

pyglow = PyGlow()

# Initialize
pyglow.all(0)

# Variables
sleep_speed = 0.10

# Lists
# LEDs for snakes 12 and 21
snake_12_leds = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 18]
# LEDs for snakes 13 and 31
snake_13_leds = [1, 2, 3, 4, 5, 12, 13, 14, 15, 16, 17, 18]
# LEDs for snakes 23 and 32
snake_23_leds = [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

# Functions
def slithering_exploding_snake_12():
    # Light up Snake 12
    '''' Uncomment the following line for feedback '''
    #print "Snake 12 is slithering..."
    pyglow.led(1, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(7, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_12_or_21()
    # Explode Snake 12
    '''' Uncomment the following line for feedback '''
    #print "Snake 12 is exploding..."
    explode_snake_12_or_21()

def slithering_exploding_snake_13():
    # Light up Snake 13
    '''' Uncomment the following line for feedback '''
    #print "Snake 13 is slithering..."
    pyglow.led(1, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(13, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_13_or_31()
    # Explode Snake 13
    '''' Uncomment the following line for feedback '''
    #print "Snake 13 is exploding..."
    explode_snake_13_or_31()

def slithering_exploding_snake_21():
    # Light up Snake 21
    '''' Uncomment the following line for feedback '''
    #print "Snake 21 is slithering..."
    pyglow.led(7, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(1, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_12_or_21()
    # Explode Snake 21
    '''' Uncomment the following line for feedback '''
    #print "Snake 21 is exploding..."
    explode_snake_12_or_21()

def slithering_exploding_snake_23():
    # Light up Snake 23
    '''' Uncomment the following line for feedback '''
    #print "Snake 23 is slithering..."
    pyglow.led(7, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(13, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_23_or_32()
    # Explode Snake 23
    '''' Uncomment the following line for feedback '''
    #print "Snake 23 is exploding..."
    explode_snake_23_or_32()
    
def slithering_exploding_snake_31():
    # Light up Snake 31
    '''' Uncomment the following line for feedback '''
    #print "Snake 31 is slithering..."
    pyglow.led(13, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(18, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(5, 100)
    sleep(sleep_speed)
    pyglow.led(4, 100)
    sleep(sleep_speed)
    pyglow.led(3, 100)
    sleep(sleep_speed)
    pyglow.led(2, 100)
    sleep(sleep_speed)
    pyglow.led(1, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_13_or_31()
    # Explode Snake 31
    '''' Uncomment the following line for feedback '''
    #print "Snake 31 is exploding..."
    explode_snake_13_or_31()

def slithering_exploding_snake_32():
    # Light up Snake 32
    '''' Uncomment the following line for feedback '''
    #print "Snake 32 is slithering..." 
    pyglow.led(13, 100)
    sleep(sleep_speed)
    pyglow.led(14, 100)
    sleep(sleep_speed)
    pyglow.led(15, 100)
    sleep(sleep_speed)
    pyglow.led(16, 100)
    sleep(sleep_speed)
    pyglow.led(17, 100)
    sleep(sleep_speed)
    pyglow.led(6, 100)
    sleep(sleep_speed)
    pyglow.led(12, 100)
    sleep(sleep_speed)
    pyglow.led(11, 100)
    sleep(sleep_speed)
    pyglow.led(10, 100)
    sleep(sleep_speed)
    pyglow.led(9, 100)
    sleep(sleep_speed)
    pyglow.led(8, 100)
    sleep(sleep_speed)
    pyglow.led(7, 100)
    sleep(sleep_speed)
    # Pulse
    pulse_snake_23_or_32()
    # Explode Snake 32
    '''' Uncomment the following line for feedback '''
    #print "Snake 32 is slithering..."
    explode_snake_23_or_32()
    
def pulse_snake_12_or_21():
    # Variable
    pulse_speed = 175
    ''' Uncomment the following print statement for feedback '''
    #print "Snake is pulsing."
    while pulse_speed < 225:
        ''' Uncomment the following print statement for feedback '''
        #print "Pulse speed is: ", pulse_speed
    	pyglow.led(snake_12_leds, 100, speed = pulse_speed, pulse = True)
    	sleep(0)
    	pyglow.update_leds()
        pulse_speed += 1
    pyglow.led(snake_12_leds, 100)
    sleep(1)

def pulse_snake_13_or_31():
    # Variable
    pulse_speed = 175
    ''' Uncomment the following print statement for feedback '''
    #print "Snake is pulsing."
    while pulse_speed < 225:
        ''' Uncomment the following print statement for feedback '''
        #print "Pulse speed is: ", pulse_speed
    	pyglow.led(snake_13_leds, 100, speed = pulse_speed, pulse = True)
    	sleep(0)
    	pyglow.update_leds()
        pulse_speed += 1
    pyglow.led(snake_13_leds, 100)
    sleep(1)

def pulse_snake_23_or_32():
    # Variable
    pulse_speed = 175
    ''' Uncomment the following print statement for feedback '''
    #print "Snake is pulsing."
    while pulse_speed < 225:
        ''' Uncomment the following print statement for feedback '''
        #print "Pulse speed is: ", pulse_speed
    	pyglow.led(snake_23_leds, 100, speed = pulse_speed, pulse = True)
    	sleep(0)
    	pyglow.update_leds()
        pulse_speed += 1
    pyglow.led(snake_23_leds, 100)
    sleep(1)

def explode_snake_12_or_21():
    # Variables
    explode_speed = 0.01
    # Fade Body 5 (on both sides)
    pyglow.led(18, 90)
    sleep(explode_speed)
    pyglow.led(6, 90)
    sleep(explode_speed)
    # Fade Body 5 and 4
    pyglow.led(18, 80)
    sleep(explode_speed)
    pyglow.led(6, 80)
    sleep(explode_speed)
    pyglow.led(11, 90)
    sleep(explode_speed)
    pyglow.led(5, 90)
    # Fade Body 5 - 3
    pyglow.led(18, 70)
    sleep(explode_speed)
    pyglow.led(6, 70)
    sleep(explode_speed)
    pyglow.led(11, 80)
    sleep(explode_speed)
    pyglow.led(5, 80)
    sleep(explode_speed)
    pyglow.led(10, 90)
    sleep(explode_speed)
    pyglow.led(4, 90)
    # Fade Body 5 - 2
    pyglow.led(18, 60)
    sleep(explode_speed)
    pyglow.led(6, 60)
    sleep(explode_speed)
    pyglow.led(11, 70)
    sleep(explode_speed)
    pyglow.led(5, 70)
    sleep(explode_speed)
    pyglow.led(10, 80)
    sleep(explode_speed)
    pyglow.led(4, 80)
    sleep(explode_speed)
    pyglow.led(9, 90)
    sleep(explode_speed)
    pyglow.led(3, 90)
    # Fade Body 5 - 1
    pyglow.led(18, 50)
    sleep(explode_speed)
    pyglow.led(6, 50)
    sleep(explode_speed)
    pyglow.led(11, 60)
    sleep(explode_speed)
    pyglow.led(5, 60)
    sleep(explode_speed)
    pyglow.led(10, 70)
    sleep(explode_speed)
    pyglow.led(4, 70)
    sleep(explode_speed)
    pyglow.led(9, 80)
    sleep(explode_speed)
    pyglow.led(3, 80)
    sleep(explode_speed)
    pyglow.led(8, 90)
    sleep(explode_speed)
    pyglow.led(2, 90)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 40)
    sleep(explode_speed)
    pyglow.led(6, 40)
    sleep(explode_speed)
    pyglow.led(11, 50)
    sleep(explode_speed)
    pyglow.led(5, 50)
    sleep(explode_speed)
    pyglow.led(10, 60)
    sleep(explode_speed)
    pyglow.led(4, 60)
    sleep(explode_speed)
    pyglow.led(9, 70)
    sleep(explode_speed)
    pyglow.led(3, 70)
    sleep(explode_speed)
    pyglow.led(8, 80)
    sleep(explode_speed)
    pyglow.led(2, 80)
    sleep(explode_speed)
    pyglow.led(7, 90)
    sleep(explode_speed)
    pyglow.led(1, 90)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 30)
    sleep(explode_speed)
    pyglow.led(6, 30)
    sleep(explode_speed)
    pyglow.led(11, 40)
    sleep(explode_speed)
    pyglow.led(5, 40)
    sleep(explode_speed)
    pyglow.led(10, 50)
    sleep(explode_speed)
    pyglow.led(4, 50)
    sleep(explode_speed)
    pyglow.led(9, 60)
    sleep(explode_speed)
    pyglow.led(3, 60)
    sleep(explode_speed)
    pyglow.led(8, 70)
    sleep(explode_speed)
    pyglow.led(2, 70)
    sleep(explode_speed)
    pyglow.led(7, 80)
    sleep(explode_speed)
    pyglow.led(1, 80)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 20)
    sleep(explode_speed)
    pyglow.led(6, 20)
    sleep(explode_speed)
    pyglow.led(11, 30)
    sleep(explode_speed)
    pyglow.led(5, 30)
    sleep(explode_speed)
    pyglow.led(10, 40)
    sleep(explode_speed)
    pyglow.led(4, 40)
    sleep(explode_speed)
    pyglow.led(9, 50)
    sleep(explode_speed)
    pyglow.led(3, 50)
    sleep(explode_speed)
    pyglow.led(8, 60)
    sleep(explode_speed)
    pyglow.led(2, 60)
    sleep(explode_speed)
    pyglow.led(7, 70)
    sleep(explode_speed)
    pyglow.led(1, 70)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 10)
    sleep(explode_speed)
    pyglow.led(6, 10)
    sleep(explode_speed)
    pyglow.led(11, 20)
    sleep(explode_speed)
    pyglow.led(5, 20)
    sleep(explode_speed)
    pyglow.led(10, 30)
    sleep(explode_speed)
    pyglow.led(4, 30)
    sleep(explode_speed)
    pyglow.led(9, 40)
    sleep(explode_speed)
    pyglow.led(3, 40)
    sleep(explode_speed)
    pyglow.led(8, 50)
    sleep(explode_speed)
    pyglow.led(2, 50)
    sleep(explode_speed)
    pyglow.led(7, 60)
    sleep(explode_speed)
    pyglow.led(1, 60)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 0)
    sleep(explode_speed)
    pyglow.led(6, 0)
    sleep(explode_speed)
    pyglow.led(11, 10)
    sleep(explode_speed)
    pyglow.led(5, 10)
    sleep(explode_speed)
    pyglow.led(10, 20)
    sleep(explode_speed)
    pyglow.led(4, 20)
    sleep(explode_speed)
    pyglow.led(9, 30)
    sleep(explode_speed)
    pyglow.led(3, 30)
    sleep(explode_speed)
    pyglow.led(8, 40)
    sleep(explode_speed)
    pyglow.led(2, 40)
    sleep(explode_speed)
    pyglow.led(7, 50)
    sleep(explode_speed)
    pyglow.led(1, 50)
    sleep(explode_speed)
    # Fade Body 4 -1, Head and Tail
    pyglow.led(11, 0)
    sleep(explode_speed)
    pyglow.led(5, 0)
    sleep(explode_speed)
    pyglow.led(10, 10)
    sleep(explode_speed)
    pyglow.led(4, 10)
    sleep(explode_speed)
    pyglow.led(9, 20)
    sleep(explode_speed)
    pyglow.led(3, 20)
    sleep(explode_speed)
    pyglow.led(8, 30)
    sleep(explode_speed)
    pyglow.led(2, 30)
    sleep(explode_speed)
    pyglow.led(7, 40)
    sleep(explode_speed)
    pyglow.led(1, 40)
    sleep(explode_speed)
    # Fade Body 3 -1, Head and Tail
    pyglow.led(10, 0)
    sleep(explode_speed)
    pyglow.led(4, 0)
    sleep(explode_speed)
    pyglow.led(9, 10)
    sleep(explode_speed)
    pyglow.led(3, 10)
    sleep(explode_speed)
    pyglow.led(8, 20)
    sleep(explode_speed)
    pyglow.led(2, 20)
    sleep(explode_speed)
    pyglow.led(7, 30)
    sleep(explode_speed)
    pyglow.led(1, 30)
    sleep(explode_speed)
    # Fade Body 2 - 1, Head and Tail
    pyglow.led(9, 0)
    sleep(explode_speed)
    pyglow.led(3, 0)
    sleep(explode_speed)
    pyglow.led(8, 10)
    sleep(explode_speed)
    pyglow.led(2, 10)
    sleep(explode_speed)
    pyglow.led(7, 20)
    sleep(explode_speed)
    pyglow.led(1, 20)
    sleep(explode_speed)
    # Fade Body 1, Head and Tail
    pyglow.led(8, 0)
    sleep(explode_speed)
    pyglow.led(2, 0)
    sleep(explode_speed)
    pyglow.led(7, 10)
    sleep(explode_speed)
    pyglow.led(1, 10)
    sleep(explode_speed)
    # Fade Head and Tail
    pyglow.led(7, 0)
    sleep(explode_speed)
    pyglow.led(1, 0)
    sleep(explode_speed)

def explode_snake_13_or_31():
    # Variables
    explode_speed = 0.01
    # Fade Body 5 (on both sides)
    pyglow.led(18, 90)
    sleep(explode_speed)
    pyglow.led(12, 90)
    sleep(explode_speed)
    # Fade Body 5 and 4
    pyglow.led(18, 80)
    sleep(explode_speed)
    pyglow.led(12, 80)
    sleep(explode_speed)
    pyglow.led(17, 90)
    sleep(explode_speed)
    pyglow.led(5, 90)
    # Fade Body 5 - 3
    pyglow.led(18, 70)
    sleep(explode_speed)
    pyglow.led(12, 70)
    sleep(explode_speed)
    pyglow.led(17, 80)
    sleep(explode_speed)
    pyglow.led(5, 80)
    sleep(explode_speed)
    pyglow.led(16, 90)
    sleep(explode_speed)
    pyglow.led(4, 90)
    # Fade Body 5 - 2
    pyglow.led(18, 60)
    sleep(explode_speed)
    pyglow.led(12, 60)
    sleep(explode_speed)
    pyglow.led(17, 70)
    sleep(explode_speed)
    pyglow.led(5, 70)
    sleep(explode_speed)
    pyglow.led(16, 80)
    sleep(explode_speed)
    pyglow.led(4, 80)
    sleep(explode_speed)
    pyglow.led(15, 90)
    sleep(explode_speed)
    pyglow.led(3, 90)
    # Fade Body 5 - 1
    pyglow.led(18, 50)
    sleep(explode_speed)
    pyglow.led(12, 50)
    sleep(explode_speed)
    pyglow.led(17, 60)
    sleep(explode_speed)
    pyglow.led(5, 60)
    sleep(explode_speed)
    pyglow.led(16, 70)
    sleep(explode_speed)
    pyglow.led(4, 70)
    sleep(explode_speed)
    pyglow.led(15, 80)
    sleep(explode_speed)
    pyglow.led(3, 80)
    sleep(explode_speed)
    pyglow.led(14, 90)
    sleep(explode_speed)
    pyglow.led(2, 90)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 40)
    sleep(explode_speed)
    pyglow.led(12, 40)
    sleep(explode_speed)
    pyglow.led(17, 50)
    sleep(explode_speed)
    pyglow.led(5, 50)
    sleep(explode_speed)
    pyglow.led(16, 60)
    sleep(explode_speed)
    pyglow.led(4, 60)
    sleep(explode_speed)
    pyglow.led(15, 70)
    sleep(explode_speed)
    pyglow.led(3, 70)
    sleep(explode_speed)
    pyglow.led(4, 80)
    sleep(explode_speed)
    pyglow.led(2, 80)
    sleep(explode_speed)
    pyglow.led(3, 90)
    sleep(explode_speed)
    pyglow.led(1, 90)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 30)
    sleep(explode_speed)
    pyglow.led(12, 30)
    sleep(explode_speed)
    pyglow.led(17, 40)
    sleep(explode_speed)
    pyglow.led(5, 40)
    sleep(explode_speed)
    pyglow.led(16, 50)
    sleep(explode_speed)
    pyglow.led(4, 50)
    sleep(explode_speed)
    pyglow.led(15, 60)
    sleep(explode_speed)
    pyglow.led(3, 60)
    sleep(explode_speed)
    pyglow.led(14, 70)
    sleep(explode_speed)
    pyglow.led(2, 70)
    sleep(explode_speed)
    pyglow.led(13, 80)
    sleep(explode_speed)
    pyglow.led(1, 80)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 20)
    sleep(explode_speed)
    pyglow.led(2, 20)
    sleep(explode_speed)
    pyglow.led(17, 30)
    sleep(explode_speed)
    pyglow.led(5, 30)
    sleep(explode_speed)
    pyglow.led(16, 40)
    sleep(explode_speed)
    pyglow.led(4, 40)
    sleep(explode_speed)
    pyglow.led(15, 50)
    sleep(explode_speed)
    pyglow.led(3, 50)
    sleep(explode_speed)
    pyglow.led(14, 60)
    sleep(explode_speed)
    pyglow.led(2, 60)
    sleep(explode_speed)
    pyglow.led(13, 70)
    sleep(explode_speed)
    pyglow.led(1, 70)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 10)
    sleep(explode_speed)
    pyglow.led(12, 10)
    sleep(explode_speed)
    pyglow.led(17, 20)
    sleep(explode_speed)
    pyglow.led(5, 20)
    sleep(explode_speed)
    pyglow.led(16, 30)
    sleep(explode_speed)
    pyglow.led(4, 30)
    sleep(explode_speed)
    pyglow.led(15, 40)
    sleep(explode_speed)
    pyglow.led(3, 40)
    sleep(explode_speed)
    pyglow.led(14, 50)
    sleep(explode_speed)
    pyglow.led(2, 50)
    sleep(explode_speed)
    pyglow.led(3, 60)
    sleep(explode_speed)
    pyglow.led(1, 60)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(18, 0)
    sleep(explode_speed)
    pyglow.led(12, 0)
    sleep(explode_speed)
    pyglow.led(17, 10)
    sleep(explode_speed)
    pyglow.led(5, 10)
    sleep(explode_speed)
    pyglow.led(16, 20)
    sleep(explode_speed)
    pyglow.led(4, 20)
    sleep(explode_speed)
    pyglow.led(15, 30)
    sleep(explode_speed)
    pyglow.led(3, 30)
    sleep(explode_speed)
    pyglow.led(14, 40)
    sleep(explode_speed)
    pyglow.led(2, 40)
    sleep(explode_speed)
    pyglow.led(13, 50)
    sleep(explode_speed)
    pyglow.led(1, 50)
    sleep(explode_speed)
    # Fade Body 4 -1, Head and Tail
    pyglow.led(17, 0)
    sleep(explode_speed)
    pyglow.led(5, 0)
    sleep(explode_speed)
    pyglow.led(16, 10)
    sleep(explode_speed)
    pyglow.led(4, 10)
    sleep(explode_speed)
    pyglow.led(15, 20)
    sleep(explode_speed)
    pyglow.led(3, 20)
    sleep(explode_speed)
    pyglow.led(14, 30)
    sleep(explode_speed)
    pyglow.led(2, 30)
    sleep(explode_speed)
    pyglow.led(13, 40)
    sleep(explode_speed)
    pyglow.led(1, 40)
    sleep(explode_speed)
    # Fade Body 3 -1, Head and Tail
    pyglow.led(16, 0)
    sleep(explode_speed)
    pyglow.led(4, 0)
    sleep(explode_speed)
    pyglow.led(15, 10)
    sleep(explode_speed)
    pyglow.led(3, 10)
    sleep(explode_speed)
    pyglow.led(14, 20)
    sleep(explode_speed)
    pyglow.led(2, 20)
    sleep(explode_speed)
    pyglow.led(13, 30)
    sleep(explode_speed)
    pyglow.led(1, 30)
    sleep(explode_speed)
    # Fade Body 2 - 1, Head and Tail
    pyglow.led(15, 0)
    sleep(explode_speed)
    pyglow.led(3, 0)
    sleep(explode_speed)
    pyglow.led(14, 10)
    sleep(explode_speed)
    pyglow.led(2, 10)
    sleep(explode_speed)
    pyglow.led(13, 20)
    sleep(explode_speed)
    pyglow.led(1, 20)
    sleep(explode_speed)
    # Fade Body 1, Head and Tail
    pyglow.led(14, 0)
    sleep(explode_speed)
    pyglow.led(2, 0)
    sleep(explode_speed)
    pyglow.led(13, 10)
    sleep(explode_speed)
    pyglow.led(1, 10)
    sleep(explode_speed)
    # Fade Head and Tail
    pyglow.led(13, 0)
    sleep(explode_speed)
    pyglow.led(1, 0)
    sleep(explode_speed)
    
def explode_snake_23_or_32():
    # Variables
    explode_speed = 0.01
    # Fade Body 5 (on both sides)
    pyglow.led(12, 90)
    sleep(explode_speed)
    pyglow.led(6, 90)
    sleep(explode_speed)
    # Fade Body 5 and 4
    pyglow.led(12, 80)
    sleep(explode_speed)
    pyglow.led(6, 80)
    sleep(explode_speed)
    pyglow.led(17, 90)
    sleep(explode_speed)
    pyglow.led(11, 90)
    # Fade Body 5 - 3
    pyglow.led(12, 70)
    sleep(explode_speed)
    pyglow.led(6, 70)
    sleep(explode_speed)
    pyglow.led(17, 80)
    sleep(explode_speed)
    pyglow.led(11, 80)
    sleep(explode_speed)
    pyglow.led(16, 90)
    sleep(explode_speed)
    pyglow.led(10, 90)
    # Fade Body 5 - 2
    pyglow.led(12, 60)
    sleep(explode_speed)
    pyglow.led(6, 60)
    sleep(explode_speed)
    pyglow.led(17, 70)
    sleep(explode_speed)
    pyglow.led(11, 70)
    sleep(explode_speed)
    pyglow.led(16, 80)
    sleep(explode_speed)
    pyglow.led(10, 80)
    sleep(explode_speed)
    pyglow.led(15, 90)
    sleep(explode_speed)
    pyglow.led(9, 90)
    # Fade Body 5 - 1
    pyglow.led(12, 50)
    sleep(explode_speed)
    pyglow.led(6, 50)
    sleep(explode_speed)
    pyglow.led(17, 60)
    sleep(explode_speed)
    pyglow.led(11, 60)
    sleep(explode_speed)
    pyglow.led(16, 70)
    sleep(explode_speed)
    pyglow.led(10, 70)
    sleep(explode_speed)
    pyglow.led(15, 80)
    sleep(explode_speed)
    pyglow.led(9, 80)
    sleep(explode_speed)
    pyglow.led(14, 90)
    sleep(explode_speed)
    pyglow.led(8, 90)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(12, 40)
    sleep(explode_speed)
    pyglow.led(6, 40)
    sleep(explode_speed)
    pyglow.led(17, 50)
    sleep(explode_speed)
    pyglow.led(11, 50)
    sleep(explode_speed)
    pyglow.led(16, 60)
    sleep(explode_speed)
    pyglow.led(10, 60)
    sleep(explode_speed)
    pyglow.led(15, 70)
    sleep(explode_speed)
    pyglow.led(9, 70)
    sleep(explode_speed)
    pyglow.led(14, 80)
    sleep(explode_speed)
    pyglow.led(8, 80)
    sleep(explode_speed)
    pyglow.led(13, 90)
    sleep(explode_speed)
    pyglow.led(7, 90)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(12, 30)
    sleep(explode_speed)
    pyglow.led(6, 30)
    sleep(explode_speed)
    pyglow.led(17, 40)
    sleep(explode_speed)
    pyglow.led(11, 40)
    sleep(explode_speed)
    pyglow.led(16, 50)
    sleep(explode_speed)
    pyglow.led(10, 50)
    sleep(explode_speed)
    pyglow.led(15, 60)
    sleep(explode_speed)
    pyglow.led(9, 60)
    sleep(explode_speed)
    pyglow.led(14, 70)
    sleep(explode_speed)
    pyglow.led(8, 70)
    sleep(explode_speed)
    pyglow.led(13, 80)
    sleep(explode_speed)
    pyglow.led(7, 80)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(12, 20)
    sleep(explode_speed)
    pyglow.led(6, 20)
    sleep(explode_speed)
    pyglow.led(17, 30)
    sleep(explode_speed)
    pyglow.led(11, 30)
    sleep(explode_speed)
    pyglow.led(16, 40)
    sleep(explode_speed)
    pyglow.led(10, 40)
    sleep(explode_speed)
    pyglow.led(15, 50)
    sleep(explode_speed)
    pyglow.led(9, 50)
    sleep(explode_speed)
    pyglow.led(14, 60)
    sleep(explode_speed)
    pyglow.led(8, 60)
    sleep(explode_speed)
    pyglow.led(13, 70)
    sleep(explode_speed)
    pyglow.led(7, 70)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(12, 10)
    sleep(explode_speed)
    pyglow.led(6, 10)
    sleep(explode_speed)
    pyglow.led(17, 20)
    sleep(explode_speed)
    pyglow.led(11, 20)
    sleep(explode_speed)
    pyglow.led(16, 30)
    sleep(explode_speed)
    pyglow.led(10, 30)
    sleep(explode_speed)
    pyglow.led(15, 40)
    sleep(explode_speed)
    pyglow.led(9, 40)
    sleep(explode_speed)
    pyglow.led(14, 50)
    sleep(explode_speed)
    pyglow.led(8, 50)
    sleep(explode_speed)
    pyglow.led(13, 60)
    sleep(explode_speed)
    pyglow.led(7, 60)
    sleep(explode_speed)
    # Fade Body 5 -1, Head and Tail
    pyglow.led(12, 0)
    sleep(explode_speed)
    pyglow.led(6, 0)
    sleep(explode_speed)
    pyglow.led(17, 10)
    sleep(explode_speed)
    pyglow.led(11, 10)
    sleep(explode_speed)
    pyglow.led(16, 20)
    sleep(explode_speed)
    pyglow.led(10, 20)
    sleep(explode_speed)
    pyglow.led(15, 30)
    sleep(explode_speed)
    pyglow.led(9, 30)
    sleep(explode_speed)
    pyglow.led(14, 40)
    sleep(explode_speed)
    pyglow.led(8, 40)
    sleep(explode_speed)
    pyglow.led(13, 50)
    sleep(explode_speed)
    pyglow.led(7, 50)
    sleep(explode_speed)
    # Fade Body 4 -1, Head and Tail
    pyglow.led(17, 0)
    sleep(explode_speed)
    pyglow.led(11, 0)
    sleep(explode_speed)
    pyglow.led(16, 10)
    sleep(explode_speed)
    pyglow.led(10, 10)
    sleep(explode_speed)
    pyglow.led(15, 20)
    sleep(explode_speed)
    pyglow.led(9, 20)
    sleep(explode_speed)
    pyglow.led(14, 30)
    sleep(explode_speed)
    pyglow.led(8, 30)
    sleep(explode_speed)
    pyglow.led(13, 40)
    sleep(explode_speed)
    pyglow.led(7, 40)
    sleep(explode_speed)
    # Fade Body 3 -1, Head and Tail
    pyglow.led(16, 0)
    sleep(explode_speed)
    pyglow.led(10, 0)
    sleep(explode_speed)
    pyglow.led(15, 10)
    sleep(explode_speed)
    pyglow.led(9, 10)
    sleep(explode_speed)
    pyglow.led(14, 20)
    sleep(explode_speed)
    pyglow.led(8, 20)
    sleep(explode_speed)
    pyglow.led(13, 30)
    sleep(explode_speed)
    pyglow.led(7, 30)
    sleep(explode_speed)
    # Fade Body 2 - 1, Head and Tail
    pyglow.led(15, 0)
    sleep(explode_speed)
    pyglow.led(9, 0)
    sleep(explode_speed)
    pyglow.led(14, 10)
    sleep(explode_speed)
    pyglow.led(8, 10)
    sleep(explode_speed)
    pyglow.led(13, 20)
    sleep(explode_speed)
    pyglow.led(7, 20)
    sleep(explode_speed)
    # Fade Body 1, Head and Tail
    pyglow.led(14, 0)
    sleep(explode_speed)
    pyglow.led(8, 0)
    sleep(explode_speed)
    pyglow.led(13, 10)
    sleep(explode_speed)
    pyglow.led(7, 10)
    sleep(explode_speed)
    # Fade Head and Tail
    pyglow.led(13, 0)
    sleep(explode_speed)
    pyglow.led(7, 0)
    sleep(explode_speed)

# Start the program
try:
    while True:
        # Snakes 12, 13, 21, 23, 31, 32
        slithering_exploding_snake_12()
        sleep(1)
        slithering_exploding_snake_13()
        sleep(1)
        slithering_exploding_snake_21()
        sleep(1)
        slithering_exploding_snake_23()
        sleep(1)
        slithering_exploding_snake_31()
        sleep(1)
        slithering_exploding_snake_32()
        sleep(1)
        # Snakes 12, 23, 31, 13, 32, 21
        slithering_exploding_snake_12()
        sleep(1)
        slithering_exploding_snake_23()
        sleep(1)
        slithering_exploding_snake_31()
        sleep(1)
        slithering_exploding_snake_13()
        sleep(1)
        slithering_exploding_snake_32()
        sleep(1)
        slithering_exploding_snake_21()
        sleep(1)
        # Snakes 13, 12, 23, 21, 31, 32
        slithering_exploding_snake_13()
        sleep(1)
        slithering_exploding_snake_12()
        sleep(1)
        slithering_exploding_snake_23()
        sleep(1)
        slithering_exploding_snake_21()
        sleep(1)
        slithering_exploding_snake_31()
        sleep(1)
        slithering_exploding_snake_32()
        sleep(1)
        # Snakes 13, 32, 21, 12, 23, 31
        slithering_exploding_snake_13()
        sleep(1)
        slithering_exploding_snake_32()
        sleep(1)
        slithering_exploding_snake_21()
        sleep(1)
        slithering_exploding_snake_12()
        sleep(1)
        slithering_exploding_snake_23()
        sleep(1)
        slithering_exploding_snake_31()
        sleep(1)
# Stop the exploding snake carnage with Ctrl-C
except KeyboardInterrupt:
    pyglow.all()
