#!/usr/bin/python3
"""
Exploding Millipedes

I think the title is self explanatory. This program will run a
random millipede at a slow speed, a random millipede  at a
medium/slow speed, a random millipede at a medium speed, a
a random millipede at a fast speed, then a random millipede
at a random speed. The millipedes will explode.

....................

Functions:

- millipede_12: Lights up and "ripples" the LEDs on arms 1 and 2
- millipede_13: Lights up and "ripples" the LEDs on arms 1 and 3
- millipede_21: Lights up and "ripples" the LEDs on arms 2 and 1
- millipede_23: Lights up and "ripples" the LEDs on arms 2 and 3
- millipede_31: Lights up and "ripples" the LEDs on arms 3 and 1
- millipede_32: Lights up and "ripples" the LEDs on arms 3 and 2
- pulse_millipede_12_or_21: Pulses millipede 12 or 21
- pulse_millipede_13_or_31: Pulses millipede 13 or 31
- pulse_millipede_23_or_32: Pulses millipede 23 or 32
- explode_millipede_12_or_21: Explodes millipede 12 or 21
- explode_millipede_13_or_31: Explodes millipede 13 or 31
- explode_millipede_23_or_32: Explodes millipede 23 or 32
....................

Requirements: PyGlow.py

....................

Author: Paul Ryan

This program was written on a Raspberry Pi using the Geany IDE.
"""
########################################################################
#                          Import modules                              #
########################################################################

from time import sleep
import random
from PyGlow import PyGlow

########################################################################
#                           Variables                                  #
########################################################################

PYGLOW = PyGlow()
SLEEP_SPEED = 0.10

########################################################################
#                           Initialize                                 #
########################################################################

PYGLOW.all(0)

########################################################################
#                            Functions                                 #
########################################################################


def main():
    """
    The main function
    """

    millipede_ripple_speeds = [0.1, 0.075, 0.05, 0.025]

    millipedes = [millipede_12, millipede_13, millipede_21, millipede_23,
                  millipede_31, millipede_32]

    print("Press Ctrl-C to stop the program.")
    try:
        while True:
            # Random Slow millipede
            random.choice(millipedes)(0.1)
            # Random Slow/Medium millipede
            random.choice(millipedes)(0.075)
            # Random Medium millipede
            random.choice(millipedes)(0.05)
            # Random Fast millipede
            random.choice(millipedes)(0.025)
            # Random millipede, Random Speed
            random.choice(millipedes)(random.choice(millipede_ripple_speeds))
    # Stop the program and turn off LEDs with Ctrl-C
    except KeyboardInterrupt:
        print("\nExiting program.")
        PYGLOW.all(0)


def millipede_12(ripple_speed):
    """
    Lights up and "ripples" the LEDs on arms 1 and 2
    """
    # Uncomment the following print lines for testing/debugging
    # print("Centipede 12")
    # print("Centipede speed is: ", ripple_speed)

    ripple_speed = ripple_speed

    # millipede 12 Head
    PYGLOW.led(1, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    # millipede 12 Body 1
    PYGLOW.led(2, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    # millipede 12 Body 2
    PYGLOW.led(3, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 2 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    # millipede 12 Body 3
    PYGLOW.led(4, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 3 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    # millipede 12 Body 4
    PYGLOW.led(5, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 4 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    # millipede 12 Body 5
    PYGLOW.led(6, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 5 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    # millipede 12 Body 6
    PYGLOW.led(18, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 6 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    # millipede 12 Body 7
    PYGLOW.led(11, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 7 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    # millipede 12 Body 8
    PYGLOW.led(10, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 8 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    # millipede 12 Body 9
    PYGLOW.led(9, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 9 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    # millipede 12 Body 10
    PYGLOW.led(8, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 10 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    # millipede 12 Body 11
    PYGLOW.led(7, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 11 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    # Pulse (Ripple faster)
    pulse_millipede_12_or_21()
    # Explode
    explode_millipede_12_or_21()

    sleep(1)


def millipede_13(ripple_speed):
    """
    Lights up and "ripples" the LEDs on arms 1 and 3
    """
    # Uncomment the following print lines for testing/debugging
    # print("Centipede 13")
    # print("Centipede speed is: ", ripple_speed)

    ripple_speed = ripple_speed

    # Turn on millipede 13
    # Turn on Head
    PYGLOW.led(1, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    # Turn on Body 1
    PYGLOW.led(2, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    # Turn on Body 2
    PYGLOW.led(3, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 2 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    # Turn on Body 3
    PYGLOW.led(4, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 3 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    # Turn on Body 4
    PYGLOW.led(5, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 4 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    # Turn on Body 5
    PYGLOW.led(12, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 5 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    # Turn on Body 6
    PYGLOW.led(18, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 6 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    # Turn on Body 7
    PYGLOW.led(17, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 7 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    # Turn on Body 8
    PYGLOW.led(16, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 8 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    # Turn on Body 9
    PYGLOW.led(15, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 9 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    # Turn on Body 10
    PYGLOW.led(14, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 10 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    # Turn on Body 11
    PYGLOW.led(13, 120)
    sleep(SLEEP_SPEED)
    # Ripple Body 1 - 11 and Head
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    # Pulse (Ripple faster)
    pulse_millipede_13_or_31()
    # Explode
    explode_millipede_13_or_31()

    sleep(1)


def millipede_21(ripple_speed):
    """
    Lights up and "ripples" the LEDs on arms 2 and 1
    """
    # Uncomment the following print lines for testing/debugging
    # print("Centipede 21")
    # print("Centipede speed is: ", ripple_speed)

    ripple_speed = ripple_speed

    # Turn on millipede 21
    # Turn on Head
    PYGLOW.led(7, 120)
    sleep(SLEEP_SPEED)
    # Ripple head
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    # Turn on Body 1
    PYGLOW.led(8, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    # Turn on Body 2
    PYGLOW.led(9, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 2
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    # Turn on Body 3
    PYGLOW.led(10, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 3
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    # Turn on Body 4
    PYGLOW.led(11, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 4
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    # Turn on Body 5
    PYGLOW.led(18, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 5
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    # Turn on Body 6
    PYGLOW.led(6, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 6
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    # Turn on Body 7
    PYGLOW.led(5, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 7
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    # Turn on Body 8
    PYGLOW.led(4, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 8
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    # Turn on Body 9
    PYGLOW.led(3, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 9
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    # Turn on Body 10
    PYGLOW.led(2, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 10
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    # Turn on Body 11
    PYGLOW.led(1, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 11
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    # Pulse (Ripple faster)
    pulse_millipede_12_or_21()
    # Explode
    explode_millipede_12_or_21()

    sleep(1)


def millipede_23(ripple_speed):
    """
    Lights up and "ripples" the LEDs on arms 2 and 3
    """
    # Uncomment the following print lines for testing/debugging
    # print("Centipede 23")
    # print("Centipede speed is: ", ripple_speed)

    ripple_speed = ripple_speed

    # Light up millipede 23
    # Turn on Head
    PYGLOW.led(7, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    # Turn on Body 1
    PYGLOW.led(8, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    # Turn on Body 2
    PYGLOW.led(9, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 2
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    # Turn on Body 3
    PYGLOW.led(10, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 3
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    # Turn on Body 4
    PYGLOW.led(11, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 4
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    # Turn on Body 5
    PYGLOW.led(12, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 5
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    # Turn on Body 6
    PYGLOW.led(6, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 6
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    # Turn on Body 7
    PYGLOW.led(17, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 7
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    # Turn on Body 8
    PYGLOW.led(16, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 8
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    # Turn on Body 9
    PYGLOW.led(15, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 9
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    # Turn on Body 10
    PYGLOW.led(14, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 10
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    # Turn on Body 11
    PYGLOW.led(13, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 11
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    # Pulse (Ripple faster)
    pulse_millipede_23_or_32()
    # Explode
    explode_millipede_23_or_32()

    sleep(1)


def millipede_31(ripple_speed):
    """
    Lights up and "ripples" the LEDs on arms 3 and 1
    """
    # Uncomment the following print lines for testing/debugging
    # print("Centipede 31")
    # print("Centipede speed is: ", ripple_speed)

    ripple_speed = ripple_speed

    # Light up millipede 31
    # Turn on Head
    PYGLOW.led(13, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    # Turn on Body 1
    PYGLOW.led(14, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    # Turn on Body 2
    PYGLOW.led(15, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 2
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    # Turn on Body 3
    PYGLOW.led(16, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 3
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    # Turn on Body 4
    PYGLOW.led(17, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 4
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    # Turn on Body 5
    PYGLOW.led(18, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 5
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    # Turn on Body 6
    PYGLOW.led(12, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 6
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    # Turn on Body 7
    PYGLOW.led(5, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 7
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    # Turn on Body 8
    PYGLOW.led(4, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 8
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    # Turn on Body 9
    PYGLOW.led(3, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 9
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    # Turn on Body 10
    PYGLOW.led(2, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 10
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    # Turn on Body 11
    PYGLOW.led(1, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 11
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(18, 60)
    sleep(ripple_speed)
    PYGLOW.led(18, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(5, 60)
    sleep(ripple_speed)
    PYGLOW.led(5, 120)
    sleep(ripple_speed)
    PYGLOW.led(4, 60)
    sleep(ripple_speed)
    PYGLOW.led(4, 120)
    sleep(ripple_speed)
    PYGLOW.led(3, 60)
    sleep(ripple_speed)
    PYGLOW.led(3, 120)
    sleep(ripple_speed)
    PYGLOW.led(2, 60)
    sleep(ripple_speed)
    PYGLOW.led(2, 120)
    sleep(ripple_speed)
    PYGLOW.led(1, 60)
    sleep(ripple_speed)
    PYGLOW.led(1, 120)
    sleep(ripple_speed)
    # Pulse (Ripple faster)
    pulse_millipede_13_or_31()
    # Explode
    explode_millipede_13_or_31()

    sleep(1)


def millipede_32(ripple_speed):
    """
    Lights up and "ripples" the LEDs on arms 3 and 2
    """
    # Uncomment the following print lines for testing/debugging
    # print("Centipede 32")
    # print("Centipede speed is: ", ripple_speed)

    ripple_speed = ripple_speed

    # Light up Centipede 32
    # Turn on Head
    PYGLOW.led(13, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    # Turn on Body 1
    PYGLOW.led(14, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    # Turn on Body 2
    PYGLOW.led(15, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 2
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    # Turn on Body 3
    PYGLOW.led(16, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 3
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    # Turn on Body 4
    PYGLOW.led(17, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 4
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    # Turn on Body 5
    PYGLOW.led(6, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 5
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    # Turn on Body 6
    PYGLOW.led(12, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 6
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    # Turn on Body 7
    PYGLOW.led(11, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 7
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    # Turn on Body 8
    PYGLOW.led(10, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 8
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    # Turn on Body 9
    PYGLOW.led(9, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 9
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    # Turn on Body 10
    PYGLOW.led(8, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 10
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    # Turn on Body 11
    PYGLOW.led(7, 120)
    sleep(SLEEP_SPEED)
    # Ripple Head and Body 1 - 11
    PYGLOW.led(13, 60)
    sleep(ripple_speed)
    PYGLOW.led(13, 120)
    sleep(ripple_speed)
    PYGLOW.led(14, 60)
    sleep(ripple_speed)
    PYGLOW.led(14, 120)
    sleep(ripple_speed)
    PYGLOW.led(15, 60)
    sleep(ripple_speed)
    PYGLOW.led(15, 120)
    sleep(ripple_speed)
    PYGLOW.led(16, 60)
    sleep(ripple_speed)
    PYGLOW.led(16, 120)
    sleep(ripple_speed)
    PYGLOW.led(17, 60)
    sleep(ripple_speed)
    PYGLOW.led(17, 120)
    sleep(ripple_speed)
    PYGLOW.led(6, 60)
    sleep(ripple_speed)
    PYGLOW.led(6, 120)
    sleep(ripple_speed)
    PYGLOW.led(12, 60)
    sleep(ripple_speed)
    PYGLOW.led(12, 120)
    sleep(ripple_speed)
    PYGLOW.led(11, 60)
    sleep(ripple_speed)
    PYGLOW.led(11, 120)
    sleep(ripple_speed)
    PYGLOW.led(10, 60)
    sleep(ripple_speed)
    PYGLOW.led(10, 120)
    sleep(ripple_speed)
    PYGLOW.led(9, 60)
    sleep(ripple_speed)
    PYGLOW.led(9, 120)
    sleep(ripple_speed)
    PYGLOW.led(8, 60)
    sleep(ripple_speed)
    PYGLOW.led(8, 120)
    sleep(ripple_speed)
    PYGLOW.led(7, 60)
    sleep(ripple_speed)
    PYGLOW.led(7, 120)
    sleep(ripple_speed)
    # Pulse (Ripple faster)
    pulse_millipede_23_or_32()
    # Explode
    explode_millipede_23_or_32()

    sleep(1)


def pulse_millipede_12_or_21():
    """
    Pulses either millipede 12 or 21
    """

    ripple_speed = 0.15
    counter = 10

    while ripple_speed > 0.02:
        # Ripple Head and Body 1 - 11
        PYGLOW.led(6, 60)
        PYGLOW.led(18, 60)
        sleep(ripple_speed)
        PYGLOW.led(6, 120)
        PYGLOW.led(18, 120)
        sleep(ripple_speed)
        PYGLOW.led(5, 60)
        PYGLOW.led(11, 60)
        sleep(ripple_speed)
        PYGLOW.led(5, 120)
        PYGLOW.led(11, 120)
        sleep(ripple_speed)
        PYGLOW.led(4, 60)
        PYGLOW.led(10, 60)
        sleep(ripple_speed)
        PYGLOW.led(4, 120)
        PYGLOW.led(10, 120)
        sleep(ripple_speed)
        PYGLOW.led(3, 60)
        PYGLOW.led(9, 60)
        sleep(ripple_speed)
        PYGLOW.led(3, 120)
        PYGLOW.led(9, 120)
        sleep(ripple_speed)
        PYGLOW.led(2, 60)
        PYGLOW.led(8, 60)
        sleep(ripple_speed)
        PYGLOW.led(2, 120)
        PYGLOW.led(8, 120)
        sleep(ripple_speed)
        PYGLOW.led(1, 60)
        PYGLOW.led(7, 60)
        sleep(ripple_speed)
        PYGLOW.led(1, 120)
        PYGLOW.led(7, 120)
        sleep(ripple_speed)
        # Decrement ripple_speed
        ripple_speed -= 0.01
    # Reset ripple_speed
    ripple_speed = 0.02
    while counter > 0:
        # Ripple Head and Body 1 - 11
        PYGLOW.led(6, 60)
        PYGLOW.led(18, 60)
        sleep(ripple_speed)
        PYGLOW.led(6, 120)
        PYGLOW.led(18, 120)
        sleep(ripple_speed)
        PYGLOW.led(5, 60)
        PYGLOW.led(11, 60)
        sleep(ripple_speed)
        PYGLOW.led(5, 120)
        PYGLOW.led(11, 120)
        sleep(ripple_speed)
        PYGLOW.led(4, 60)
        PYGLOW.led(10, 60)
        sleep(ripple_speed)
        PYGLOW.led(4, 120)
        PYGLOW.led(10, 120)
        sleep(ripple_speed)
        PYGLOW.led(3, 60)
        PYGLOW.led(9, 60)
        sleep(ripple_speed)
        PYGLOW.led(3, 120)
        PYGLOW.led(9, 120)
        sleep(ripple_speed)
        PYGLOW.led(2, 60)
        PYGLOW.led(8, 60)
        sleep(ripple_speed)
        PYGLOW.led(2, 120)
        PYGLOW.led(8, 120)
        sleep(ripple_speed)
        PYGLOW.led(1, 60)
        PYGLOW.led(7, 60)
        sleep(ripple_speed)
        PYGLOW.led(1, 120)
        PYGLOW.led(7, 120)
        sleep(ripple_speed)
        # Decrement counter
        counter -= 1
    sleep(1)


def pulse_millipede_13_or_31():
    """
    Pulses either millipede 13 or 31
    """

    ripple_speed = 0.15
    counter = 10

    while ripple_speed > 0.02:
        # Ripple Head and Body 1 - 11
        PYGLOW.led(18, 60)
        PYGLOW.led(12, 60)
        sleep(ripple_speed)
        PYGLOW.led(18, 120)
        PYGLOW.led(12, 120)
        sleep(ripple_speed)
        PYGLOW.led(17, 60)
        PYGLOW.led(5, 60)
        sleep(ripple_speed)
        PYGLOW.led(17, 120)
        PYGLOW.led(5, 120)
        sleep(ripple_speed)
        PYGLOW.led(16, 60)
        PYGLOW.led(4, 60)
        sleep(ripple_speed)
        PYGLOW.led(16, 120)
        PYGLOW.led(4, 120)
        sleep(ripple_speed)
        PYGLOW.led(15, 60)
        PYGLOW.led(3, 60)
        sleep(ripple_speed)
        PYGLOW.led(15, 120)
        PYGLOW.led(3, 120)
        sleep(ripple_speed)
        PYGLOW.led(14, 60)
        PYGLOW.led(2, 60)
        sleep(ripple_speed)
        PYGLOW.led(14, 120)
        PYGLOW.led(2, 120)
        sleep(ripple_speed)
        PYGLOW.led(13, 60)
        PYGLOW.led(1, 60)
        sleep(ripple_speed)
        PYGLOW.led(13, 120)
        PYGLOW.led(1, 120)
        sleep(ripple_speed)
        # Decrement counter
        ripple_speed -= 0.01
    # Reset ripple_speed
    ripple_speed = 0.02
    while counter > 1:
        # Ripple Head and Body 1 - 11
        PYGLOW.led(18, 60)
        PYGLOW.led(12, 60)
        sleep(ripple_speed)
        PYGLOW.led(18, 120)
        PYGLOW.led(12, 120)
        sleep(ripple_speed)
        PYGLOW.led(17, 60)
        PYGLOW.led(5, 60)
        sleep(ripple_speed)
        PYGLOW.led(17, 120)
        PYGLOW.led(5, 120)
        sleep(ripple_speed)
        PYGLOW.led(16, 60)
        PYGLOW.led(4, 60)
        sleep(ripple_speed)
        PYGLOW.led(16, 120)
        PYGLOW.led(4, 120)
        sleep(ripple_speed)
        PYGLOW.led(15, 60)
        PYGLOW.led(3, 60)
        sleep(ripple_speed)
        PYGLOW.led(15, 120)
        PYGLOW.led(3, 120)
        sleep(ripple_speed)
        PYGLOW.led(14, 60)
        PYGLOW.led(2, 60)
        sleep(ripple_speed)
        PYGLOW.led(14, 120)
        PYGLOW.led(2, 120)
        sleep(ripple_speed)
        PYGLOW.led(13, 60)
        PYGLOW.led(1, 60)
        sleep(ripple_speed)
        PYGLOW.led(13, 120)
        PYGLOW.led(1, 120)
        sleep(ripple_speed)
        # Decrement counter
        counter -= 1
    # Sleep 1 second before exploding
    sleep(1)


def pulse_millipede_23_or_32():
    """
    Pulses either millipede 23 or 32
    """

    ripple_speed = 0.15
    counter = 10

    while ripple_speed > 0.02:
        # Ripple Head and Body 1 - 11
        PYGLOW.led(12, 60)
        PYGLOW.led(6, 60)
        sleep(ripple_speed)
        PYGLOW.led(12, 120)
        PYGLOW.led(16, 120)
        sleep(ripple_speed)
        PYGLOW.led(17, 60)
        PYGLOW.led(11, 60)
        sleep(ripple_speed)
        PYGLOW.led(17, 120)
        PYGLOW.led(11, 120)
        sleep(ripple_speed)
        PYGLOW.led(16, 60)
        PYGLOW.led(10, 60)
        sleep(ripple_speed)
        PYGLOW.led(16, 120)
        PYGLOW.led(10, 120)
        sleep(ripple_speed)
        PYGLOW.led(15, 60)
        PYGLOW.led(9, 60)
        sleep(ripple_speed)
        PYGLOW.led(15, 120)
        PYGLOW.led(9, 120)
        sleep(ripple_speed)
        PYGLOW.led(14, 60)
        PYGLOW.led(8, 60)
        sleep(ripple_speed)
        PYGLOW.led(14, 120)
        PYGLOW.led(8, 120)
        sleep(ripple_speed)
        PYGLOW.led(13, 60)
        PYGLOW.led(7, 60)
        sleep(ripple_speed)
        PYGLOW.led(13, 120)
        PYGLOW.led(7, 120)
        sleep(ripple_speed)
        # Decrement ripple_speed
        ripple_speed -= 0.01
    # Reset ripple_speed
    ripple_speed = 0.02
    while counter > 1:
        # Ripple Head and Body 1 - 11
        PYGLOW.led(12, 60)
        PYGLOW.led(6, 60)
        sleep(ripple_speed)
        PYGLOW.led(12, 120)
        PYGLOW.led(16, 120)
        sleep(ripple_speed)
        PYGLOW.led(17, 60)
        PYGLOW.led(11, 60)
        sleep(ripple_speed)
        PYGLOW.led(17, 120)
        PYGLOW.led(11, 120)
        sleep(ripple_speed)
        PYGLOW.led(16, 60)
        PYGLOW.led(10, 60)
        sleep(ripple_speed)
        PYGLOW.led(16, 120)
        PYGLOW.led(10, 120)
        sleep(ripple_speed)
        PYGLOW.led(15, 60)
        PYGLOW.led(9, 60)
        sleep(ripple_speed)
        PYGLOW.led(15, 120)
        PYGLOW.led(9, 120)
        sleep(ripple_speed)
        PYGLOW.led(14, 60)
        PYGLOW.led(8, 60)
        sleep(ripple_speed)
        PYGLOW.led(14, 120)
        PYGLOW.led(8, 120)
        sleep(ripple_speed)
        PYGLOW.led(13, 60)
        PYGLOW.led(7, 60)
        sleep(ripple_speed)
        PYGLOW.led(13, 120)
        PYGLOW.led(7, 120)
        sleep(ripple_speed)
        # Decrement counter
        counter -= 1
    # Sleep 1 second before exploding
    sleep(1)


def explode_millipede_12_or_21():
    """
    Explodes millipede 12 or 21
    """

    explode_speed = 0.020

    # Explode snake 12 or 21
    PYGLOW.led(18, 0)
    sleep(explode_speed)
    PYGLOW.led(6, 0)
    sleep(explode_speed)
    PYGLOW.led(11, 0)
    sleep(explode_speed)
    PYGLOW.led(5, 0)
    sleep(explode_speed)
    PYGLOW.led(10, 0)
    sleep(explode_speed)
    PYGLOW.led(4, 0)
    sleep(explode_speed)
    PYGLOW.led(9, 0)
    sleep(explode_speed)
    PYGLOW.led(3, 0)
    sleep(explode_speed)
    PYGLOW.led(8, 0)
    sleep(explode_speed)
    PYGLOW.led(2, 0)
    sleep(explode_speed)
    PYGLOW.led(7, 0)
    sleep(explode_speed)
    PYGLOW.led(1, 0)
    sleep(explode_speed)


def explode_millipede_13_or_31():
    """
    Explodes millipede 13 or 31
    """

    explode_speed = 0.020

    # Explode snake 13 or 31
    PYGLOW.led(18, 0)
    sleep(explode_speed)
    PYGLOW.led(12, 0)
    sleep(explode_speed)
    PYGLOW.led(17, 0)
    sleep(explode_speed)
    PYGLOW.led(5, 0)
    sleep(explode_speed)
    PYGLOW.led(16, 0)
    sleep(explode_speed)
    PYGLOW.led(4, 0)
    sleep(explode_speed)
    PYGLOW.led(15, 0)
    sleep(explode_speed)
    PYGLOW.led(3, 0)
    sleep(explode_speed)
    PYGLOW.led(14, 0)
    sleep(explode_speed)
    PYGLOW.led(2, 0)
    sleep(explode_speed)
    PYGLOW.led(13, 0)
    sleep(explode_speed)
    PYGLOW.led(1, 0)
    sleep(explode_speed)


def explode_millipede_23_or_32():
    """
    Explodes millipede 23 or 32
    """

    explode_speed = 0.020
    # Explode snake 23 or 32
    PYGLOW.led(12, 0)
    sleep(explode_speed)
    PYGLOW.led(6, 0)
    sleep(explode_speed)
    PYGLOW.led(17, 0)
    sleep(explode_speed)
    PYGLOW.led(11, 0)
    sleep(explode_speed)
    PYGLOW.led(16, 0)
    sleep(explode_speed)
    PYGLOW.led(10, 0)
    sleep(explode_speed)
    PYGLOW.led(15, 0)
    sleep(explode_speed)
    PYGLOW.led(9, 0)
    sleep(explode_speed)
    PYGLOW.led(14, 0)
    sleep(explode_speed)
    PYGLOW.led(8, 0)
    sleep(explode_speed)
    PYGLOW.led(13, 0)
    sleep(explode_speed)
    PYGLOW.led(7, 0)
    sleep(explode_speed)


if __name__ == '__main__':
    main()
